In [53]:
import pandas as pd
import numpy as np
import re
import matplotlib.pyplot as plt

Nickel (Ni)

In [54]:
ni_df = pd.read_csv('metalpdb_report.tsv', sep = '\t')
ni_df.head(6)

,Site Id,Metals,Metals Info,Ligands
0,1b9m_1,Ni;,NI_263(A)_NI;,"ASP_139(A), HIS_140(A), HIS_146(A), ASP_148(A)..."
1,1e0o_1,Ni;,NI_903(B)_NI;,HIS_287(B) HOH_2010(B);
2,1e0o_2,Ni;,NI_902(B)_NI;,"HIS_245(B), ASP_247(B);"
3,1e0o_3,Ni;,NI_900(D)_NI;,"HIS_93(C), HIS_254(D) HOH_2011(D), HOH_2012(D);"
4,1e20_1,Ni;,NI_802(B)_NI;,"HOH_2052(A), HOH_2053(A);"
5,1e42_4,Ni;,NI_970(B)_NI;,"HIS_735(B) HOH_2043(B), HOH_2049(B), HOH_2096(..."

In [55]:
ligand_list = []
for ligand in ni_df['Ligands']:
    temp = ligand.split(' ')
    ligand_list.append(temp)
ligand_list

[['ASP_139(A),', 'HIS_140(A),', 'HIS_146(A),', 'ASP_148(A)', 'HOH_465(A);'],
 ['HIS_287(B)', 'HOH_2010(B);'],
 ['HIS_245(B),', 'ASP_247(B);'],
 ['HIS_93(C),', 'HIS_254(D)', 'HOH_2011(D),', 'HOH_2012(D);'],
 ['HOH_2052(A),', 'HOH_2053(A);'],
 ['HIS_735(B)',
  'HOH_2043(B),',
  'HOH_2049(B),',
  'HOH_2096(A),',
  'HOH_2097(A),',
  'HOH_2148(A);'],
 ['HIS_189(L);'],
 ['HIS_220(C);'],
 ['ASN_42(A),',
  'HIS_68(A),',
  'GLU_105(A)',
  'FMN_401(A),',
  'HOH_1008(A),',
  'HOH_1009(A);'],
 ['HIS_77(A)', 'HOH_1030(A);'],
 ['HIS_54(A)',
  'GDP_502(A),',
  'HOH_1016(A),',
  'HOH_1154(A),',
  'HOH_1155(A),',
  'HOH_1156(A);'],
 ['HIS_247(A)', 'HOH_14(A),', 'HOH_59(A),', 'HOH_60(A);'],
 ['HIS_101(B)', 'TRS_303(B),', 'TRS_304(B);'],
 ['HIS_36(B)', 'HOH_435(B);'],
 ['HIS_5(A),',
  'GLU_56(A),',
  'HIS_74(B),',
  'GLU_122(B)',
  'HOH_140(B),',
  'HOH_152(B);'],
 ['HIS_5(B),',
  'GLU_56(B),',
  'HIS_74(A),',
  'GLU_122(A)',
  'HOH_142(B),',
  'HOH_1213(A);'],
 ['HIS_246(C),',
  'HIS_272(C)',
  'KCX_217(C),',
  'HOH_723(C),',
  'HOH_724(C),',
  'HOH_726(C);'],
 ['HIS_69(A)', 'HOH_2059(A),', 'HOH_2061(A),', 'HOH_2062(A);'],
 ['ALA_1(A)', 'HOH_2001(A);'],
 ['TRP_262(B)',
  'HOH_2183(D),',
  'HOH_2184(D),',
  'HOH_2193(B),',
  'HOH_2195(B);'],
 ['ASP_139(B),', 'ASP_141(B),', 'HIS_146(B)', 'HOH_2020(B);'],
 ['HIS_402(D),', 'HIS_404(D);'],
 ['HIS_0(A)', 'HOH_2002(A);'],
 ['HIS_49(A)', 'HOH_2038(A);'],
 ['GLN_147(D)', 'F43_1550(A),', 'COM_1552(A);'],
 ['ASP_76(D);'],
 ['HIS_103(D)',
  'HOH_2091(D),',
  'HOH_2092(D),',
  'HOH_2093(D),',
  'HOH_2143(D);'],
 ['HIS_211(A)', 'HOH_2067(A),', 'HOH_2115(A),', 'HOH_2117(A);'],
 ['HIS_305(A);'],
 ['HIS_263(A);'],
 ['GLY_499(B)', 'HOH_1272(B),', 'HOH_1319(B),', 'HOH_1320(B);'],
 ['ALA_1(A),', 'HIS_4(A),', 'ASP_343(A)', 'HOH_1497(A);'],
 ['HIS_92(A),',
  'HIS_96(A),',
  'HIS_102(A),',
  'TYR_149(A)',
  'HOH_300(A),',
  'HOH_600(A);'],
 ['HIS_296(A)', 'HOH_534(A),', 'HOH_552(A);'],
 ['ALA_34(A),', 'ASP_37(A),', 'HIS_38(A);'],
 ['HIS_431(B),',
  'HIS_433(B),',
  'HIS_592(B)',
  'HOH_1014(B),',
  'HOH_1017(B),',
  'HOH_1143(B);'],
 ['HIS_-2(B),', 'HIS_0(B);'],
 ['HIS_176(K)', 'CL_12(K),', 'HOH_32(C),', 'CL_95(K),', 'HOH_110(C);'],
 ['HIS_162(X),', 'HIS_211(X)', 'HOH_2087(X),', 'HOH_2103(X);'],
 ['ASP_23(X);'],
 ['ASP_173(X),', 'ASP_175(X),', 'ASP_198(X)', 'HOH_2099(X);'],
 ['CYS_169(A),', 'CYS_173(A),', 'HIS_260(A)', 'CL_300(A);'],
 ['HIS_92(H)', 'HNI_147(H);'],
 ['LYS_16(B);GLU_96(A)',
  'HOH_469(B);GLU_96(B)',
  'HOH_469(B);LYS_16(A)',
  'HOH_469(B);'],
 ['ASN_175(A)', 'HOH_346(A),', 'HOH_347(A),', 'HOH_348(A),', 'HOH_349(A);'],
 ['HIS_79(A),', 'GLU_87(A),', 'HIS_146(A),', 'HIS_148(A)', 'HOH_241(A);'],
 ['ALA_206(A),', 'ARG_248(A);'],
 ['HIS_148(A)', 'HOH_937(A),', 'HOH_938(A),', 'HOH_939(A),', 'HOH_940(A);'],
 ['HIS_6(A)', 'HOH_936(A),', 'HOH_948(A),', 'HOH_955(A),', 'HOH_961(A);'],
 ['HIS_303(A);'],
 ['HIS_114(A)', 'HOH_2050(A),', 'HOH_2116(A),', 'HOH_2117(A);'],
 ['ARG_132(A),', 'HIS_191(A),', 'GLU_193(A)', 'CL_1436(A);'],
 ['LYS_13(A)', 'HOH_565(A);'],
 ['HIS_65(A),',
  'HIS_71(A)',
  'HOH_512(A),',
  'HOH_514(A),',
  'HOH_523(A),',
  'HOH_566(A);'],
 ['HIS_36(A),', 'GLU_126(F)', 'HOH_357(F),', 'HOH_375(F),', 'HOH_540(A);'],
 ['HIS_105(B);'],
 ['HIS_55(A),',
  'HIS_57(A),',
  'HIS_200(A),',
  'ASP_279(A)',
  'HOH_9072(A),',
  'HOH_9075(A);'],
 ['HIS_86(A),',
  'HIS_88(A),',
  'HIS_140(A)',
  'HOH_359(A),',
  'HOH_360(A),',
  'HOH_361(A);'],
 ['CYS_114(A),', 'HIS_157(A),', 'HIS_161(A)', 'HOH_511(A);'],
 ['HIS_139(A),', 'HIS_141(A);'],
 ['ASP_131(A),',
  'ASP_142(A),',
  'GLU_269(A)',
  'T03_289(A);ASP_142(A),',
  'HIS_205(A),',
  'GLU_238(A),',
  'GLU_269(A)',
  'T03_289(A);HIS_114(A)',
  'T03_289(A),',
  'CL_292(A),',
  'HOH_447(A);'],
 ['TCN_1(D);'],
 ['HIS_479(A)', 'HOH_2545(A);'],
 ['HIS_31(A),', 'HIS_100(A)', 'TRS_109(B),', 'HOH_119(B);'],
 ['HIS_213(D);'],
 ['ASP_129(A),', 'HIS_138(A)', 'HOH_2024(A);'],
 ['HIS_415(A),', 'GLU_459(A)', 'HOH_2146(A);'],
 ['HIS_195(A),', 'ASP_243(A)', 'HOH_2086(A);'],
 ['HIS_337(A)', 'HOH_2127(A);'],
 ['HIS_423(A);'],
 ['HIS_44(E),', 'HIS_46(E),', 'GLU_51(E),', 'HIS_85(E)', 'UNL_501(E);'],
 ['HIS_525(A),', 'ASP_529(A);'],
 ['HIS_76(A),',
  'ASP_168(A),',
  'HIS_172(A)',
  'HOH_403(A),',
  'HOH_436(A),',
  'HOH_449(A);'],
 ['HIS_252(A);'],
 ['HIS_590(A),', 'HIS_592(A);'],
 ['HIS_587(A),', 'HIS_589(A);'],
 ['HIS_383(A),', 'GLU_392(A)', 'HOH_81(A);'],
 ['HIS_47(E),', 'ASP_74(G),', 'GLU_78(G)', 'HOH_2016(G),', 'HOH_2018(G);'],
 ['HIS_47(C),', 'ASP_74(A),', 'GLU_78(A)', 'HOH_2011(C),', 'HOH_2025(A);'],
 ['HIS_76(B),', 'HIS_87(D),', 'HIS_89(D),', 'CYS_95(D);'],
 ['HIS_76(C),', 'HIS_87(A),', 'HIS_89(A),', 'CYS_95(A);'],
 ['HIS_59(A),', 'HIS_63(A);'],
 ['ALA_1(A),', 'ASP_39(A);'],
 ['HIS_73(A),', 'HIS_77(A);'],
 ['GLU_36(B)', 'HOH_538(B),', 'HOH_539(B),', 'HOH_540(B);'],
 ['HOH_550(A),', 'HOH_556(A),', 'HOH_558(A),', 'HOH_560(A);'],
 ['HIS_25(A),',
  'GLU_77(A)',
  'HOH_480(A),',
  'HOH_483(A),',
  'HOH_486(A),',
  'HOH_563(A);'],
 ['ALA_2(A)', 'HOH_404(A),', 'HOH_427(A),', 'HOH_464(A);'],
 ['HIS_3(B),', 'HIS_6(B),', 'HIS_8(B);'],
 ['HIS_187(A),',
  'ASP_189(A),',
  'HIS_273(A)',
  'HOH_715(A),',
  'HOH_716(A),',
  'HOH_717(A);'],
 ['HIS_107(C)',
  'HOH_583(C),',
  'HOH_584(C),',
  'HOH_594(C),',
  'HOH_595(C),',
  'HOH_596(C),',
  'HOH_599(C);'],
 ['HIS_53(A)', 'HOH_264(A),', 'HOH_268(A),', 'HOH_295(A);'],
 ['HIS_0(A)', 'CL_261(A),', 'CL_262(A);'],
 ['HIS_83(A)', 'HOH_523(A),', 'HOH_524(A),', 'HOH_525(A),', 'HOH_526(A);'],
 ['ASP_287(B),', 'ASP_289(B),', 'ASP_291(B)', 'SEP_116(B),', 'HOH_706(B);'],
 ['HOH_589(B);'],
 ['HIS_201(B)', 'HOH_590(B),', 'HOH_591(B),', 'HOH_599(B);'],
 ['HOH_484(A),', 'HOH_485(A);'],
 ['HIS_500(A)',
  'CL_2002(A),',
  'HOH_2048(A),',
  'HOH_2119(A),',
  'HOH_2121(A),',
  'HOH_2325(A);'],
 ['HIS_700(A)',
  'HOH_2058(A),',
  'HOH_2176(A),',
  'HOH_2177(A),',
  'HOH_2489(A);'],
 ['HIS_882(A)',
  'CL_1996(A),',
  'CL_1997(A),',
  'CL_1998(A),',
  'CL_1999(A),',
  'CL_2000(A);'],
 ['ASP_75(B);'],
 ['GLU_32(B),', 'ASP_36(B);'],
 ['GLU_32(B),', 'ASP_36(B),', 'LEU_120(A),', 'VAL_123(A);'],
 ['SER_253(J),',
  'SER_255(J),',
  'THR_328(J),',
  'ASN_1641(D)',
  'HOH_2001(J),',
  'HOH_2002(J);'],
 ['HIS_6(B),',
  'HIS_8(B),',
  'GLU_92(B),',
  'ASP_204(B);GLU_92(B),',
  'HIS_128(B),',
  'HIS_153(B);'],
 ['HOH_2054(A),', 'HOH_2059(A),', 'HOH_2060(A);'],
 ['HIS_96(C),', 'ASP_98(C),', 'HIS_157(C)', 'IMD_501(C),', 'IMD_502(C);'],
 ['GLU_367(A)', 'HOH_2068(A),', 'HOH_2151(A),', 'HOH_2248(A);'],
 ['HIS_1805(X)', 'HOH_2(X),', 'HOH_3(X),', 'HOH_82(X);'],
 ['HIS_100(A)', 'ACO_162(B),', 'ACO_164(A);'],
 ['GLU_225(B),', 'GLU_231(A)', 'HOH_2022(A);'],
 ['GLU_225(A),', 'GLU_231(B)', 'HOH_2007(B),', 'HOH_2021(B);'],
 ['HIS_145(B),', 'GLU_151(B),', 'HIS_234(B);'],
 ['GLU_245(C)', 'HOH_2070(C);'],
 ['ASP_319(B),',
  'VAL_320(B),',
  'ASP_438(B),',
  'PRO_439(B),',
  'GLU_441(B)',
  'HOH_2104(B);'],
 ['ASP_308(A),', 'GLU_489(A),', 'ALA_536(A),', 'ASN_539(A)', 'HOH_2136(A);'],
 ['HIS_269(A),', 'LYS_272(A)', 'HOH_814(A),', 'HOH_815(A),', 'HOH_816(A);'],
 ['GLU_217(A),',
  'HIS_220(A),',
  'ASP_255(A)',
  'GLO_401(A),',
  'HOH_1001(A);GLU_181(A),',
  'GLU_217(A),',
  'ASP_245(A),',
  'ASP_287(A)',
  'GLO_401(A);'],
 ['GLU_134(A),', 'HIS_213(A)', 'CL_262(A);'],
 ['GLU_217(A),',
  'HIS_220(A),',
  'ASP_255(A),',
  'ASP_257(A)',
  'HOH_1001(A);GLU_181(A),',
  'GLU_217(A),',
  'ASP_245(A),',
  'ASP_287(A);'],
 ['HIS_42(A),', 'HIS_46(A),', 'GLU_63(A),', 'HIS_119(A),', 'MET_123(A);'],
 ['HIS_14(B),',
  'GLU_18(B),',
  'GLU_160(B)',
  'HOH_2055(B),',
  'HOH_2056(B),',
  'HOH_2269(B);'],
 ['HIS_56(B)', 'HOH_2140(B);'],
 ['EDO_1198(B),', 'HOH_2002(B),', 'HOH_2013(B);'],
 ['ASP_349(A),', 'ASP_365(A)', 'HOH_683(A);'],
 ['HIS_423(A),', 'HIS_425(A)', 'HOH_681(A),', 'HOH_682(A);'],
 ['HIS_722(B)',
  'HOH_1012(B),',
  'HOH_1013(B),',
  'HOH_1274(B),',
  'HOH_1280(B);'],
 ['ALA_1(A)', '144_503(A),', 'HOH_553(A);'],
 ['GLY_-3(B),', 'SER_-2(B),', 'HIS_-1(B);'],
 ['GLY_-3(A),', 'SER_-2(A),', 'HIS_-1(A);'],
 ['PO4_2005(A);'],
 ['ASP_52(A)', 'HOH_218(A),', 'HOH_281(A),', 'HOH_288(A),', 'HOH_325(A);'],
 ['ASP_101(A)', 'MM5_201(A),', 'HOH_278(A);'],
 ['MM5_202(A);'],
 ['HOH_555(A);'],
 ['ASP_142(A),',
  'HIS_205(A),',
  'GLU_238(A),',
  'GLU_269(A)',
  'Y10_286(A);ASP_131(A),',
  'ASP_142(A),',
  'GLU_269(A)',
  'Y10_286(A);'],
 ['HIS_61(A),', 'ASP_65(A)', 'HOH_444(A),', 'HOH_445(A);'],
 ['ASP_209(A),', 'ASP_271(A)', 'HOH_289(A),', 'HOH_459(A),', 'HOH_462(A);'],
 ['HIS_110(A),',
  'LYS_201(A)',
  'HOH_414(A),',
  'HOH_435(A),',
  'HOH_438(A),',
  'HOH_466(A);'],
 ['HIS_131(A)',
  'HOH_343(A),',
  'HOH_362(A),',
  'HOH_370(A),',
  'HOH_436(A),',
  'HOH_456(A);'],
 ['TRP_1(D)', 'TRS_2002(D);'],
 ['TRP_1(A),', 'PHE_94(B)', 'TRS_2003(A);'],
 ['TRP_1(B),', 'PHE_94(A)', 'TRS_2000(B),', 'HOH_3173(A);'],
 ['ASP_1(L),',
  'LYS_9(L),',
  'HIS_119(H)',
  'HOH_302(L),',
  'HOH_303(L),',
  'HOH_304(L);'],
 ['HOH_256(A),', 'HOH_288(A);;'],
 ['HOH_504(A);'],
 ['HIS_76(H),',
  'HIS_87(F),',
  'HIS_89(F),',
  'CYS_95(F);HIS_79(H),',
  'SER_82(H),',
  'HIS_89(F);'],
 ['HIS_58(A);'],
 ['ASP_11(B),',
  'HIS_395(B)',
  'HOH_1454(B),',
  'HOH_1468(B),',
  'HOH_1703(B),',
  'HOH_1714(B);'],
 ['HIS_48(A)', 'HOH_1423(A),', 'HOH_1591(A),', 'HOH_1634(A),', 'HOH_1671(A);'],
 ['ASP_399(A)',
  'HOH_1597(A),',
  'HOH_1668(A),',
  'HOH_1669(A),',
  'HOH_1670(A);'],
 ['ASP_296(B)',
  'HOH_1282(B),',
  'HOH_1642(B),',
  'HOH_1676(B),',
  'HOH_1709(B),',
  'HOH_1723(B);'],
 ['HIS_154(B)',
  'HOH_1221(B),',
  'HOH_1506(B),',
  'HOH_1520(B),',
  'HOH_1537(B),',
  'HOH_1677(B);'],
 ['GLY_71(A);'],
 ['ASN_119(A);'],
 ['HIS_67(A),', 'HIS_83(A),', 'HIS_87(A)', 'IMD_212(A),', 'IMD_213(A);'],
 ['HIS_198(A),', 'HIS_200(A);'],
 ['HIS_35(B)',
  'HOH_2048(B),',
  'HOH_2260(B),',
  'HOH_2324(A),',
  'HOH_2325(A);HIS_35(A)',
  'HOH_2049(A),',
  'HOH_2050(A),',
  'HOH_2290(A),',
  'HOH_2324(A),',
  'HOH_2325(A);'],
 ['HIS_8(E),', 'GLU_59(E),', 'HIS_77(F),', 'GLU_120(F)', 'HOH_2061(E);'],
 ['HIS_8(B),', 'GLU_59(B),', 'HIS_77(A),', 'GLU_120(A)', 'HOH_2130(A);'],
 ['HIS_17(A),', 'HIS_19(A);'],
 ['HIS_104(A);'],
 ['HIS_88(A),',
  'HIS_90(A),',
  'GLU_97(A),',
  'HIS_136(A)',
  'PA5_300(A),',
  'HOH_343(A);'],
 ['MET_1(C),', 'VAL_96(C),', 'ASP_110(C)', 'HOH_190(C),', 'HOH_191(C);'],
 ['ASP_491(A),', 'ASP_493(A),', 'HIS_577(A)', 'HOH_39(A);'],
 ['HIS_116(C);'],
 ['CYS_6(A),', 'CYS_9(A),', 'CYS_39(A),', 'CYS_42(A);'],
 ['HIS_321(A),', 'LYS_325(A)', 'HOH_26(A),', 'HOH_88(A);'],
 ['HIS_38(Z);HIS_38(Z);'],
 ['HIS_671(P),', 'ASP_672(P);'],
 ['HIS_61(B),', 'GLU_242(A);GLU_242(A),', 'ASP_243(A)', 'HOH_365(A);'],
 ['HIS_63(A)', 'HQI_151(A);'],
 ['HIS_88(A),', 'HIS_90(A),', 'GLU_94(A),', 'HIS_133(A)', 'UNL_201(A);'],
 ['ASP_73(A)', 'HOH_2037(A);'],
 ['GLU_247(A),', 'ASP_284(A);'],
 ['ASP_105(A);'],
 ['HIS_365(A),', 'ASP_369(A)', 'HOH_2177(A),', 'HOH_2205(A);'],
 ['HIS_291(A)', 'HOH_2168(A),', 'HOH_2189(A),', 'HOH_2190(A);'],
 ['ASP_1(L);'],
 ['HIS_10(B)', 'HOH_35(B),', 'HOH_85(B);'],
 ['HIS_101(A);'],
 ['HIS_28(A);HIS_23(A),', 'HIS_28(A),', 'GLU_144(A)', 'HOH_416(A);'],
 ['HIS_3(A);'],
 ['HIS_371(B)',
  'HOH_9141(B),',
  'HOH_9151(B),',
  'HOH_9173(B),',
  'HOH_9340(B),',
  'HOH_9356(B);'],
 ['HIS_70(A),', 'HIS_72(A),', 'HIS_126(A)', 'EDO_151(A),', 'MLI_153(A);'],
 ['HIS_179(B);'],
 ['HIS_210(A)', 'HOH_2003(A),', 'HOH_2127(A);'],
 ['HIS_-14(B),', 'HIS_-11(B);'],
 ['ASP_216(B);'],
 ['HIS_-12(B),', 'HIS_-10(B),', 'HIS_0(B),', 'ASP_84(B);'],
 ['HIS_-15(B),', 'HIS_-13(B);'],
 ['SER_-17(B);'],
 ['HIS_90(B),', 'HIS_91(B)', 'HOH_463(B),', 'HOH_485(B),', 'HOH_524(B);'],
 ['HIS_170(A),',
  'HIS_172(A),',
  'GLU_185(A),',
  'HIS_228(A)',
  'HOH_296(A),',
  'HOH_297(A);'],
 ['HIS_47(A),', 'GLU_53(A),', 'HIS_91(A)', 'HOH_289(A),', 'HOH_290(A);'],
 ['HIS_149(A),', 'HIS_160(A),', 'HIS_162(A)', 'CIT_300(A);'],
 ['CYS_111(A);'],
 ['CYS_89(B);'],
 ['HIS_88(B);'],
 ['HIS_18(A),', 'HIS_20(A);'],
 ['HIS_12(A),', 'HIS_14(A);'],
 ['CYS_509(A)',
  'SF4_733(A);CYS_531(A)',
  'SF4_733(A);CYS_512(A)',
  'SF4_733(A);CYS_521(A)',
  'SF4_733(A);CYS_598(A),',
  'GLY_599(A),',
  'CYS_600(A);'],
 ['GLU_44(A),', 'GLU_113(A)', 'NOS_804(A);'],
 ['HIS_9(A)', 'HOH_226(A),', 'HOH_227(A);'],
 ['GLU_64(B)', 'HOH_636(B);'],
 ['GLU_64(A),', 'HIS_269(B),', 'LYS_272(B)', 'HOH_628(A),', 'HOH_629(A);'],
 ['HIS_32(A),', 'HIS_34(A),', 'HIS_76(A)', 'FMT_100(A),', 'HOH_116(A);'],
 ['HIS_61(B)', 'HOH_1009(B),', 'HOH_1019(B),', 'HOH_1030(B);'],
 ['LYS_1106(A),', 'HIS_1277(A)', 'HOH_2019(A),', 'CL_2304(A);'],
 ['HOH_2003(A),', 'HOH_2004(A);'],
 ['HOH_2002(A),', 'HOH_2005(A);'],
 ['HIS_257(X)', 'HOH_5(X),', 'HOH_27(X),', 'HOH_39(X);'],
 ['GLY_1(B),', 'HIS_2(B),', 'HIS_450(A)', 'HOH_2001(B);'],
 ['HIS_80(A)',
  'HOH_294(A),',
  'HOH_295(A),',
  'HOH_296(A),',
  'HOH_297(A),',
  'HOH_298(A);'],
 ['HIS_67(C),',
  'HIS_160(C),',
  'HIS_164(C)',
  'HOH_302(C),',
  'HOH_303(C),',
  'HOH_346(C);'],
 ['GLU_52(C);'],
 ['GLU_52(A)', 'HOH_2135(A),', 'HOH_2142(A);'],
 ['HIS_40(A),',
  'HIS_164(A),',
  'GLU_234(A)',
  'HOH_306(A),',
  'HOH_310(A),',
  'HOH_327(A);'],
 ['HIS_94(A),',
  'HIS_96(A),',
  'HIS_119(A)',
  'HOH_263(A),',
  'HOH_338(A),',
  'SO4_500(A);'],
 ['ASP_178(A),', 'HIS_496(A),', 'HIS_498(A)', 'HOH_658(A);'],
 ['HOH_483(A),', 'HOH_528(A),', 'HOH_560(A),', 'HOH_654(A),', 'HOH_710(A);'],
 ['GLU_348(A)', 'HOH_644(A),', 'HOH_686(A),', 'HOH_801(A);'],
 ['ASN_259(B),',
  'HIS_297(B),',
  'HIS_320(B)',
  'HOH_646(B);ASP_208(B),',
  'HIS_210(B),',
  'ASP_236(B),',
  'HIS_322(B)',
  'HOH_646(B);'],
 ['MET_10(A),', 'ASP_102(A),', 'GLU_105(A),', 'HIS_106(A)', 'HOH_616(A);'],
 ['HIS_79(A),',
  'GLU_83(A),',
  'HIS_98(A)',
  'PO4_600(A),',
  'HOH_629(A),',
  'HOH_642(A);'],
 ['HIS_186(A),', 'GLU_188(A),', 'HIS_270(A)', 'HOH_524(A),', 'HOH_529(A);'],
 ['HIS_0(A),', 'ASP_2(A);'],
 ['HIS_167(A),', 'HIS_267(A)', 'HOH_345(A),', 'HOH_463(A),', 'HOH_467(A);'],
 ['ASP_141(A)', 'HOH_2013(A);'],
 ['HIS_5(D);'],
 ['HIS_122(A)', 'HOH_196(A),', 'HOH_197(A),', 'HOH_198(A),', 'HOH_199(A);'],
 ['THR_2(A),', 'GLN_3(A),', 'HIS_4(A);'],
 ['HIS_120(B)', 'HOH_696(B),', 'HOH_697(B),', 'HOH_698(B);'],
 ['GLU_27(A),', 'GLU_30(A);'],
 ['CYS_549(L)',
  'CSO_84(L),',
  'NFC_1004(L);CYS_81(L),',
  'CYS_549(L)',
  'CSO_84(L),',
  'CSO_546(L),',
  'NFC_1004(L);'],
 ['HIS_79(A);'],
 ['HIS_-9(D),',
  'HIS_48(A),',
  'HIS_142(A),',
  'HIS_146(A)',
  'IMD_301(A),',
  'HOH_421(A);'],
 ['HIS_-9(A),',
  'HIS_48(D),',
  'HIS_142(D),',
  'HIS_146(D)',
  'IMD_301(C),',
  'HOH_382(C);'],
 ['HIS_235(A)', 'HOH_361(A),', 'HOH_362(A),', 'GOL_363(A);'],
 ['HIS_530(D),', 'ASP_573(D);'],
 ['HIS_17(B),', 'HIS_99(A)', 'HOH_184(A),', 'HOH_208(B),', 'HOH_222(B);'],
 ['HIS_17(A),', 'HIS_99(B)', 'HOH_186(A),', 'HOH_189(A),', 'HOH_210(B);'],
 ['HIS_138(A)', 'HOH_342(B),', 'HOH_378(A),', 'HOH_379(A);'],
 ['HOH_2219(B),', 'HOH_2221(B),', 'HOH_2222(B);'],
 ['GLU_217(A),', 'HIS_220(A),', 'ASP_255(A),', 'ASP_257(A)', 'HOH_1073(A);'],
 ['GLY_113(A),', 'SER_114(A),', 'HIS_115(A);'],
 ['GLU_292(A);'],
 ['HIS_86(A),', 'HIS_143(B),', 'HIS_151(B)', 'HOH_253(B);'],
 ['HOH_116(B),', 'PXX_151(B);'],
 ['HIS_261(A),',
  'CYS_295(A)',
  'NFS_639(A);CYS_526(A)',
  'NFS_639(A),',
  'HOH_1436(A);CYS_333(A)',
  'NFS_639(A);CYS_446(A)',
  'NFS_639(A);'],
 ['CYS_476(A)',
  'NFS_639(A);CYS_526(A)',
  'NFS_639(A),',
  'HOH_1440(A);CYS_333(A)',
  'NFS_639(A);CYS_446(A)',
  'NFS_639(A)'],
 ['GLU_49(B),',
  'ASP_53(B),',
  'GLU_91(B),',
  'ASP_95(B)',
  'PO3_569(B),',
  'HOH_615(B);GLU_91(B),',
  'ASN_92(B),',
  'ASP_95(B)',
  'PO3_569(B),',
  'HOH_589(B),',
  'HOH_628(B);GLU_56(B),',
  'GLU_88(B),',
  'GLU_91(B)',
  'HOH_579(B),',
  'HOH_589(B);GLU_49(B),',
  'GLU_50(B),',
  'ASP_53(B)',
  'HOH_592(B),',
  'HOH_611(B)'],
 ['HIS_79(D);'],
 ['HIS_46(H);'],
 ['ASP_90(C);'],
 ['GLU_102(H),', 'HIS_106(H);'],
 ['ASP_77(E);'],
 ['ASP_24(F);'],
 ['HIS_98(A),', 'HIS_100(A);'],
 ['HIS_97(A);'],
 ['ASP_66(A)',
  'HOH_305(A),',
  'HOH_312(A),',
  'HOH_331(A),',
  'HOH_343(A),',
  'HOH_355(A);'],
 ['GLY_-1(B),', 'HIS_0(B)', 'HOH_329(B),', 'HOH_343(B);'],
 ['GLY_-1(C),', 'HIS_0(C)', 'HOH_308(C);'],
 ['GLU_8(A),',
  'ASP_10(A),',
  'ASP_19(A),',
  'HIS_24(A)',
  'HOH_1006(A),',
  'HOH_1051(A);ASP_10(A),',
  'TYR_12(A),',
  'ASN_14(A),',
  'ASP_19(A)',
  'HOH_1255(A),',
  'HOH_1276(A);'],
 ['SER_134(A)', 'HOH_1032(A),', 'HOH_1046(A),', 'HOH_1066(A);'],
 ['ARG_297(B),', 'HIS_330(B);'],
 ['GLU_136(A),',
  'GLU_253(A)',
  'HOH_596(A),',
  'HOH_606(A),',
  'HOH_776(A),',
  'HOH_1027(A);HIS_205(A);'],
 ['GLU_127(H)', 'HOH_1264(H),', 'HOH_1265(H);'],
 ['GLU_78(D),', 'GLU_144(E)', 'HOH_436(D),', 'HOH_659(D);'],
 ['HIS_1(K),', 'CYS_2(K),', 'CYS_6(K);'],
 ['ASP_226(A),', 'ASP_227(G),', 'HIS_230(A)', 'HOH_668(G),', 'HOH_774(A);'],
 ['ASP_226(G),', 'ASP_227(A),', 'HIS_230(G)', 'HOH_830(G);'],
 ['GLU_202(B)', 'HOH_595(B),', 'HOH_1288(B);'],
 ['MET_69(H)', 'HOH_608(H),', 'HOH_1190(H);'],
 ['GLU_180(B)', 'HOH_1263(B);'],
 ['ASP_305(A);'],
 ['HOH_1237(B);'],
 ['ASP_226(F),', 'HIS_230(F);'],
 ['GLU_78(E)', 'HOH_1331(E);'],
 ['GLU_26(B),', 'GLU_29(B);'],
 ['HIS_-4(A),', 'HIS_-2(A);'],
 ['HOH_2001(A);'],
 ['HIS_-1(A),', 'HIS_1(A);'],
 ['HOH_2039(A),', 'HOH_2129(A);'],
 ['HIS_363(B),', 'GLN_389(B),', 'GLU_419(B);'],
 ['HIS_302(B),', 'GLU_303(B);'],
 ['ARG_262(B);'],
 ['HIS_97(B)', 'HOH_2025(A),', 'HOH_2086(A),', 'HOH_2157(B);'],
 ['ASP_83(B);'],
 ['ASP_376(B),', 'GLY_401(B),', 'HIS_435(B)', 'HOH_2218(B),', 'HOH_2219(B);'],
 ['HOH_2029(E);'],
 ['MET_54(F),', 'HIS_55(F);'],
 ['GLY_-2(C),', 'SER_-1(C),', 'HIS_0(C);'],
 ['BTN_300(A),', 'SO4_302(A);'],
 ['HIS_2114(B),', 'HIS_2118(B),', 'HIS_2124(B);'],
 ['GLY_288(A),', 'SER_289(A),', 'HIS_290(A);'],
 ['ASP_194(A),', 'HIS_198(A),', 'HIS_258(A),', 'HIS_272(A)', 'UNL_728(A);'],
 ['HIS_97(A)', 'HOH_485(A),', 'HOH_549(A),', 'HOH_555(A),', 'HOH_617(A);'],
 ['HIS_471(A),', 'HIS_472(A);'],
 ['HIS_106(A)', 'HOH_242(A),', 'HOH_253(D),', 'HOH_281(D);'],
 ['HIS_76(A),', 'HIS_78(A),', 'HIS_219(A);'],
 ['HIS_33(C),', 'HIS_67(C),', 'ASP_68(C),', 'ASP_124(C);'],
 ['CGU_119(B),',
  'CGU_123(B),',
  'CL_411(B),',
  'HOH_412(B);CL_421(B),',
  'CL_422(B);CL_431(B),',
  'CL_432(B);'],
 ['HIS_7(A),', 'GLU_25(A),', 'HIS_29(A);'],
 ['HIS_199(C);'],
 ['GLY_125(B),', 'HIS_199(A)', 'HOH_4(B),', 'HOH_5(B),', 'HOH_6(B);'],
 ['ASP_175(A)', 'HOH_222(A),', 'HOH_224(A),', 'HOH_260(A);'],
 ['HIS_202(A),', 'ASP_204(A),', 'HIS_347(A)', 'OGA_390(A),', 'HOH_800(A);'],
 ['GLU_494(B),', 'ASP_495(B);HIS_313(A),', 'GLU_494(B)', 'HOH_2009(A);'],
 ['HIS_439(A)', 'HOH_2069(A);'],
 ['CYS_2(A),', 'GLY_3(A),', 'CYS_4(A);SER_1(A),', 'CYS_2(A)', 'HOH_139(A);'],
 ['HIS_45(A),', 'LYS_49(A),', 'HIS_231(B)', 'HOH_2003(B);'],
 ['HIS_17(B),', 'HIS_18(B)', 'HOH_2002(B);'],
 ['HIS_45(B),', 'LYS_49(B),', 'HIS_231(A)', 'HOH_2004(A);'],
 ['HIS_-22(B),', 'HIS_-20(B),', 'HIS_134(B)', 'IMD_253(B);'],
 ['GLU_494(B),', 'ASP_495(B)', 'HOH_2012(A);'],
 ['HIS_280(A),', 'ASP_483(B)', 'HOH_2013(A),', 'HOH_2057(B);'],
 ['HIS_525(A);'],
 ['HIS_498(B)', 'HOH_2064(B);'],
 ['GLU_261(A),',
  'ASP_344(A),',
  'ASP_465(A)',
  'HOH_2044(A),',
  'HOH_2091(A);GLU_261(A),',
  'ASP_344(A),',
  'ASP_351(A),',
  'CYS_462(A),',
  'ASP_465(A)',
  'HOH_2089(A);'],
 ['HIS_428(B)', 'HOH_2036(B);'],
 ['GLU_315(A),', 'GLU_320(A)', 'HOH_2027(A);GLU_320(A);'],
 ['HIS_313(B),', 'GLU_494(A)', 'HOH_2003(B),', 'HOH_2007(B),', 'HOH_2106(A);'],
 ['HIS_459(B);'],
 ['HIS_313(A)', 'HOH_2006(A),', 'HOH_2009(A),', 'HOH_2024(A);'],
 ['HIS_151(C),', 'GLU_171(C),', 'HIS_175(C)', 'HOH_328(C);'],
 ['HIS_201(A),', 'HIS_206(A),', 'ASP_356(A)', 'TRS_504(A);'],
 ['HIS_16(A)', 'TRS_505(A),', 'HOH_589(A),', 'HOH_663(A);'],
 ['HIS_344(A)', 'HOH_638(A),', 'HOH_697(B),', 'HOH_718(A),', 'HOH_749(B);'],
 ['HIS_40(A),', 'HIS_216(C),', 'GLU_222(C)', 'HOH_395(A),', 'HOH_397(C);'],
 ['HIS_40(C),', 'GLU_222(A)', 'HOH_394(A),', 'HOH_396(A);'],
 ['HIS_40(C),', 'HIS_216(A),', 'GLU_222(A)', 'HOH_398(C),', 'HOH_414(A);'],
 ['ASP_66(A);'],
 ['HIS_199(A),', 'GLU_245(B),', 'ASP_292(B),', 'ASP_294(B);'],
 ['HIS_24(A),',
  'HIS_69(A),',
  'ASP_70(A),',
  'ASP_205(A)',
  'HOH_262(A),',
  'HOH_344(A);'],

In [56]:
very_new_list = []
for i in ligand_list:
    new_list = []
    for j in i:
        new_list.extend(re.findall(r'([A-Z]+)\_.*', j))
    very_new_list.append(new_list)
very_new_list

[['ASP', 'HIS', 'HIS', 'ASP', 'HOH'],
 ['HIS', 'HOH'],
 ['HIS', 'ASP'],
 ['HIS', 'HIS', 'HOH', 'HOH'],
 ['HOH', 'HOH'],
 ['HIS', 'HOH', 'HOH', 'HOH', 'HOH', 'HOH'],
 ['HIS'],
 ['HIS'],
 ['ASN', 'HIS', 'GLU', 'FMN', 'HOH', 'HOH'],
 ['HIS', 'HOH'],
 ['HIS', 'GDP', 'HOH', 'HOH', 'HOH', 'HOH'],
 ['HIS', 'HOH', 'HOH', 'HOH'],
 ['HIS', 'TRS', 'TRS'],
 ['HIS', 'HOH'],
 ['HIS', 'GLU', 'HIS', 'GLU', 'HOH', 'HOH'],
 ['HIS', 'GLU', 'HIS', 'GLU', 'HOH', 'HOH'],
 ['HIS', 'HIS', 'KCX', 'HOH', 'HOH', 'HOH'],
 ['HIS', 'HOH', 'HOH', 'HOH'],
 ['ALA', 'HOH'],
 ['TRP', 'HOH', 'HOH', 'HOH', 'HOH'],
 ['ASP', 'ASP', 'HIS', 'HOH'],
 ['HIS', 'HIS'],
 ['HIS', 'HOH'],
 ['HIS', 'HOH'],
 ['GLN', 'COM'],
 ['ASP'],
 ['HIS', 'HOH', 'HOH', 'HOH', 'HOH'],
 ['HIS', 'HOH', 'HOH', 'HOH'],
 ['HIS'],
 ['HIS'],
 ['GLY', 'HOH', 'HOH', 'HOH'],
 ['ALA', 'HIS', 'ASP', 'HOH'],
 ['HIS', 'HIS', 'HIS', 'TYR', 'HOH', 'HOH'],
 ['HIS', 'HOH', 'HOH'],
 ['ALA', 'ASP', 'HIS'],
 ['HIS', 'HIS', 'HIS', 'HOH', 'HOH', 'HOH'],
 ['HIS', 'HIS'],
 ['HIS', 'CL', 'HOH', 'CL', 'HOH'],
 ['HIS', 'HIS', 'HOH', 'HOH'],
 ['ASP'],
 ['ASP', 'ASP', 'ASP', 'HOH'],
 ['CYS', 'CYS', 'HIS', 'CL'],
 ['HIS', 'HNI'],
 ['LYS', 'HOH', 'HOH', 'HOH'],
 ['ASN', 'HOH', 'HOH', 'HOH', 'HOH'],
 ['HIS', 'GLU', 'HIS', 'HIS', 'HOH'],
 ['ALA', 'ARG'],
 ['HIS', 'HOH', 'HOH', 'HOH', 'HOH'],
 ['HIS', 'HOH', 'HOH', 'HOH', 'HOH'],
 ['HIS'],
 ['HIS', 'HOH', 'HOH', 'HOH'],
 ['ARG', 'HIS', 'GLU', 'CL'],
 ['LYS', 'HOH'],
 ['HIS', 'HIS', 'HOH', 'HOH', 'HOH', 'HOH'],
 ['HIS', 'GLU', 'HOH', 'HOH', 'HOH'],
 ['HIS'],
 ['HIS', 'HIS', 'HIS', 'ASP', 'HOH', 'HOH'],
 ['HIS', 'HIS', 'HIS', 'HOH', 'HOH', 'HOH'],
 ['CYS', 'HIS', 'HIS', 'HOH'],
 ['HIS', 'HIS'],
 ['ASP', 'ASP', 'GLU', 'ASP', 'HIS', 'GLU', 'GLU', 'HIS', 'CL', 'HOH'],
 ['TCN'],
 ['HIS', 'HOH'],
 ['HIS', 'HIS', 'TRS', 'HOH'],
 ['HIS'],
 ['ASP', 'HIS', 'HOH'],
 ['HIS', 'GLU', 'HOH'],
 ['HIS', 'ASP', 'HOH'],
 ['HIS', 'HOH'],
 ['HIS'],
 ['HIS', 'HIS', 'GLU', 'HIS', 'UNL'],
 ['HIS', 'ASP'],
 ['HIS', 'ASP', 'HIS', 'HOH', 'HOH', 'HOH'],
 ['HIS'],
 ['HIS', 'HIS'],
 ['HIS', 'HIS'],
 ['HIS', 'GLU', 'HOH'],
 ['HIS', 'ASP', 'GLU', 'HOH', 'HOH'],
 ['HIS', 'ASP', 'GLU', 'HOH', 'HOH'],
 ['HIS', 'HIS', 'HIS', 'CYS'],
 ['HIS', 'HIS', 'HIS', 'CYS'],
 ['HIS', 'HIS'],
 ['ALA', 'ASP'],
 ['HIS', 'HIS'],
 ['GLU', 'HOH', 'HOH', 'HOH'],
 ['HOH', 'HOH', 'HOH', 'HOH'],
 ['HIS', 'GLU', 'HOH', 'HOH', 'HOH', 'HOH'],
 ['ALA', 'HOH', 'HOH', 'HOH'],
 ['HIS', 'HIS', 'HIS'],
 ['HIS', 'ASP', 'HIS', 'HOH', 'HOH', 'HOH'],
 ['HIS', 'HOH', 'HOH', 'HOH', 'HOH', 'HOH', 'HOH'],
 ['HIS', 'HOH', 'HOH', 'HOH'],
 ['HIS', 'CL', 'CL'],
 ['HIS', 'HOH', 'HOH', 'HOH', 'HOH'],
 ['ASP', 'ASP', 'ASP', 'SEP', 'HOH'],
 ['HOH'],
 ['HIS', 'HOH', 'HOH', 'HOH'],
 ['HOH', 'HOH'],
 ['HIS', 'CL', 'HOH', 'HOH', 'HOH', 'HOH'],
 ['HIS', 'HOH', 'HOH', 'HOH', 'HOH'],
 ['HIS', 'CL', 'CL', 'CL', 'CL', 'CL'],
 ['ASP'],
 ['GLU', 'ASP'],
 ['GLU', 'ASP', 'LEU', 'VAL'],
 ['SER', 'SER', 'THR', 'ASN', 'HOH', 'HOH'],
 ['HIS', 'HIS', 'GLU', 'ASP', 'HIS', 'HIS'],
 ['HOH', 'HOH', 'HOH'],
 ['HIS', 'ASP', 'HIS', 'IMD', 'IMD'],
 ['GLU', 'HOH', 'HOH', 'HOH'],
 ['HIS', 'HOH', 'HOH', 'HOH'],
 ['HIS', 'ACO', 'ACO'],
 ['GLU', 'GLU', 'HOH'],
 ['GLU', 'GLU', 'HOH', 'HOH'],
 ['HIS', 'GLU', 'HIS'],
 ['GLU', 'HOH'],
 ['ASP', 'VAL', 'ASP', 'PRO', 'GLU', 'HOH'],
 ['ASP', 'GLU', 'ALA', 'ASN', 'HOH'],
 ['HIS', 'LYS', 'HOH', 'HOH', 'HOH'],
 ['GLU', 'HIS', 'ASP', 'GLO', 'HOH', 'GLU', 'ASP', 'ASP', 'GLO'],
 ['GLU', 'HIS', 'CL'],
 ['GLU', 'HIS', 'ASP', 'ASP', 'HOH', 'GLU', 'ASP', 'ASP'],
 ['HIS', 'HIS', 'GLU', 'HIS', 'MET'],
 ['HIS', 'GLU', 'GLU', 'HOH', 'HOH', 'HOH'],
 ['HIS', 'HOH'],
 ['EDO', 'HOH', 'HOH'],
 ['ASP', 'ASP', 'HOH'],
 ['HIS', 'HIS', 'HOH', 'HOH'],
 ['HIS', 'HOH', 'HOH', 'HOH', 'HOH'],
 ['ALA', 'HOH'],
 ['GLY', 'SER', 'HIS'],
 ['GLY', 'SER', 'HIS'],
 [],
 ['ASP', 'HOH', 'HOH', 'HOH', 'HOH'],
 ['ASP', 'HOH'],
 [],
 ['HOH'],
 ['ASP', 'HIS', 'GLU', 'GLU', 'ASP', 'ASP', 'GLU'],
 ['HIS', 'ASP', 'HOH', 'HOH'],
 ['ASP', 'ASP', 'HOH', 'HOH', 'HOH'],
 ['HIS', 'LYS', 'HOH', 'HOH', 'HOH', 'HOH'],
 ['HIS', 'HOH', 'HOH', 'HOH', 'HOH', 'HOH'],
 ['TRP', 'TRS'],
 ['TRP', 'PHE', 'TRS'],
 ['TRP', 'PHE', 'TRS', 'HOH'],
 ['ASP', 'LYS', 'HIS', 'HOH', 'HOH', 'HOH'],
 ['HOH', 'HOH'],
 ['HOH'],
 ['HIS', 'HIS', 'HIS', 'CYS', 'SER', 'HIS'],
 ['HIS'],
 ['ASP', 'HIS', 'HOH', 'HOH', 'HOH', 'HOH'],
 ['HIS', 'HOH', 'HOH', 'HOH', 'HOH'],
 ['ASP', 'HOH', 'HOH', 'HOH', 'HOH'],
 ['ASP', 'HOH', 'HOH', 'HOH', 'HOH', 'HOH'],
 ['HIS', 'HOH', 'HOH', 'HOH', 'HOH', 'HOH'],
 ['GLY'],
 ['ASN'],
 ['HIS', 'HIS', 'HIS', 'IMD', 'IMD'],
 ['HIS', 'HIS'],
 ['HIS', 'HOH', 'HOH', 'HOH', 'HOH', 'HOH', 'HOH', 'HOH', 'HOH', 'HOH'],
 ['HIS', 'GLU', 'HIS', 'GLU', 'HOH'],
 ['HIS', 'GLU', 'HIS', 'GLU', 'HOH'],
 ['HIS', 'HIS'],
 ['HIS'],
 ['HIS', 'HIS', 'GLU', 'HIS', 'HOH'],
 ['MET', 'VAL', 'ASP', 'HOH', 'HOH'],
 ['ASP', 'ASP', 'HIS', 'HOH'],
 ['HIS'],
 ['CYS', 'CYS', 'CYS', 'CYS'],
 ['HIS', 'LYS', 'HOH', 'HOH'],
 ['HIS'],
 ['HIS', 'ASP'],
 ['HIS', 'GLU', 'ASP', 'HOH'],
 ['HIS', 'HQI'],
 ['HIS', 'HIS', 'GLU', 'HIS', 'UNL'],
 ['ASP', 'HOH'],
 ['GLU', 'ASP'],
 ['ASP'],
 ['HIS', 'ASP', 'HOH', 'HOH'],
 ['HIS', 'HOH', 'HOH', 'HOH'],
 ['ASP'],
 ['HIS', 'HOH', 'HOH'],
 ['HIS'],
 ['HIS', 'HIS', 'GLU', 'HOH'],
 ['HIS'],
 ['HIS', 'HOH', 'HOH', 'HOH', 'HOH', 'HOH'],
 ['HIS', 'HIS', 'HIS', 'EDO', 'MLI'],
 ['HIS'],
 ['HIS', 'HOH', 'HOH'],
 ['HIS', 'HIS'],
 ['ASP'],
 ['HIS', 'HIS', 'HIS', 'ASP'],
 ['HIS', 'HIS'],
 ['SER'],
 ['HIS', 'HIS', 'HOH', 'HOH', 'HOH'],
 ['HIS', 'HIS', 'GLU', 'HIS', 'HOH', 'HOH'],
 ['HIS', 'GLU', 'HIS', 'HOH', 'HOH'],
 ['HIS', 'HIS', 'HIS', 'CIT'],
 ['CYS'],
 ['CYS'],
 ['HIS'],
 ['HIS', 'HIS'],
 ['HIS', 'HIS'],
 ['CYS', 'CYS', 'CYS', 'CYS', 'CYS', 'GLY', 'CYS'],
 ['GLU', 'GLU', 'NOS'],
 ['HIS', 'HOH', 'HOH'],
 ['GLU', 'HOH'],
 ['GLU', 'HIS', 'LYS', 'HOH', 'HOH'],
 ['HIS', 'HIS', 'HIS', 'FMT', 'HOH'],
 ['HIS', 'HOH', 'HOH', 'HOH'],
 ['LYS', 'HIS', 'HOH', 'CL'],
 ['HOH', 'HOH'],
 ['HOH', 'HOH'],
 ['HIS', 'HOH', 'HOH', 'HOH'],
 ['GLY', 'HIS', 'HIS', 'HOH'],
 ['HIS', 'HOH', 'HOH', 'HOH', 'HOH', 'HOH'],
 ['HIS', 'HIS', 'HIS', 'HOH', 'HOH', 'HOH'],
 ['GLU'],
 ['GLU', 'HOH', 'HOH'],
 ['HIS', 'HIS', 'GLU', 'HOH', 'HOH', 'HOH'],
 ['HIS', 'HIS', 'HIS', 'HOH', 'HOH'],
 ['ASP', 'HIS', 'HIS', 'HOH'],
 ['HOH', 'HOH', 'HOH', 'HOH', 'HOH'],
 ['GLU', 'HOH', 'HOH', 'HOH'],
 ['ASN', 'HIS', 'HIS', 'HOH', 'HIS', 'ASP', 'HIS', 'HOH'],
 ['MET', 'ASP', 'GLU', 'HIS', 'HOH'],
 ['HIS', 'GLU', 'HIS', 'HOH', 'HOH'],
 ['HIS', 'GLU', 'HIS', 'HOH', 'HOH'],
 ['HIS', 'ASP'],
 ['HIS', 'HIS', 'HOH', 'HOH', 'HOH'],
 ['ASP', 'HOH'],
 ['HIS'],
 ['HIS', 'HOH', 'HOH', 'HOH', 'HOH'],
 ['THR', 'GLN', 'HIS'],
 ['HIS', 'HOH', 'HOH', 'HOH'],
 ['GLU', 'GLU'],
 ['CYS', 'CSO', 'NFC', 'CYS', 'CSO', 'CSO', 'NFC'],
 ['HIS'],
 ['HIS', 'HIS', 'HIS', 'HIS', 'IMD', 'HOH'],
 ['HIS', 'HIS', 'HIS', 'HIS', 'IMD', 'HOH'],
 ['HIS', 'HOH', 'HOH', 'GOL'],
 ['HIS', 'ASP'],
 ['HIS', 'HIS', 'HOH', 'HOH', 'HOH'],
 ['HIS', 'HIS', 'HOH', 'HOH', 'HOH'],
 ['HIS', 'HOH', 'HOH', 'HOH'],
 ['HOH', 'HOH', 'HOH'],
 ['GLU', 'HIS', 'ASP', 'ASP', 'HOH'],
 ['GLY', 'SER', 'HIS'],
 ['GLU'],
 ['HIS', 'HIS', 'HIS', 'HOH'],
 ['HOH', 'PXX'],
 ['HIS', 'CYS', 'NFS', 'NFS', 'HOH', 'NFS', 'NFS'],
 ['CYS', 'NFS', 'NFS', 'HOH', 'NFS', 'NFS'],
 ['GLU',
  'ASP',
  'GLU',
  'ASP',
  'HOH',
  'ASN',
  'ASP',
  'HOH',
  'HOH',
  'GLU',
  'GLU',
  'HOH',
  'HOH',
  'GLU',
  'ASP',
  'HOH',
  'HOH'],
 ['HIS'],
 ['HIS'],
 ['ASP'],
 ['GLU', 'HIS'],
 ['ASP'],
 ['ASP'],
 ['HIS', 'HIS'],
 ['HIS'],
 ['ASP', 'HOH', 'HOH', 'HOH', 'HOH', 'HOH'],
 ['GLY', 'HIS', 'HOH', 'HOH'],
 ['GLY', 'HIS', 'HOH'],
 ['GLU', 'ASP', 'ASP', 'HIS', 'HOH', 'HOH', 'TYR', 'ASN', 'ASP', 'HOH', 'HOH'],
 ['SER', 'HOH', 'HOH', 'HOH'],
 ['ARG', 'HIS'],
 ['GLU', 'GLU', 'HOH', 'HOH', 'HOH', 'HOH'],
 ['GLU', 'HOH', 'HOH'],
 ['GLU', 'GLU', 'HOH', 'HOH'],
 ['HIS', 'CYS', 'CYS'],
 ['ASP', 'ASP', 'HIS', 'HOH', 'HOH'],
 ['ASP', 'ASP', 'HIS', 'HOH'],
 ['GLU', 'HOH', 'HOH'],
 ['MET', 'HOH', 'HOH'],
 ['GLU', 'HOH'],
 ['ASP'],
 ['HOH'],
 ['ASP', 'HIS'],
 ['GLU', 'HOH'],
 ['GLU', 'GLU'],
 ['HIS', 'HIS'],
 ['HOH'],
 ['HIS', 'HIS'],
 ['HOH', 'HOH'],
 ['HIS', 'GLN', 'GLU'],
 ['HIS', 'GLU'],
 ['ARG'],
 ['HIS', 'HOH', 'HOH', 'HOH'],
 ['ASP'],
 ['ASP', 'GLY', 'HIS', 'HOH', 'HOH'],
 ['HOH'],
 ['MET', 'HIS'],
 ['GLY', 'SER', 'HIS'],
 ['BTN'],
 ['HIS', 'HIS', 'HIS'],
 ['GLY', 'SER', 'HIS'],
 ['ASP', 'HIS', 'HIS', 'HIS', 'UNL'],
 ['HIS', 'HOH', 'HOH', 'HOH', 'HOH'],
 ['HIS', 'HIS'],
 ['HIS', 'HOH', 'HOH', 'HOH'],
 ['HIS', 'HIS', 'HIS'],
 ['HIS', 'HIS', 'ASP', 'ASP'],
 ['CGU', 'CGU', 'CL', 'HOH', 'CL', 'CL'],
 ['HIS', 'GLU', 'HIS'],
 ['HIS'],
 ['GLY', 'HIS', 'HOH', 'HOH', 'HOH'],
 ['ASP', 'HOH', 'HOH', 'HOH'],
 ['HIS', 'ASP', 'HIS', 'OGA', 'HOH'],
 ['GLU', 'ASP', 'GLU', 'HOH'],
 ['HIS', 'HOH'],
 ['CYS', 'GLY', 'CYS', 'CYS', 'HOH'],
 ['HIS', 'LYS', 'HIS', 'HOH'],
 ['HIS', 'HIS', 'HOH'],
 ['HIS', 'LYS', 'HIS', 'HOH'],
 ['HIS', 'HIS', 'HIS', 'IMD'],
 ['GLU', 'ASP', 'HOH'],
 ['HIS', 'ASP', 'HOH', 'HOH'],
 ['HIS'],
 ['HIS', 'HOH'],
 ['GLU', 'ASP', 'ASP', 'HOH', 'HOH', 'ASP', 'ASP', 'CYS', 'ASP', 'HOH'],
 ['HIS', 'HOH'],
 ['GLU', 'GLU', 'HOH'],
 ['HIS', 'GLU', 'HOH', 'HOH', 'HOH'],
 ['HIS'],
 ['HIS', 'HOH', 'HOH', 'HOH'],
 ['HIS', 'GLU', 'HIS', 'HOH'],
 ['HIS', 'HIS', 'ASP', 'TRS'],
 ['HIS', 'TRS', 'HOH', 'HOH'],
 ['HIS', 'HOH', 'HOH', 'HOH', 'HOH'],
 ['HIS', 'HIS', 'GLU', 'HOH', 'HOH'],
 ['HIS', 'GLU', 'HOH', 'HOH'],
 ['HIS', 'HIS', 'GLU', 'HOH', 'HOH'],
 ['ASP'],
 ['HIS', 'GLU', 'ASP', 'ASP'],
 ['HIS', 'HIS', 'ASP', 'ASP', 'HOH', 'HOH'],
 ['HIS', 'ASP', 'HIS', 'HOH', 'HOH'],
 ['COM'],
 ['HIS', 'HIS'],
 ['HIS'],
 ['VAL', 'ASP', 'HOH', 'HOH'],
 ['HIS'],
 ['HIS', 'HOH', 'HOH'],
 ['ASP', 'HOH', 'HOH', 'HOH', 'HOH'],
 ['HIS', 'HOH'],
 ['ASP', 'HIS'],
 ['GLU'],
 ['HIS'],
 ['ASP', 'GLN', 'HIS', 'HOH'],
 ['HOH', 'HOH', 'HOH', 'HOH', 'HOH'],
 ['HIS', 'HIS', 'TYR', 'HOH', 'HOH'],
 ['HIS', 'HOH'],
 ['HIS', 'HIS', 'HOH', 'HOH', 'HOH'],
 ['HIS'],
 ['HIS', 'IMD'],
 ['HIS'],
 ['HIS', 'GLU'],
 ['HIS', 'HIS', 'HOH', 'HOH'],
 ['HIS'],
 ['HIS'],
 ['HIS', 'HIS', 'HIS', 'HOH', 'HOH', 'HOH'],
 ['HIS', 'CYS'],
 ['GLU', 'HIS', 'HOH', 'HOH', 'HOH', 'HOH'],
 ['ASP', 'HIS', 'HOH'],
 ['LYS'],
 ['HIS', 'HOH'],
 ['HIS', 'HIS', 'CYS'],
 ['HIS', 'HOH'],
 ['HIS', 'HOH', 'HOH'],
 ['HIS', 'HIS'],
 ['HIS', 'CTC', 'HOH', 'HOH', 'HOH'],
 ['HIS', 'HIS', 'HOH', 'HOH', 'HOH', 'HOH'],
 ['CYS', 'HIS', 'IMD', 'IMD'],
 ['ASP', 'HIS', 'HIS'],
 ['HIS', 'HIS'],
 ['HIS'],
 ['HIS', 'HIS', 'HOH'],
 ['HIS', 'HIS'],
 ['HIS', 'HIS', 'CYS', 'HOH'],
 ['HIS', 'HIS'],
 ['HIS', 'HIS'],
 ['HIS', 'HOH'],
 ['GLU', 'HIS', 'HIS', 'HOH', 'HOH', 'HOH'],
 ['ASP', 'GLU', 'GLU', 'HOH', 'HOH', 'ASP', 'PHE', 'GLN', 'GLU'],
 ['HIS', 'HIS', 'ACT', 'HOH'],
 ['HIS', 'ASP'],
 ['ASP'],
 ['ASP', 'ASP'],
 ['ARG', 'HIS', 'ASP', 'HOH'],
 ['ASP', 'HOH', 'HOH', 'HOH', 'HOH', 'HOH'],
 ['HIS', 'COA'],
 ['HIS', 'HIS', 'HIS'],
 ['ASP', 'ASP', 'HOH'],
 ['HIS', 'HOH', 'HOH'],
 ['HIS', 'HOH', 'HOH'],
 ['ILE', 'HOH', 'HOH', 'HOH', 'HOH'],
 ['GLU'],
 ['HOH', 'HOH', 'HOH', 'HOH'],
 ['ASP', 'HIS', 'HOH', 'HOH', 'HOH'],
 ['HIS', 'HOH'],
 ['CYS', 'GLU', 'HOH', 'HOH'],
 ['CYS', 'HOH'],
 ['HOH', 'PXX'],
 ['HOH', 'PXX'],
 ['HIS', 'ASP', 'GLU', 'HOH', 'HOH', 'HOH'],
 ['HIS', 'HIS', 'HOH'],
 ['HIS', 'LYS', 'HOH', 'HOH', 'HOH'],
 ['HIS', 'LYS'],
 ['HIS', 'HOH', 'HOH', 'HOH', 'HOH'],
 ['HIS'],
 ['HIS'],
 ['HIS', 'HOH', 'HOH'],
 ['HIS', 'HOH', 'HOH', 'HOH'],
 ['ASN', 'GLN', 'HOH', 'HOH'],
 ['ASP', 'ASP', 'ASN', 'HOH'],
 ['HIS', 'HIS', 'HIS', 'UNL'],
 ['HIS', 'HIS', 'HIS', 'UNL'],
 ['HIS', 'HIS'],
 ['HIS', 'HOH'],
 ['MET', 'ASP', 'HOH', 'HOH', 'HOH'],
 ['HIS', 'HIS'],
 ['GLY', 'HIS', 'HOH', 'HOH'],
 ['HIS', 'GLU', 'HIS', 'GLU', 'HOH', 'HOH'],
 ['HIS'],
 ['HIS', 'HIS'],
 ['ASP', 'HOH', 'HOH', 'HOH'],
 ['GLY', 'HIS', 'CYS', 'HIS'],
 ['HIS', 'HIS', 'GLU', 'HOH', 'HOH', 'HOH'],
 ['ASN', 'HIS', 'HIS', 'HIS', 'HOH', 'HOH'],
 ['ASP', 'HIS', 'HIS', 'ASN', 'HOH', 'HOH'],
 ['CYS', 'CYS', 'CYS', 'CYS', 'CYS', 'GLY', 'CYS'],
 ['CYS', 'CYS', 'CYS', 'CYS', 'CYS', 'GLY', 'CYS'],
 ['HIS', 'GLU'],
 ['HIS', 'HIS', 'HOH', 'HOH'],
 ['HIS', 'HOH'],
 ['HIS', 'HIS', 'HIS', 'HOH'],
 ['HIS', 'GLU', 'HIS', 'HOH'],
 ['ASP', 'ASN', 'HIS', 'HOH', 'HOH'],
 ['HIS'],
 ['HIS'],
 ['HIS', 'HIS', 'ASP', 'HOH'],
 ['HIS', 'HOH', 'HOH', 'HOH', 'HOH'],
 ['HIS', 'HOH', 'HOH', 'HOH', 'HOH'],
 ['MET', 'HOH', 'HOH', 'HOH', 'HOH'],
 ['MET', 'HOH', 'HOH', 'HOH', 'HOH'],
 ['HIS', 'HOH', 'HOH'],
 ['SER', 'HIS'],
 ['HIS'],
 ['HIS', 'HIS', 'HOH', 'HOH', 'HOH', 'HOH'],
 ['HIS', 'GLU', 'HOH', 'HOH', 'HOH'],
 ['HIS', 'HOH', 'HOH'],
 ['HIS', 'ASP', 'HIS', 'HOH', 'AKG'],
 ['HIS', 'HIS', 'GLU', 'HOH'],
 ['HIS', 'ASP', 'HOH', 'HOH', 'HOH'],
 ['HIS', 'HOH', 'HOH', 'HOH', 'HOH'],
 ['HIS', 'ASP', 'HOH', 'HOH'],
 ['HIS'],
 ['HIS', 'HIS', 'HOH', 'HOH'],
 ['HIS', 'HIS', 'HOH', 'HOH', 'HOH', 'HOH'],
 ['MET', 'HOH', 'HOH', 'HOH'],
 ['CYS', 'CYS', 'CYS', 'CYS', 'CYS', 'GLY', 'CYS'],
 ['ASP'],
 ['ASP', 'HOH', 'HOH', 'HOH'],
 ['ASP', 'HOH'],
 ['ASN', 'ASN'],
 ['GLU'],
 ['HIS', 'HOH'],
 ['ASP'],
 ['HIS', 'HOH'],
 ['HIS'],
 ['HIS', 'HOH', 'HOH', 'HOH'],
 ['HIS', 'HOH'],
 ['GLU'],
 ['HIS', 'HIS', 'HIS'],
 ['ASP', 'HIS', 'ASP', 'HIS', 'HOH', 'HOH', 'HIS', 'HIS', 'ASP', 'HOH', 'HOH'],
 ['DG', 'HOH', 'HOH', 'HOH', 'HOH'],
 ['HIS', 'HIS', 'HIS', 'GLU', 'HOH', 'HOH'],
 ['HIS', 'HIS', 'HIS', 'HIS', 'HIS'],
 ['HIS', 'ASP'],
 ['HIS'],
 ['GLY', 'SER', 'HIS'],
 ['CYS', 'CYS', 'CYS', 'CYS'],
 ['HIS', 'HOH', 'HOH'],
 ['HIS', 'HOH', 'HOH'],
 ['HIS', 'HOH'],
 ['HIS', 'ASP', 'HOH', 'HOH'],
 ['ARG', 'HOH'],
 ['ASP', 'HIS', 'TRS', 'HOH'],
 ['HIS', 'ASP', 'HOH', 'HOH', 'HOH'],
 ['CSD', 'CSO', 'HOH', 'HOH', 'HOH'],
 ['CSD', 'CSO', 'HOH', 'HOH'],
 ['HIS', 'HIS', 'HIS', 'ASP'],
 ['HIS', 'HOH'],
 ['HIS', 'HIS'],
 ['HIS'],
 ['ASP', 'DTP', 'ASP', 'DTP'],
 ['GLU', 'HOH'],
 ['GLU', 'LYS'],
 ['ASN', 'TRP', 'HIS', 'ASP'],
 ['HIS', 'ARG'],
 ['HIS', 'ASP'],
 ['HIS', 'HOH', 'HOH', 'HOH', 'HOH'],
 ['ASN'],
 ['CYS', 'HIS', 'HIS', 'HOH', 'HOH', 'GLU', 'HIS', 'HOH', 'HOH'],
 ['HIS', 'ASP', 'HIS', 'ASP', 'HOH', 'HOH'],
 ['HIS', 'HOH', 'HOH', 'HOH'],
 ['HIS', 'HOH'],
 ['SER', 'GLN', 'HIS'],
 ['HIS', 'GLU'],
 ['HIS', 'HIS', 'HIS'],
 ['HIS', 'HIS', 'HIS'],
 ['HOH'],
 ['HIS', 'ASP', 'HIS', 'HOH'],
 ['GLU', 'HIS', 'HOH', 'HOH', 'HOH'],
 ['HOH', 'HOH'],
 ['HIS', 'HOH', 'HOH', 'HOH'],
 ['HIS', 'HOH', 'HOH', 'HOH'],
 ['HIS', 'HOH', 'HOH', 'HOH'],
 ['HIS'],
 ['HIS', 'BTB'],
 ['HIS', 'ASP', 'GLU'],
 ['HIS', 'HIS', 'ASN', 'HIS', 'GLU'],
 ['HIS', 'ASP', 'HOH', 'HOH', 'HOH', 'HOH'],
 ['HIS', 'HIS', 'GLU', 'IMD', 'HOH'],
 ['ASP', 'HIS', 'HIS', 'ACY', 'HOH'],
 ['ILE', 'LEU', 'ILE'],
 ['HIS', 'LYS', 'SIN', 'HOH', 'HOH', 'HOH'],
 ['HIS', 'HOH', 'HOH'],
 ['CYS', 'HIS', 'GLU', 'HOH'],
 ['HIS', 'HOH'],
 ['HIS', 'ASP', 'ASP', 'ASP', 'ABH', 'HIS', 'ASP', 'ASP', 'ABH'],
 ['GLU',
  'HIS',
  'SOR',
  'DOD',
  'HIS',
  'ASP',
  'ASP',
  'DOD',
  'GLU',
  'ASP',
  'ASP',
  'SOR'],
 ['HIS', 'HIS', 'HOH', 'HOH', 'HOH', 'HOH'],
 ['HIS', 'HOH', 'HOH', 'HOH'],
 ['HIS', 'HOH', 'HOH', 'HOH'],
 ['HIS', 'HOH', 'HOH', 'HOH', 'HOH', 'HOH'],
 ['HOH', 'HOH'],
 ['HIS', 'HIS', 'KCX', 'HIS', 'HIS', 'ASP', 'KCX'],
 ['HIS', 'HOH', 'HOH'],
 ['HIS', 'HIS', 'IMD'],
 ['GLY', 'MET', 'HIS'],
 ['HIS', 'HOH'],
 ['HIS', 'HOH', 'HOH', 'HOH'],
 ['HIS', 'HOH'],
 ['HIS', 'HOH', 'HOH', 'HOH', 'HOH'],
 ['CYS', 'CYS'],
 ['HIS', 'HIS'],
 ['GLU'],
 ['GLY', 'HIS', 'GLU', 'HOH', 'HOH', 'HOH'],
 ['HIS', 'HOH', 'HOH'],
 ['HOH', 'HOH', 'HOH', 'HOH'],
 ['HIS', 'GLU', 'HOH'],
 ['HIS'],
 ['ASP', 'HOH'],
 ['HOH', 'HOH'],
 ['GLU', 'HOH', 'HOH'],
 ['HOH'],
 ['GLU', 'HIS', 'HOH', 'HOH', 'HOH'],
 ['HIS', 'HIS', 'HIS', 'HOH', 'HOH'],
 ['HIS', 'ASP', 'HIS', 'OGA', 'HOH'],
 ['HIS'],
 ['HIS', 'HIS'],
 ['ASP', 'HOH', 'HOH', 'HOH', 'HOH'],
 ['HIS', 'HOH', 'HOH', 'HOH'],
 ['HIS', 'HOH', 'HOH', 'HOH'],
 ['CYS', 'HOH', 'HOH'],
 ['HIS', 'HIS', 'ASN', 'HIS', 'HIS', 'HIS'],
 ['HIS', 'HOH', 'HOH'],
 ['HIS'],
 ['SER', 'HIS', 'TRS', 'HOH'],
 ['ASP', 'HOH'],
 ['HIS'],
 ['HOH'],
 ['ASP', 'HOH'],
 ['SER', 'HIS', 'HOH', 'HOH'],
 ['HIS', 'HOH', 'HOH', 'HOH'],
 ['HIS', 'HIS', 'GLU', 'HIS', 'HOH'],
 ['HIS', 'HIS', 'HOH'],
 ['HIS', 'GLU', 'HOH', 'HOH', 'HOH'],
 ['HIS', 'HIS', 'HOH', 'HOH'],
 ['HIS', 'HOH', 'HOH'],
 ['HIS', 'HOH', 'HOH', 'HOH'],
 ['HIS', 'ASP', 'HIS', 'HOH', 'HOH'],
 ['HIS'],
 ['MET', 'HIS', 'HOH'],
 ['HIS', 'HOH', 'HOH'],
 ['HIS', 'HOH', 'HOH', 'HOH'],
 ['HIS', 'HOH'],
 ['HIS', 'HOH', 'HOH', 'HOH', 'HOH', 'HOH', 'HOH', 'HOH'],
 ['HIS', 'HOH', 'HOH', 'HOH', 'HOH'],
 ['GLU', 'GLN', 'UNL', 'HOH', 'HOH'],
 ['GLN', 'HIS'],
 ['ASP', 'GLU'],
 ['GLY', 'HIS', 'HIS', 'HOH'],
 ['GLY', 'HIS', 'HIS', 'GLN', 'HOH'],
 ['ASP', 'GLU'],
 ['GLY', 'HIS', 'HIS', 'HOH', 'HOH'],
 ['GLU', 'ASP', 'HOH'],
 ['HOH', 'HOH', 'HOH'],
 ['SER', 'SER', 'THR', 'ASP', 'HOH', 'HOH'],
 ['HIS', 'GLU'],
 ['HIS', 'HIS'],
 ['HIS', 'HOH', 'HOH', 'HOH'],
 ['HIS', 'HOH', 'HOH'],
 ['HIS'],
 ['ASP', 'HOH', 'HOH', 'HOH', 'HOH', 'HOH'],
 ['GLY', 'SER', 'HIS'],
 ['ASP', 'TRS', 'HOH'],
 ['HIS'],
 ['HIS'],
 ['HOH', 'HOH', 'HOH', 'HOH'],
 ['GLY', 'SER', 'HIS'],
 ['ASP', 'ASP', 'THR', 'ASP', 'MBY', 'HOH'],
 ['HIS', 'ASP', 'HOH', 'HOH', 'HOH'],
 ['GLU', 'HIS', 'ASP'],
 ['CYS'],
 ['HIS', 'CYS', 'HOH'],
 ['HIS', 'HIS', 'HOH'],
 ['HIS', 'HIS', 'HIS', 'HOH', 'HOH'],
 ['HIS', 'HIS', 'HIS', 'HOH'],
 ['HIS', 'HIS'],
 ['ACT', 'ACT', 'HOH', 'HOH', 'HOH'],
 ['GLU', 'ACT', 'HOH'],
 ['HIS', 'HOH', 'HOH', 'HOH'],
 ['ACT', 'ACT', 'HOH', 'HOH'],
 ['HIS', 'HIS', 'HOH'],
 ['GLY', 'SER', 'HIS'],
 ['CYS', 'CYS'],
 ['HOH'],
 ['HIS', 'HIS'],
 ['HIS', 'HIS'],
 ['HIS', 'HIS'],
 ['CYS', 'HOH', 'HOH'],
 ['HIS'],
 ['HIS', 'HIS'],
 ['HIS', 'HIS', 'CL'],
 ['PRO', 'ASN', 'HOH'],
 ['MET', 'HIS', 'HIS'],
 ['HIS', 'HIS', 'GLU'],
 ['HIS', 'HOH', 'HOH'],
 ['HIS', 'GLN', 'HOH', 'HOH', 'HOH', 'HOH'],
 ['CYS', 'HOH'],
 ['HIS', 'HOH', 'HOH', 'HOH', 'HOH', 'HOH'],
 ['HIS', 'HOH', 'HOH', 'HOH', 'HOH'],
 ['HIS', 'HOH', 'HOH', 'HOH', 'HOH', 'HOH'],
 ['GLU', 'HIS'],
 ['HIS'],
 ['HIS', 'HIS'],
 ['HIS', 'SER'],
 ['GLY', 'SER', 'HIS'],
 ['HIS', 'HIS'],
 ['LEU', 'LCP'],
 ['GLU', 'ASN', 'GLU', 'NAG'],
 ['HIS', 'HIS', 'ASP', 'ASP'],
 ['HIS'],
 ['HIS'],
 ['HIS', 'HOH', 'HOH', 'HOH'],
 ['HIS', 'HIS'],
 ['GLN', 'HIS', 'HIS', 'HOH', 'HOH'],
 ['HIS', 'HIS', 'HIS', 'HOH', 'HOH'],
 ['HIS', 'HIS', 'GLU', 'TRS'],
 ['HIS', 'HIS'],
 ['LEU', 'ASN', 'ASP', 'PHE', 'ASN', 'ASP', 'PHE', 'HOH'],
 ['HIS', 'HIS', 'HIS', 'HIS'],
 ['HIS', 'HOH', 'HOH'],
 ['ASP', 'SER', 'HIS', 'CIT'],
 ['HIS', 'ALA', 'HOH', 'HOH', 'HOH'],
 ['GLU', 'HOH', 'HOH', 'HOH'],
 ['HIS', 'GLU', 'HOH', 'HOH', 'HOH'],
 ['HIS'],
 ['GLY', 'ALA', 'MET'],
 ['HIS'],
 ['HIS', 'ASP', 'HIS', 'DGR', 'HOH'],
 ['GLU', 'HIS', 'HIS', 'HOH'],
 ['GLU', 'HIS', 'HIS', 'HOH', 'HOH'],
 ['GLU', 'HIS', 'ACT'],
 ['ALA', 'HIS', 'HOH'],
 ['HIS', 'HIS', 'GLU', 'HOH'],
 ['HIS', 'HIS'],
 ['HIS', 'HOH', 'HOH', 'HOH'],
 ['HIS', 'HOH'],
 ['THR', 'SER', 'CYS', 'HIS'],
 ['HIS', 'HOH', 'HOH', 'HOH', 'HOH', 'HOH'],
 ['HIS', 'HIS', 'HIS'],
 ['HIS', 'HIS'],
 ['GLU', 'HOH', 'HOH', 'HOH', 'GLU'],
 ['HIS', 'HIS', 'HIS', 'HIS', 'HIS'],
 ['HIS', 'HIS', 'ASP', 'HOH', 'HOH', 'HOH', 'HIS', 'HIS', 'HIS', 'HOH', 'HOH'],
 ['HIS', 'HIS'],
 ['HIS', 'HIS', 'HIS'],
 ['HIS', 'GLU', 'HIS'],
 ['ASP'],
 ['ASP', 'HIS', 'ASP'],
 ['HIS', 'EY'],
 ['GLU', 'HIS'],
 ['GLU', 'HIS', 'HIS'],
 ['HIS', 'HIS'],
 ['GLY', 'HIS'],
 ['GLU', 'HIS', 'GOL'],
 ['HIS', 'HIS', 'ASP', 'ASP', 'HIS', 'HIS', 'HIS'],
 ['ASP', 'GLU'],
 ['HIS', 'IMD', 'IMD', 'IMD', 'IMD'],
 ['HIS', 'HOH'],
 ['HIS', 'HOH', 'HOH'],
 ['MET', 'HIS', 'HIS'],
 ['LEU', 'ASP', 'HOH', 'HOH', 'HOH', 'HOH'],
 ['ASP', 'HOH', 'HOH', 'HOH'],
 ['HIS', 'HIS'],
 ['GLU', 'HIS', 'HIS', 'HOH', 'HOH', 'HOH'],
 ['HIS'],
 ['HIS', 'HOH'],
 ['HIS', 'HOH', 'HOH'],
 ['HIS', 'HIS'],
 ['HOH'],
 ['HIS', 'HIS'],
 ['ASP', 'HIS', 'HOH'],
 ['HIS', 'CYS'],
 ['ASP', 'HIS', 'HOH', 'HOH'],
 ['HIS', 'ASP', 'THR'],
 ['ASP', 'ASP', 'HIS', 'HOH'],
 ['HIS', 'HOH'],
 ['HIS', 'HIS'],
 ['HIS', 'HIS', 'HIS'],
 ['HIS', 'K', 'K', 'GOL', 'HOH'],
 ['HIS', 'HOH'],
 ['HIS', 'HIS', 'HOH'],
 ['HIS', 'HIS', 'HOH'],
 ['HIS', 'HIS', 'HIS', 'HIS', 'HOH'],
 ['HIS'],
 ['HIS', 'HIS'],
 ['HIS', 'SCN', 'SCN'],
 ['HOH', 'HOH'],
 ['HIS', 'HIS', 'LMR', 'HOH', 'HOH'],

In [57]:
ligand_dict = {}
for lig in tup_lig_list:
    if lig not in ligand_dict:
        ligand_dict[lig] = 1
    else:
        ligand_dict[lig] += 1
ligand_dict

{('ASP', 'HIS', 'HIS', 'ASP', 'HOH'): 1,
 ('HIS', 'HOH'): 44,
 ('HIS', 'ASP'): 10,
 ('HIS', 'HIS', 'HOH', 'HOH'): 7,
 ('HOH', 'HOH'): 12,
 ('HIS', 'HOH', 'HOH', 'HOH', 'HOH', 'HOH'): 10,
 ('HIS',): 70,
 ('ASN', 'HIS', 'GLU', 'FMN', 'HOH', 'HOH'): 1,
 ('HIS', 'GDP', 'HOH', 'HOH', 'HOH', 'HOH'): 1,
 ('HIS', 'HOH', 'HOH', 'HOH'): 34,
 ('HIS', 'TRS', 'TRS'): 1,
 ('HIS', 'GLU', 'HIS', 'GLU', 'HOH', 'HOH'): 3,
 ('HIS', 'HIS', 'KCX', 'HOH', 'HOH', 'HOH'): 1,
 ('ALA', 'HOH'): 2,
 ('TRP', 'HOH', 'HOH', 'HOH', 'HOH'): 1,
 ('ASP', 'ASP', 'HIS', 'HOH'): 4,
 ('HIS', 'HIS'): 52,
 ('GLN', 'COM'): 1,
 ('ASP',): 21,
 ('HIS', 'HOH', 'HOH', 'HOH', 'HOH'): 19,
 ('GLY', 'HOH', 'HOH', 'HOH'): 1,
 ('ALA', 'HIS', 'ASP', 'HOH'): 1,
 ('HIS', 'HIS', 'HIS', 'TYR', 'HOH', 'HOH'): 1,
 ('HIS', 'HOH', 'HOH'): 28,
 ('ALA', 'ASP', 'HIS'): 1,
 ('HIS', 'HIS', 'HIS', 'HOH', 'HOH', 'HOH'): 7,
 ('HIS', 'CL', 'HOH', 'CL', 'HOH'): 1,
 ('ASP', 'ASP', 'ASP', 'HOH'): 1,
 ('CYS', 'CYS', 'HIS', 'CL'): 1,
 ('HIS', 'HNI'): 1,
 ('LYS', 'HOH', 'HOH', 'HOH'): 1,
 ('ASN', 'HOH', 'HOH', 'HOH', 'HOH'): 1,
 ('HIS', 'GLU', 'HIS', 'HIS', 'HOH'): 1,
 ('ALA', 'ARG'): 1,
 ('ARG', 'HIS', 'GLU', 'CL'): 1,
 ('LYS', 'HOH'): 1,
 ('HIS', 'HIS', 'HOH', 'HOH', 'HOH', 'HOH'): 7,
 ('HIS', 'GLU', 'HOH', 'HOH', 'HOH'): 5,
 ('HIS', 'HIS', 'HIS', 'ASP', 'HOH', 'HOH'): 1,
 ('CYS', 'HIS', 'HIS', 'HOH'): 1,
 ('ASP', 'ASP', 'GLU', 'ASP', 'HIS', 'GLU', 'GLU', 'HIS', 'CL', 'HOH'): 1,
 ('TCN',): 1,
 ('HIS', 'HIS', 'TRS', 'HOH'): 1,
 ('ASP', 'HIS', 'HOH'): 3,
 ('HIS', 'GLU', 'HOH'): 4,
 ('HIS', 'ASP', 'HOH'): 1,
 ('HIS', 'HIS', 'GLU', 'HIS', 'UNL'): 2,
 ('HIS', 'ASP', 'HIS', 'HOH', 'HOH', 'HOH'): 2,
 ('HIS', 'ASP', 'GLU', 'HOH', 'HOH'): 2,
 ('HIS', 'HIS', 'HIS', 'CYS'): 2,
 ('ALA', 'ASP'): 1,
 ('GLU', 'HOH', 'HOH', 'HOH'): 4,
 ('HOH', 'HOH', 'HOH', 'HOH'): 5,
 ('HIS', 'GLU', 'HOH', 'HOH', 'HOH', 'HOH'): 1,
 ('ALA', 'HOH', 'HOH', 'HOH'): 1,
 ('HIS', 'HIS', 'HIS'): 10,
 ('HIS', 'HOH', 'HOH', 'HOH', 'HOH', 'HOH', 'HOH'): 1,
 ('HIS', 'CL', 'CL'): 2,
 ('ASP', 'ASP', 'ASP', 'SEP', 'HOH'): 1,
 ('HOH',): 13,
 ('HIS', 'CL', 'HOH', 'HOH', 'HOH', 'HOH'): 1,
 ('HIS', 'CL', 'CL', 'CL', 'CL', 'CL'): 1,
 ('GLU', 'ASP'): 2,
 ('GLU', 'ASP', 'LEU', 'VAL'): 1,
 ('SER', 'SER', 'THR', 'ASN', 'HOH', 'HOH'): 1,
 ('HIS', 'HIS', 'GLU', 'ASP', 'HIS', 'HIS'): 1,
 ('HOH', 'HOH', 'HOH'): 4,
 ('HIS', 'ASP', 'HIS', 'IMD', 'IMD'): 1,
 ('HIS', 'ACO', 'ACO'): 1,
 ('GLU', 'GLU', 'HOH'): 3,
 ('GLU', 'GLU', 'HOH', 'HOH'): 2,
 ('HIS', 'GLU', 'HIS'): 3,
 ('GLU', 'HOH'): 7,
 ('ASP', 'VAL', 'ASP', 'PRO', 'GLU', 'HOH'): 1,
 ('ASP', 'GLU', 'ALA', 'ASN', 'HOH'): 1,
 ('HIS', 'LYS', 'HOH', 'HOH', 'HOH'): 2,
 ('GLU', 'HIS', 'ASP', 'GLO', 'HOH', 'GLU', 'ASP', 'ASP', 'GLO'): 1,
 ('GLU', 'HIS', 'CL'): 1,
 ('GLU', 'HIS', 'ASP', 'ASP', 'HOH', 'GLU', 'ASP', 'ASP'): 1,
 ('HIS', 'HIS', 'GLU', 'HIS', 'MET'): 1,
 ('HIS', 'GLU', 'GLU', 'HOH', 'HOH', 'HOH'): 1,
 ('EDO', 'HOH', 'HOH'): 1,
 ('ASP', 'ASP', 'HOH'): 2,
 ('GLY', 'SER', 'HIS'): 11,
 (): 3,
 ('ASP', 'HOH', 'HOH', 'HOH', 'HOH'): 4,
 ('ASP', 'HOH'): 8,
 ('ASP', 'HIS', 'GLU', 'GLU', 'ASP', 'ASP', 'GLU'): 1,
 ('HIS', 'ASP', 'HOH', 'HOH'): 5,
 ('ASP', 'ASP', 'HOH', 'HOH', 'HOH'): 1,
 ('HIS', 'LYS', 'HOH', 'HOH', 'HOH', 'HOH'): 1,
 ('TRP', 'TRS'): 1,
 ('TRP', 'PHE', 'TRS'): 1,
 ('TRP', 'PHE', 'TRS', 'HOH'): 1,
 ('ASP', 'LYS', 'HIS', 'HOH', 'HOH', 'HOH'): 1,
 ('HIS', 'HIS', 'HIS', 'CYS', 'SER', 'HIS'): 1,
 ('ASP', 'HIS', 'HOH', 'HOH', 'HOH', 'HOH'): 1,
 ('ASP', 'HOH', 'HOH', 'HOH', 'HOH', 'HOH'): 4,
 ('GLY',): 1,
 ('ASN',): 2,
 ('HIS', 'HIS', 'HIS', 'IMD', 'IMD'): 1,
 ('HIS', 'HOH', 'HOH', 'HOH', 'HOH', 'HOH', 'HOH', 'HOH', 'HOH', 'HOH'): 1,
 ('HIS', 'GLU', 'HIS', 'GLU', 'HOH'): 2,
 ('HIS', 'HIS', 'GLU', 'HIS', 'HOH'): 2,
 ('MET', 'VAL', 'ASP', 'HOH', 'HOH'): 1,
 ('CYS', 'CYS', 'CYS', 'CYS'): 2,
 ('HIS', 'LYS', 'HOH', 'HOH'): 1,
 ('HIS', 'GLU', 'ASP', 'HOH'): 1,
 ('HIS', 'HQI'): 1,
 ('HIS', 'HIS', 'GLU', 'HOH'): 3,
 ('HIS', 'HIS', 'HIS', 'EDO', 'MLI'): 1,
 ('HIS', 'HIS', 'HIS', 'ASP'): 3,
 ('SER',): 1,
 ('HIS', 'HIS', 'HOH', 'HOH', 'HOH'): 6,
 ('HIS', 'HIS', 'GLU', 'HIS', 'HOH', 'HOH'): 1,
 ('HIS', 'GLU', 'HIS', 'HOH', 'HOH'): 3,
 ('HIS', 'HIS', 'HIS', 'CIT'): 1,
 ('CYS',): 3,
 ('CYS', 'CYS', 'CYS', 'CYS', 'CYS', 'GLY', 'CYS'): 4,
 ('GLU', 'GLU', 'NOS'): 1,
 ('GLU', 'HIS', 'LYS', 'HOH', 'HOH'): 1,
 ('HIS', 'HIS', 'HIS', 'FMT', 'HOH'): 1,
 ('LYS', 'HIS', 'HOH', 'CL'): 1,
 ('GLY', 'HIS', 'HIS', 'HOH'): 2,
 ('GLU',): 11,
 ('GLU', 'HOH', 'HOH'): 5,
 ('HIS', 'HIS', 'GLU', 'HOH', 'HOH', 'HOH'): 2,
 ('HIS', 'HIS', 'HIS', 'HOH', 'HOH'): 5,
 ('ASP', 'HIS', 'HIS', 'HOH'): 2,
 ('HOH', 'HOH', 'HOH', 'HOH', 'HOH'): 2,
 ('ASN', 'HIS', 'HIS', 'HOH', 'HIS', 'ASP', 'HIS', 'HOH'): 1,
 ('MET', 'ASP', 'GLU', 'HIS', 'HOH'): 1,
 ('THR', 'GLN', 'HIS'): 1,
 ('GLU', 'GLU'): 2,
 ('CYS', 'CSO', 'NFC', 'CYS', 'CSO', 'CSO', 'NFC'): 1,
 ('HIS', 'HIS', 'HIS', 'HIS', 'IMD', 'HOH'): 2,
 ('HIS', 'HOH', 'HOH', 'GOL'): 1,
 ('GLU', 'HIS', 'ASP', 'ASP', 'HOH'): 1,
 ('HIS', 'HIS', 'HIS', 'HOH'): 3,
 ('HOH', 'PXX'): 3,
 ('HIS', 'CYS', 'NFS', 'NFS', 'HOH', 'NFS', 'NFS'): 1,
 ('CYS', 'NFS', 'NFS', 'HOH', 'NFS', 'NFS'): 1,
 ('GLU',
  'ASP',
  'GLU',
  'ASP',
  'HOH',
  'ASN',
  'ASP',
  'HOH',
  'HOH',
  'GLU',
  'GLU',
  'HOH',
  'HOH',
  'GLU',
  'ASP',
  'HOH',
  'HOH'): 1,
 ('GLU', 'HIS'): 5,
 ('GLY', 'HIS', 'HOH', 'HOH'): 2,
 ('GLY', 'HIS', 'HOH'): 1,
 ('GLU',
  'ASP',
  'ASP',
  'HIS',
  'HOH',
  'HOH',
  'TYR',
  'ASN',
  'ASP',
  'HOH',
  'HOH'): 1,
 ('SER', 'HOH', 'HOH', 'HOH'): 3,
 ('ARG', 'HIS'): 1,
 ('GLU', 'GLU', 'HOH', 'HOH', 'HOH', 'HOH'): 2,
 ('HIS', 'CYS', 'CYS'): 1,
 ('ASP', 'ASP', 'HIS', 'HOH', 'HOH'): 1,
 ('MET', 'HOH', 'HOH'): 1,
 ('ASP', 'HIS'): 4,
 ('HIS', 'GLN', 'GLU'): 1,
 ('HIS', 'GLU'): 5,
 ('ARG',): 1,
 ('ASP', 'GLY', 'HIS', 'HOH', 'HOH'): 1,
 ('MET', 'HIS'): 1,
 ('BTN',): 1,
 ('ASP', 'HIS', 'HIS', 'HIS', 'UNL'): 1,
 ('HIS', 'HIS', 'ASP', 'ASP'): 2,
 ('CGU', 'CGU', 'CL', 'HOH', 'CL', 'CL'): 1,
 ('GLY', 'HIS', 'HOH', 'HOH', 'HOH'): 1,
 ('ASP', 'HOH', 'HOH', 'HOH'): 6,
 ('HIS', 'ASP', 'HIS', 'OGA', 'HOH'): 2,
 ('GLU', 'ASP', 'GLU', 'HOH'): 1,
 ('CYS', 'GLY', 'CYS', 'CYS', 'HOH'): 1,
 ('HIS', 'LYS', 'HIS', 'HOH'): 2,
 ('HIS', 'HIS', 'HOH'): 11,
 ('HIS', 'HIS', 'HIS', 'IMD'): 1,
 ('GLU', 'ASP', 'HOH'): 2,
 ('GLU', 'ASP', 'ASP', 'HOH', 'HOH', 'ASP', 'ASP', 'CYS', 'ASP', 'HOH'): 1,
 ('HIS', 'GLU', 'HIS', 'HOH'): 2,
 ('HIS', 'HIS', 'ASP', 'TRS'): 1,
 ('HIS', 'TRS', 'HOH', 'HOH'): 1,
 ('HIS', 'HIS', 'GLU', 'HOH', 'HOH'): 2,
 ('HIS', 'GLU', 'HOH', 'HOH'): 1,
 ('HIS', 'GLU', 'ASP', 'ASP'): 1,
 ('HIS', 'HIS', 'ASP', 'ASP', 'HOH', 'HOH'): 1,
 ('HIS', 'ASP', 'HIS', 'HOH', 'HOH'): 2,
 ('COM',): 1,
 ('VAL', 'ASP', 'HOH', 'HOH'): 1,
 ('ASP', 'GLN', 'HIS', 'HOH'): 1,
 ('HIS', 'HIS', 'TYR', 'HOH', 'HOH'): 1,
 ('HIS', 'IMD'): 1,
 ('HIS', 'CYS'): 2,
 ('GLU', 'HIS', 'HOH', 'HOH', 'HOH', 'HOH'): 1,
 ('LYS',): 3,
 ('HIS', 'HIS', 'CYS'): 1,
 ('HIS', 'CTC', 'HOH', 'HOH', 'HOH'): 1,
 ('CYS', 'HIS', 'IMD', 'IMD'): 1,
 ('ASP', 'HIS', 'HIS'): 1,
 ('HIS', 'HIS', 'CYS', 'HOH'): 1,
 ('GLU', 'HIS', 'HIS', 'HOH', 'HOH', 'HOH'): 2,
 ('ASP', 'GLU', 'GLU', 'HOH', 'HOH', 'ASP', 'PHE', 'GLN', 'GLU'): 1,
 ('HIS', 'HIS', 'ACT', 'HOH'): 1,
 ('ASP', 'ASP'): 1,
 ('ARG', 'HIS', 'ASP', 'HOH'): 1,
 ('HIS', 'COA'): 1,
 ('ILE', 'HOH', 'HOH', 'HOH', 'HOH'): 1,
 ('ASP', 'HIS', 'HOH', 'HOH', 'HOH'): 1,
 ('CYS', 'GLU', 'HOH', 'HOH'): 1,
 ('CYS', 'HOH'): 2,
 ('HIS', 'ASP', 'GLU', 'HOH', 'HOH', 'HOH'): 1,
 ('HIS', 'LYS'): 1,
 ('ASN', 'GLN', 'HOH', 'HOH'): 1,
 ('ASP', 'ASP', 'ASN', 'HOH'): 1,
 ('HIS', 'HIS', 'HIS', 'UNL'): 2,
 ('MET', 'ASP', 'HOH', 'HOH', 'HOH'): 1,
 ('GLY', 'HIS', 'CYS', 'HIS'): 1,
 ('ASN', 'HIS', 'HIS', 'HIS', 'HOH', 'HOH'): 1,
 ('ASP', 'HIS', 'HIS', 'ASN', 'HOH', 'HOH'): 1,
 ('ASP', 'ASN', 'HIS', 'HOH', 'HOH'): 1,
 ('HIS', 'HIS', 'ASP', 'HOH'): 1,
 ('MET', 'HOH', 'HOH', 'HOH', 'HOH'): 2,
 ('SER', 'HIS'): 1,
 ('HIS', 'ASP', 'HIS', 'HOH', 'AKG'): 1,
 ('HIS', 'ASP', 'HOH', 'HOH', 'HOH'): 3,
 ('MET', 'HOH', 'HOH', 'HOH'): 1,
 ('ASN', 'ASN'): 1,
 ('ASP',
  'HIS',
  'ASP',
  'HIS',
  'HOH',
  'HOH',
  'HIS',
  'HIS',
  'ASP',
  'HOH',
  'HOH'): 2,
 ('DG', 'HOH', 'HOH', 'HOH', 'HOH'): 1,
 ('HIS', 'HIS', 'HIS', 'GLU', 'HOH', 'HOH'): 1,
 ('HIS', 'HIS', 'HIS', 'HIS', 'HIS'): 2,
 ('ARG', 'HOH'): 1,
 ('ASP', 'HIS', 'TRS', 'HOH'): 1,
 ('CSD', 'CSO', 'HOH', 'HOH', 'HOH'): 1,
 ('CSD', 'CSO', 'HOH', 'HOH'): 1,
 ('ASP', 'DTP', 'ASP', 'DTP'): 1,
 ('GLU', 'LYS'): 1,
 ('ASN', 'TRP', 'HIS', 'ASP'): 1,
 ('HIS', 'ARG'): 1,
 ('CYS', 'HIS', 'HIS', 'HOH', 'HOH', 'GLU', 'HIS', 'HOH', 'HOH'): 1,
 ('HIS', 'ASP', 'HIS', 'ASP', 'HOH', 'HOH'): 1,
 ('SER', 'GLN', 'HIS'): 1,
 ('HIS', 'ASP', 'HIS', 'HOH'): 1,
 ('GLU', 'HIS', 'HOH', 'HOH', 'HOH'): 2,
 ('HIS', 'BTB'): 3,
 ('HIS', 'ASP', 'GLU'): 1,
 ('HIS', 'HIS', 'ASN', 'HIS', 'GLU'): 1,
 ('HIS', 'ASP', 'HOH', 'HOH', 'HOH', 'HOH'): 2,
 ('HIS', 'HIS', 'GLU', 'IMD', 'HOH'): 1,
 ('ASP', 'HIS', 'HIS', 'ACY', 'HOH'): 1,
 ('ILE', 'LEU', 'ILE'): 1,
 ('HIS', 'LYS', 'SIN', 'HOH', 'HOH', 'HOH'): 1,
 ('CYS', 'HIS', 'GLU', 'HOH'): 1,
 ('HIS', 'ASP', 'ASP', 'ASP', 'ABH', 'HIS', 'ASP', 'ASP', 'ABH'): 1,
 ('GLU',
  'HIS',
  'SOR',
  'DOD',
  'HIS',
  'ASP',
  'ASP',
  'DOD',
  'GLU',
  'ASP',
  'ASP',
  'SOR'): 1,
 ('HIS', 'HIS', 'KCX', 'HIS', 'HIS', 'ASP', 'KCX'): 1,
 ('HIS', 'HIS', 'IMD'): 1,
 ('GLY', 'MET', 'HIS'): 1,
 ('CYS', 'CYS'): 2,
 ('GLY', 'HIS', 'GLU', 'HOH', 'HOH', 'HOH'): 1,
 ('CYS', 'HOH', 'HOH'): 2,
 ('HIS', 'HIS', 'ASN', 'HIS', 'HIS', 'HIS'): 1,
 ('SER', 'HIS', 'TRS', 'HOH'): 1,
 ('SER', 'HIS', 'HOH', 'HOH'): 1,
 ('MET', 'HIS', 'HOH'): 1,
 ('HIS', 'HOH', 'HOH', 'HOH', 'HOH', 'HOH', 'HOH', 'HOH'): 1,
 ('GLU', 'GLN', 'UNL', 'HOH', 'HOH'): 1,
 ('GLN', 'HIS'): 1,
 ('ASP', 'GLU'): 4,
 ('GLY', 'HIS', 'HIS', 'GLN', 'HOH'): 1,
 ('GLY', 'HIS', 'HIS', 'HOH', 'HOH'): 1,
 ('SER', 'SER', 'THR', 'ASP', 'HOH', 'HOH'): 1,
 ('ASP', 'TRS', 'HOH'): 1,
 ('ASP', 'ASP', 'THR', 'ASP', 'MBY', 'HOH'): 1,
 ('GLU', 'HIS', 'ASP'): 1,
 ('HIS', 'CYS', 'HOH'): 1,
 ('ACT', 'ACT', 'HOH', 'HOH', 'HOH'): 1,
 ('GLU', 'ACT', 'HOH'): 1,
 ('ACT', 'ACT', 'HOH', 'HOH'): 1,
 ('HIS', 'HIS', 'CL'): 2,
 ('PRO', 'ASN', 'HOH'): 1,
 ('MET', 'HIS', 'HIS'): 2,
 ('HIS', 'HIS', 'GLU'): 1,
 ('HIS', 'GLN', 'HOH', 'HOH', 'HOH', 'HOH'): 1,
 ('HIS', 'SER'): 1,
 ('LEU', 'LCP'): 1,
 ('GLU', 'ASN', 'GLU', 'NAG'): 1,
 ('GLN', 'HIS', 'HIS', 'HOH', 'HOH'): 1,
 ('HIS', 'HIS', 'GLU', 'TRS'): 1,
 ('LEU', 'ASN', 'ASP', 'PHE', 'ASN', 'ASP', 'PHE', 'HOH'): 1,
 ('HIS', 'HIS', 'HIS', 'HIS'): 1,
 ('ASP', 'SER', 'HIS', 'CIT'): 1,
 ('HIS', 'ALA', 'HOH', 'HOH', 'HOH'): 1,
 ('GLY', 'ALA', 'MET'): 1,
 ('HIS', 'ASP', 'HIS', 'DGR', 'HOH'): 1,
 ('GLU', 'HIS', 'HIS', 'HOH'): 2,
 ('GLU', 'HIS', 'HIS', 'HOH', 'HOH'): 2,
 ('GLU', 'HIS', 'ACT'): 1,
 ('ALA', 'HIS', 'HOH'): 1,
 ('THR', 'SER', 'CYS', 'HIS'): 1,
 ('GLU', 'HOH', 'HOH', 'HOH', 'GLU'): 1,
 ('HIS',
  'HIS',
  'ASP',
  'HOH',
  'HOH',
  'HOH',
  'HIS',
  'HIS',
  'HIS',
  'HOH',
  'HOH'): 1,
 ('ASP', 'HIS', 'ASP'): 1,
 ('HIS', 'EY'): 1,
 ('GLU', 'HIS', 'HIS'): 1,
 ('GLY', 'HIS'): 1,
 ('GLU', 'HIS', 'GOL'): 1,
 ('HIS', 'HIS', 'ASP', 'ASP', 'HIS', 'HIS', 'HIS'): 1,
 ('HIS', 'IMD', 'IMD', 'IMD', 'IMD'): 1,
 ('LEU', 'ASP', 'HOH', 'HOH', 'HOH', 'HOH'): 1,
 ('ASP', 'HIS', 'HOH', 'HOH'): 1,
 ('HIS', 'ASP', 'THR'): 1,
 ('HIS', 'K', 'K', 'GOL', 'HOH'): 1,
 ('HIS', 'HIS', 'HIS', 'HIS', 'HOH'): 1,
 ('HIS', 'SCN', 'SCN'): 1,
 ('HIS', 'HIS', 'LMR', 'HOH', 'HOH'): 1,
 ('HIS', 'ASP', 'HIS', 'AKG'): 1,
 ('ASN', 'ASP', 'HOH'): 1,
 ('ASN', 'HIS'): 1,
 ('ASN', 'GLN', 'HIS', 'GLU'): 1,
 ('HIS', 'HIS', 'CL', 'HOH'): 1,
 ('GLY', 'HIS', 'HIS', 'GLN', 'HIS'): 1,
 ('HIS',
  'HIS',
  'HIS',
  'ASP',
  'HOH',
  'HOH',
  'HIS',
  'ASP',
  'HIS',
  'HOH',
  'HOH'): 1,
 ('GLN', 'HIS', 'GLU', 'HOH', 'HOH', 'HOH'): 1,
 ('THR',): 1,
 ('CYS',
  'CYS',
  'FES',
  'HIS',
  'FES',
  'CYS',
  'FES',
  'HIS',
  'FES',
  'HIS',
  'HOH',
  'HOH',
  'HOH',
  'HOH'): 1,
 ('HIS', 'ASP', 'HIS', 'SIN', 'HOH'): 1,
 ('CYS', 'CYS', 'HIS', 'HIS'): 1,
 ('HIS', 'LYS', 'HIS', 'HOH', 'HOH'): 1,
 ('GLU', 'GLU', 'ASN', 'ASN', 'THR', 'HOH'): 1,
 ('VAL', 'HOH'): 1,
 ('MET', 'HOH'): 1,
 ('GLU',
  'GLU',
  'ASP',
  'GLN',
  'ASP',
  'ASP',
  'HIS',
  'ASP',
  'ASP',
  'ASN',
  'ASP',
  'HOH'): 1,
 ('PRO',): 1,
 ('GLY', 'IMD'): 1,
 ('HIS', 'ACT', 'HOH'): 1,
 ('HIS', 'ASP', 'CL'): 1,
 ('GLU', 'ASP', 'HIS', 'GLU', 'HOH'): 1,
 ('GLU', 'ASP', 'GOA', 'HOH', 'HOH'): 1,
 ('ASN', 'HIS', 'HOH', 'HOH', 'HOH', 'HOH'): 1,
 ('HIS', 'HIS', 'HOH', 'HOH', 'HOH', 'HOH', 'HOH'): 1,
 ('ASP', 'ASN', 'HIS', 'HIS', 'HIS', 'ASP', 'HOH'): 1,
 ('HIS', 'ASP', 'HOH', 'HOH', 'ASP', 'HOH', 'HOH', 'HOH', 'HOH'): 1,
 ('HIS', 'HIS', 'ASP', 'HOH', 'HOH', 'HOH'): 1,
 ('HIS', 'HIS', 'AKG', 'HOH', 'HOH'): 1,
 ('GLU', 'HOH', 'HOH', 'HOH', 'HOH'): 1,
 ('GLU', 'HIS', 'HIS', 'HOH', 'ASP', 'GLU'): 1,
 ('SER', 'CYS'): 1,
 ('HIS', 'ASP', 'HIS', 'HIS'): 1,
 ('HIS', 'HIS', 'HIS', 'HIS', 'HIS', 'HIS'): 1,
 ('MET', 'HIS', 'HOH', 'HOH', 'HOH'): 1,
 ('DG', 'HIS', 'ASP'): 1,
 ('DG', 'LYS'): 1,
 ('ASP', 'ASP', 'HOH', 'HOH'): 1,
 ('GLU',
  'GLU',
  'GLU',
  'HOH',
  'HOH',
  'GLU',
  'GLU',
  'HOH',
  'HOH',
  'HOH',
  'HOH',
  'HOH',
  'HOH',
  'HOH',
  'HOH',
  'HOH',
  'HOH',
  'HOH'): 1}

In [58]:
{lig: count for lig, count in sorted(ligand_dict.items(), key=lambda item: -item[1])}

{('HIS',): 70,
 ('HIS', 'HIS'): 52,
 ('HIS', 'HOH'): 44,
 ('HIS', 'HOH', 'HOH', 'HOH'): 34,
 ('HIS', 'HOH', 'HOH'): 28,
 ('ASP',): 21,
 ('HIS', 'HOH', 'HOH', 'HOH', 'HOH'): 19,
 ('HOH',): 13,
 ('HOH', 'HOH'): 12,
 ('GLY', 'SER', 'HIS'): 11,
 ('GLU',): 11,
 ('HIS', 'HIS', 'HOH'): 11,
 ('HIS', 'ASP'): 10,
 ('HIS', 'HOH', 'HOH', 'HOH', 'HOH', 'HOH'): 10,
 ('HIS', 'HIS', 'HIS'): 10,
 ('ASP', 'HOH'): 8,
 ('HIS', 'HIS', 'HOH', 'HOH'): 7,
 ('HIS', 'HIS', 'HIS', 'HOH', 'HOH', 'HOH'): 7,
 ('HIS', 'HIS', 'HOH', 'HOH', 'HOH', 'HOH'): 7,
 ('GLU', 'HOH'): 7,
 ('HIS', 'HIS', 'HOH', 'HOH', 'HOH'): 6,
 ('ASP', 'HOH', 'HOH', 'HOH'): 6,
 ('HIS', 'GLU', 'HOH', 'HOH', 'HOH'): 5,
 ('HOH', 'HOH', 'HOH', 'HOH'): 5,
 ('HIS', 'ASP', 'HOH', 'HOH'): 5,
 ('GLU', 'HOH', 'HOH'): 5,
 ('HIS', 'HIS', 'HIS', 'HOH', 'HOH'): 5,
 ('GLU', 'HIS'): 5,
 ('HIS', 'GLU'): 5,
 ('ASP', 'ASP', 'HIS', 'HOH'): 4,
 ('HIS', 'GLU', 'HOH'): 4,
 ('GLU', 'HOH', 'HOH', 'HOH'): 4,
 ('HOH', 'HOH', 'HOH'): 4,
 ('ASP', 'HOH', 'HOH', 'HOH', 'HOH'): 4,
 ('ASP', 'HOH', 'HOH', 'HOH', 'HOH', 'HOH'): 4,
 ('CYS', 'CYS', 'CYS', 'CYS', 'CYS', 'GLY', 'CYS'): 4,
 ('ASP', 'HIS'): 4,
 ('ASP', 'GLU'): 4,
 ('HIS', 'GLU', 'HIS', 'GLU', 'HOH', 'HOH'): 3,
 ('ASP', 'HIS', 'HOH'): 3,
 ('GLU', 'GLU', 'HOH'): 3,
 ('HIS', 'GLU', 'HIS'): 3,
 (): 3,
 ('HIS', 'HIS', 'GLU', 'HOH'): 3,
 ('HIS', 'HIS', 'HIS', 'ASP'): 3,
 ('HIS', 'GLU', 'HIS', 'HOH', 'HOH'): 3,
 ('CYS',): 3,
 ('HIS', 'HIS', 'HIS', 'HOH'): 3,
 ('HOH', 'PXX'): 3,
 ('SER', 'HOH', 'HOH', 'HOH'): 3,
 ('LYS',): 3,
 ('HIS', 'ASP', 'HOH', 'HOH', 'HOH'): 3,
 ('HIS', 'BTB'): 3,
 ('ALA', 'HOH'): 2,
 ('HIS', 'HIS', 'GLU', 'HIS', 'UNL'): 2,
 ('HIS', 'ASP', 'HIS', 'HOH', 'HOH', 'HOH'): 2,
 ('HIS', 'ASP', 'GLU', 'HOH', 'HOH'): 2,
 ('HIS', 'HIS', 'HIS', 'CYS'): 2,
 ('HIS', 'CL', 'CL'): 2,
 ('GLU', 'ASP'): 2,
 ('GLU', 'GLU', 'HOH', 'HOH'): 2,
 ('HIS', 'LYS', 'HOH', 'HOH', 'HOH'): 2,
 ('ASP', 'ASP', 'HOH'): 2,
 ('ASN',): 2,
 ('HIS', 'GLU', 'HIS', 'GLU', 'HOH'): 2,
 ('HIS', 'HIS', 'GLU', 'HIS', 'HOH'): 2,
 ('CYS', 'CYS', 'CYS', 'CYS'): 2,
 ('GLY', 'HIS', 'HIS', 'HOH'): 2,
 ('HIS', 'HIS', 'GLU', 'HOH', 'HOH', 'HOH'): 2,
 ('ASP', 'HIS', 'HIS', 'HOH'): 2,
 ('HOH', 'HOH', 'HOH', 'HOH', 'HOH'): 2,
 ('GLU', 'GLU'): 2,
 ('HIS', 'HIS', 'HIS', 'HIS', 'IMD', 'HOH'): 2,
 ('GLY', 'HIS', 'HOH', 'HOH'): 2,
 ('GLU', 'GLU', 'HOH', 'HOH', 'HOH', 'HOH'): 2,
 ('HIS', 'HIS', 'ASP', 'ASP'): 2,
 ('HIS', 'ASP', 'HIS', 'OGA', 'HOH'): 2,
 ('HIS', 'LYS', 'HIS', 'HOH'): 2,
 ('GLU', 'ASP', 'HOH'): 2,
 ('HIS', 'GLU', 'HIS', 'HOH'): 2,
 ('HIS', 'HIS', 'GLU', 'HOH', 'HOH'): 2,
 ('HIS', 'ASP', 'HIS', 'HOH', 'HOH'): 2,
 ('HIS', 'CYS'): 2,
 ('GLU', 'HIS', 'HIS', 'HOH', 'HOH', 'HOH'): 2,
 ('CYS', 'HOH'): 2,
 ('HIS', 'HIS', 'HIS', 'UNL'): 2,
 ('MET', 'HOH', 'HOH', 'HOH', 'HOH'): 2,
 ('ASP',
  'HIS',
  'ASP',
  'HIS',
  'HOH',
  'HOH',
  'HIS',
  'HIS',
  'ASP',
  'HOH',
  'HOH'): 2,
 ('HIS', 'HIS', 'HIS', 'HIS', 'HIS'): 2,
 ('GLU', 'HIS', 'HOH', 'HOH', 'HOH'): 2,
 ('HIS', 'ASP', 'HOH', 'HOH', 'HOH', 'HOH'): 2,
 ('CYS', 'CYS'): 2,
 ('CYS', 'HOH', 'HOH'): 2,
 ('HIS', 'HIS', 'CL'): 2,
 ('MET', 'HIS', 'HIS'): 2,
 ('GLU', 'HIS', 'HIS', 'HOH'): 2,
 ('GLU', 'HIS', 'HIS', 'HOH', 'HOH'): 2,
 ('ASP', 'HIS', 'HIS', 'ASP', 'HOH'): 1,
 ('ASN', 'HIS', 'GLU', 'FMN', 'HOH', 'HOH'): 1,
 ('HIS', 'GDP', 'HOH', 'HOH', 'HOH', 'HOH'): 1,
 ('HIS', 'TRS', 'TRS'): 1,
 ('HIS', 'HIS', 'KCX', 'HOH', 'HOH', 'HOH'): 1,
 ('TRP', 'HOH', 'HOH', 'HOH', 'HOH'): 1,
 ('GLN', 'COM'): 1,
 ('GLY', 'HOH', 'HOH', 'HOH'): 1,
 ('ALA', 'HIS', 'ASP', 'HOH'): 1,
 ('HIS', 'HIS', 'HIS', 'TYR', 'HOH', 'HOH'): 1,
 ('ALA', 'ASP', 'HIS'): 1,
 ('HIS', 'CL', 'HOH', 'CL', 'HOH'): 1,
 ('ASP', 'ASP', 'ASP', 'HOH'): 1,
 ('CYS', 'CYS', 'HIS', 'CL'): 1,
 ('HIS', 'HNI'): 1,
 ('LYS', 'HOH', 'HOH', 'HOH'): 1,
 ('ASN', 'HOH', 'HOH', 'HOH', 'HOH'): 1,
 ('HIS', 'GLU', 'HIS', 'HIS', 'HOH'): 1,
 ('ALA', 'ARG'): 1,
 ('ARG', 'HIS', 'GLU', 'CL'): 1,
 ('LYS', 'HOH'): 1,
 ('HIS', 'HIS', 'HIS', 'ASP', 'HOH', 'HOH'): 1,
 ('CYS', 'HIS', 'HIS', 'HOH'): 1,
 ('ASP', 'ASP', 'GLU', 'ASP', 'HIS', 'GLU', 'GLU', 'HIS', 'CL', 'HOH'): 1,
 ('TCN',): 1,
 ('HIS', 'HIS', 'TRS', 'HOH'): 1,
 ('HIS', 'ASP', 'HOH'): 1,
 ('ALA', 'ASP'): 1,
 ('HIS', 'GLU', 'HOH', 'HOH', 'HOH', 'HOH'): 1,
 ('ALA', 'HOH', 'HOH', 'HOH'): 1,
 ('HIS', 'HOH', 'HOH', 'HOH', 'HOH', 'HOH', 'HOH'): 1,
 ('ASP', 'ASP', 'ASP', 'SEP', 'HOH'): 1,
 ('HIS', 'CL', 'HOH', 'HOH', 'HOH', 'HOH'): 1,
 ('HIS', 'CL', 'CL', 'CL', 'CL', 'CL'): 1,
 ('GLU', 'ASP', 'LEU', 'VAL'): 1,
 ('SER', 'SER', 'THR', 'ASN', 'HOH', 'HOH'): 1,
 ('HIS', 'HIS', 'GLU', 'ASP', 'HIS', 'HIS'): 1,
 ('HIS', 'ASP', 'HIS', 'IMD', 'IMD'): 1,
 ('HIS', 'ACO', 'ACO'): 1,
 ('ASP', 'VAL', 'ASP', 'PRO', 'GLU', 'HOH'): 1,
 ('ASP', 'GLU', 'ALA', 'ASN', 'HOH'): 1,
 ('GLU', 'HIS', 'ASP', 'GLO', 'HOH', 'GLU', 'ASP', 'ASP', 'GLO'): 1,
 ('GLU', 'HIS', 'CL'): 1,
 ('GLU', 'HIS', 'ASP', 'ASP', 'HOH', 'GLU', 'ASP', 'ASP'): 1,
 ('HIS', 'HIS', 'GLU', 'HIS', 'MET'): 1,
 ('HIS', 'GLU', 'GLU', 'HOH', 'HOH', 'HOH'): 1,
 ('EDO', 'HOH', 'HOH'): 1,
 ('ASP', 'HIS', 'GLU', 'GLU', 'ASP', 'ASP', 'GLU'): 1,
 ('ASP', 'ASP', 'HOH', 'HOH', 'HOH'): 1,
 ('HIS', 'LYS', 'HOH', 'HOH', 'HOH', 'HOH'): 1,
 ('TRP', 'TRS'): 1,
 ('TRP', 'PHE', 'TRS'): 1,
 ('TRP', 'PHE', 'TRS', 'HOH'): 1,
 ('ASP', 'LYS', 'HIS', 'HOH', 'HOH', 'HOH'): 1,
 ('HIS', 'HIS', 'HIS', 'CYS', 'SER', 'HIS'): 1,
 ('ASP', 'HIS', 'HOH', 'HOH', 'HOH', 'HOH'): 1,
 ('GLY',): 1,
 ('HIS', 'HIS', 'HIS', 'IMD', 'IMD'): 1,
 ('HIS', 'HOH', 'HOH', 'HOH', 'HOH', 'HOH', 'HOH', 'HOH', 'HOH', 'HOH'): 1,
 ('MET', 'VAL', 'ASP', 'HOH', 'HOH'): 1,
 ('HIS', 'LYS', 'HOH', 'HOH'): 1,
 ('HIS', 'GLU', 'ASP', 'HOH'): 1,
 ('HIS', 'HQI'): 1,
 ('HIS', 'HIS', 'HIS', 'EDO', 'MLI'): 1,
 ('SER',): 1,
 ('HIS', 'HIS', 'GLU', 'HIS', 'HOH', 'HOH'): 1,
 ('HIS', 'HIS', 'HIS', 'CIT'): 1,
 ('GLU', 'GLU', 'NOS'): 1,
 ('GLU', 'HIS', 'LYS', 'HOH', 'HOH'): 1,
 ('HIS', 'HIS', 'HIS', 'FMT', 'HOH'): 1,
 ('LYS', 'HIS', 'HOH', 'CL'): 1,
 ('ASN', 'HIS', 'HIS', 'HOH', 'HIS', 'ASP', 'HIS', 'HOH'): 1,
 ('MET', 'ASP', 'GLU', 'HIS', 'HOH'): 1,
 ('THR', 'GLN', 'HIS'): 1,
 ('CYS', 'CSO', 'NFC', 'CYS', 'CSO', 'CSO', 'NFC'): 1,
 ('HIS', 'HOH', 'HOH', 'GOL'): 1,
 ('GLU', 'HIS', 'ASP', 'ASP', 'HOH'): 1,
 ('HIS', 'CYS', 'NFS', 'NFS', 'HOH', 'NFS', 'NFS'): 1,
 ('CYS', 'NFS', 'NFS', 'HOH', 'NFS', 'NFS'): 1,
 ('GLU',
  'ASP',
  'GLU',
  'ASP',
  'HOH',
  'ASN',
  'ASP',
  'HOH',
  'HOH',
  'GLU',
  'GLU',
  'HOH',
  'HOH',
  'GLU',
  'ASP',
  'HOH',
  'HOH'): 1,
 ('GLY', 'HIS', 'HOH'): 1,
 ('GLU',
  'ASP',
  'ASP',
  'HIS',
  'HOH',
  'HOH',
  'TYR',
  'ASN',
  'ASP',
  'HOH',
  'HOH'): 1,
 ('ARG', 'HIS'): 1,
 ('HIS', 'CYS', 'CYS'): 1,
 ('ASP', 'ASP', 'HIS', 'HOH', 'HOH'): 1,
 ('MET', 'HOH', 'HOH'): 1,
 ('HIS', 'GLN', 'GLU'): 1,
 ('ARG',): 1,
 ('ASP', 'GLY', 'HIS', 'HOH', 'HOH'): 1,
 ('MET', 'HIS'): 1,
 ('BTN',): 1,
 ('ASP', 'HIS', 'HIS', 'HIS', 'UNL'): 1,
 ('CGU', 'CGU', 'CL', 'HOH', 'CL', 'CL'): 1,
 ('GLY', 'HIS', 'HOH', 'HOH', 'HOH'): 1,
 ('GLU', 'ASP', 'GLU', 'HOH'): 1,
 ('CYS', 'GLY', 'CYS', 'CYS', 'HOH'): 1,
 ('HIS', 'HIS', 'HIS', 'IMD'): 1,
 ('GLU', 'ASP', 'ASP', 'HOH', 'HOH', 'ASP', 'ASP', 'CYS', 'ASP', 'HOH'): 1,
 ('HIS', 'HIS', 'ASP', 'TRS'): 1,
 ('HIS', 'TRS', 'HOH', 'HOH'): 1,
 ('HIS', 'GLU', 'HOH', 'HOH'): 1,
 ('HIS', 'GLU', 'ASP', 'ASP'): 1,
 ('HIS', 'HIS', 'ASP', 'ASP', 'HOH', 'HOH'): 1,
 ('COM',): 1,
 ('VAL', 'ASP', 'HOH', 'HOH'): 1,
 ('ASP', 'GLN', 'HIS', 'HOH'): 1,
 ('HIS', 'HIS', 'TYR', 'HOH', 'HOH'): 1,
 ('HIS', 'IMD'): 1,
 ('GLU', 'HIS', 'HOH', 'HOH', 'HOH', 'HOH'): 1,
 ('HIS', 'HIS', 'CYS'): 1,
 ('HIS', 'CTC', 'HOH', 'HOH', 'HOH'): 1,
 ('CYS', 'HIS', 'IMD', 'IMD'): 1,
 ('ASP', 'HIS', 'HIS'): 1,
 ('HIS', 'HIS', 'CYS', 'HOH'): 1,
 ('ASP', 'GLU', 'GLU', 'HOH', 'HOH', 'ASP', 'PHE', 'GLN', 'GLU'): 1,
 ('HIS', 'HIS', 'ACT', 'HOH'): 1,
 ('ASP', 'ASP'): 1,
 ('ARG', 'HIS', 'ASP', 'HOH'): 1,
 ('HIS', 'COA'): 1,
 ('ILE', 'HOH', 'HOH', 'HOH', 'HOH'): 1,
 ('ASP', 'HIS', 'HOH', 'HOH', 'HOH'): 1,
 ('CYS', 'GLU', 'HOH', 'HOH'): 1,
 ('HIS', 'ASP', 'GLU', 'HOH', 'HOH', 'HOH'): 1,
 ('HIS', 'LYS'): 1,
 ('ASN', 'GLN', 'HOH', 'HOH'): 1,
 ('ASP', 'ASP', 'ASN', 'HOH'): 1,
 ('MET', 'ASP', 'HOH', 'HOH', 'HOH'): 1,
 ('GLY', 'HIS', 'CYS', 'HIS'): 1,
 ('ASN', 'HIS', 'HIS', 'HIS', 'HOH', 'HOH'): 1,
 ('ASP', 'HIS', 'HIS', 'ASN', 'HOH', 'HOH'): 1,
 ('ASP', 'ASN', 'HIS', 'HOH', 'HOH'): 1,
 ('HIS', 'HIS', 'ASP', 'HOH'): 1,
 ('SER', 'HIS'): 1,
 ('HIS', 'ASP', 'HIS', 'HOH', 'AKG'): 1,
 ('MET', 'HOH', 'HOH', 'HOH'): 1,
 ('ASN', 'ASN'): 1,
 ('DG', 'HOH', 'HOH', 'HOH', 'HOH'): 1,
 ('HIS', 'HIS', 'HIS', 'GLU', 'HOH', 'HOH'): 1,
 ('ARG', 'HOH'): 1,
 ('ASP', 'HIS', 'TRS', 'HOH'): 1,
 ('CSD', 'CSO', 'HOH', 'HOH', 'HOH'): 1,
 ('CSD', 'CSO', 'HOH', 'HOH'): 1,
 ('ASP', 'DTP', 'ASP', 'DTP'): 1,
 ('GLU', 'LYS'): 1,
 ('ASN', 'TRP', 'HIS', 'ASP'): 1,
 ('HIS', 'ARG'): 1,
 ('CYS', 'HIS', 'HIS', 'HOH', 'HOH', 'GLU', 'HIS', 'HOH', 'HOH'): 1,
 ('HIS', 'ASP', 'HIS', 'ASP', 'HOH', 'HOH'): 1,
 ('SER', 'GLN', 'HIS'): 1,
 ('HIS', 'ASP', 'HIS', 'HOH'): 1,
 ('HIS', 'ASP', 'GLU'): 1,
 ('HIS', 'HIS', 'ASN', 'HIS', 'GLU'): 1,
 ('HIS', 'HIS', 'GLU', 'IMD', 'HOH'): 1,
 ('ASP', 'HIS', 'HIS', 'ACY', 'HOH'): 1,
 ('ILE', 'LEU', 'ILE'): 1,
 ('HIS', 'LYS', 'SIN', 'HOH', 'HOH', 'HOH'): 1,
 ('CYS', 'HIS', 'GLU', 'HOH'): 1,
 ('HIS', 'ASP', 'ASP', 'ASP', 'ABH', 'HIS', 'ASP', 'ASP', 'ABH'): 1,
 ('GLU',
  'HIS',
  'SOR',
  'DOD',
  'HIS',
  'ASP',
  'ASP',
  'DOD',
  'GLU',
  'ASP',
  'ASP',
  'SOR'): 1,
 ('HIS', 'HIS', 'KCX', 'HIS', 'HIS', 'ASP', 'KCX'): 1,
 ('HIS', 'HIS', 'IMD'): 1,
 ('GLY', 'MET', 'HIS'): 1,
 ('GLY', 'HIS', 'GLU', 'HOH', 'HOH', 'HOH'): 1,
 ('HIS', 'HIS', 'ASN', 'HIS', 'HIS', 'HIS'): 1,
 ('SER', 'HIS', 'TRS', 'HOH'): 1,
 ('SER', 'HIS', 'HOH', 'HOH'): 1,
 ('MET', 'HIS', 'HOH'): 1,
 ('HIS', 'HOH', 'HOH', 'HOH', 'HOH', 'HOH', 'HOH', 'HOH'): 1,
 ('GLU', 'GLN', 'UNL', 'HOH', 'HOH'): 1,
 ('GLN', 'HIS'): 1,
 ('GLY', 'HIS', 'HIS', 'GLN', 'HOH'): 1,
 ('GLY', 'HIS', 'HIS', 'HOH', 'HOH'): 1,
 ('SER', 'SER', 'THR', 'ASP', 'HOH', 'HOH'): 1,
 ('ASP', 'TRS', 'HOH'): 1,
 ('ASP', 'ASP', 'THR', 'ASP', 'MBY', 'HOH'): 1,
 ('GLU', 'HIS', 'ASP'): 1,
 ('HIS', 'CYS', 'HOH'): 1,
 ('ACT', 'ACT', 'HOH', 'HOH', 'HOH'): 1,
 ('GLU', 'ACT', 'HOH'): 1,
 ('ACT', 'ACT', 'HOH', 'HOH'): 1,
 ('PRO', 'ASN', 'HOH'): 1,
 ('HIS', 'HIS', 'GLU'): 1,
 ('HIS', 'GLN', 'HOH', 'HOH', 'HOH', 'HOH'): 1,
 ('HIS', 'SER'): 1,
 ('LEU', 'LCP'): 1,
 ('GLU', 'ASN', 'GLU', 'NAG'): 1,
 ('GLN', 'HIS', 'HIS', 'HOH', 'HOH'): 1,
 ('HIS', 'HIS', 'GLU', 'TRS'): 1,
 ('LEU', 'ASN', 'ASP', 'PHE', 'ASN', 'ASP', 'PHE', 'HOH'): 1,
 ('HIS', 'HIS', 'HIS', 'HIS'): 1,
 ('ASP', 'SER', 'HIS', 'CIT'): 1,
 ('HIS', 'ALA', 'HOH', 'HOH', 'HOH'): 1,
 ('GLY', 'ALA', 'MET'): 1,
 ('HIS', 'ASP', 'HIS', 'DGR', 'HOH'): 1,
 ('GLU', 'HIS', 'ACT'): 1,
 ('ALA', 'HIS', 'HOH'): 1,
 ('THR', 'SER', 'CYS', 'HIS'): 1,
 ('GLU', 'HOH', 'HOH', 'HOH', 'GLU'): 1,
 ('HIS',
  'HIS',
  'ASP',
  'HOH',
  'HOH',
  'HOH',
  'HIS',
  'HIS',
  'HIS',
  'HOH',
  'HOH'): 1,
 ('ASP', 'HIS', 'ASP'): 1,
 ('HIS', 'EY'): 1,
 ('GLU', 'HIS', 'HIS'): 1,
 ('GLY', 'HIS'): 1,
 ('GLU', 'HIS', 'GOL'): 1,
 ('HIS', 'HIS', 'ASP', 'ASP', 'HIS', 'HIS', 'HIS'): 1,
 ('HIS', 'IMD', 'IMD', 'IMD', 'IMD'): 1,
 ('LEU', 'ASP', 'HOH', 'HOH', 'HOH', 'HOH'): 1,
 ('ASP', 'HIS', 'HOH', 'HOH'): 1,
 ('HIS', 'ASP', 'THR'): 1,
 ('HIS', 'K', 'K', 'GOL', 'HOH'): 1,
 ('HIS', 'HIS', 'HIS', 'HIS', 'HOH'): 1,
 ('HIS', 'SCN', 'SCN'): 1,
 ('HIS', 'HIS', 'LMR', 'HOH', 'HOH'): 1,
 ('HIS', 'ASP', 'HIS', 'AKG'): 1,
 ('ASN', 'ASP', 'HOH'): 1,
 ('ASN', 'HIS'): 1,
 ('ASN', 'GLN', 'HIS', 'GLU'): 1,
 ('HIS', 'HIS', 'CL', 'HOH'): 1,
 ('GLY', 'HIS', 'HIS', 'GLN', 'HIS'): 1,
 ('HIS',
  'HIS',
  'HIS',
  'ASP',
  'HOH',
  'HOH',
  'HIS',
  'ASP',
  'HIS',
  'HOH',
  'HOH'): 1,
 ('GLN', 'HIS', 'GLU', 'HOH', 'HOH', 'HOH'): 1,
 ('THR',): 1,
 ('CYS',
  'CYS',
  'FES',
  'HIS',
  'FES',
  'CYS',
  'FES',
  'HIS',
  'FES',
  'HIS',
  'HOH',
  'HOH',
  'HOH',
  'HOH'): 1,
 ('HIS', 'ASP', 'HIS', 'SIN', 'HOH'): 1,
 ('CYS', 'CYS', 'HIS', 'HIS'): 1,
 ('HIS', 'LYS', 'HIS', 'HOH', 'HOH'): 1,
 ('GLU', 'GLU', 'ASN', 'ASN', 'THR', 'HOH'): 1,
 ('VAL', 'HOH'): 1,
 ('MET', 'HOH'): 1,
 ('GLU',
  'GLU',
  'ASP',
  'GLN',
  'ASP',
  'ASP',
  'HIS',
  'ASP',
  'ASP',
  'ASN',
  'ASP',
  'HOH'): 1,
 ('PRO',): 1,
 ('GLY', 'IMD'): 1,
 ('HIS', 'ACT', 'HOH'): 1,
 ('HIS', 'ASP', 'CL'): 1,
 ('GLU', 'ASP', 'HIS', 'GLU', 'HOH'): 1,
 ('GLU', 'ASP', 'GOA', 'HOH', 'HOH'): 1,
 ('ASN', 'HIS', 'HOH', 'HOH', 'HOH', 'HOH'): 1,
 ('HIS', 'HIS', 'HOH', 'HOH', 'HOH', 'HOH', 'HOH'): 1,
 ('ASP', 'ASN', 'HIS', 'HIS', 'HIS', 'ASP', 'HOH'): 1,
 ('HIS', 'ASP', 'HOH', 'HOH', 'ASP', 'HOH', 'HOH', 'HOH', 'HOH'): 1,
 ('HIS', 'HIS', 'ASP', 'HOH', 'HOH', 'HOH'): 1,
 ('HIS', 'HIS', 'AKG', 'HOH', 'HOH'): 1,
 ('GLU', 'HOH', 'HOH', 'HOH', 'HOH'): 1,
 ('GLU', 'HIS', 'HIS', 'HOH', 'ASP', 'GLU'): 1,
 ('SER', 'CYS'): 1,
 ('HIS', 'ASP', 'HIS', 'HIS'): 1,
 ('HIS', 'HIS', 'HIS', 'HIS', 'HIS', 'HIS'): 1,
 ('MET', 'HIS', 'HOH', 'HOH', 'HOH'): 1,
 ('DG', 'HIS', 'ASP'): 1,
 ('DG', 'LYS'): 1,
 ('ASP', 'ASP', 'HOH', 'HOH'): 1,
 ('GLU',
  'GLU',
  'GLU',
  'HOH',
  'HOH',
  'GLU',
  'GLU',
  'HOH',
  'HOH',
  'HOH',
  'HOH',
  'HOH',
  'HOH',
  'HOH',
  'HOH',
  'HOH',
  'HOH',
  'HOH'): 1}

In [64]:
pd.read_csv('metalpdb_report_eu.tsv', sep = '\t')

,Site Id,Metals,Metals Info,Ligands
0,1jhw_1,Eu;,EU3_402(A)_EU;,"ASP_279(A), ASP_280(A), GLU_304(A);"
1,2p1x_1,Eu;,EU3_501(A)_EU;,"ASP_29(A), ASP_31(A) HOH_584(A), HOH_611(A), H..."
2,2p1x_2,Eu;,EU3_504(A)_EU;,"GLU_19(A), ASP_23(A) HOH_608(A), HOH_609(A);"
3,2p1x_3,Eu;,EU3_502(A)_EU;,"ASP_3(A), GLU_55(A) HOH_541(A), HOH_610(A);"
4,2p1x_4,Eu;,EU3_503(A)_EU;,ASP_76(A);
5,2p1x_5,Eu;,EU3_500(A)_EU;,"GLU_33(A) HOH_537(A), HOH_539(A), HOH_540(A), ..."
6,2pc2_1,Eu;,EU_201(A)_EU;,"PDC_302(A), PDC_303(A), PDC_304(A);"
7,2pc2_2,Eu;,EU_203(A)_EU;,"PDC_502(A), PDC_503(A), PDC_504(A);"
8,2pc2_3,Eu;,EU_202(A)_EU;,"PDC_402(A), PDC_404(A);"
9,2pc2_4,Eu;,EU_205(A)_EU;,PDC_702(A);
10,2pc2_5,Eu;,EU_204(A)_EU;,"PDC_602(A), PDC_603(A), PDC_604(A);"
11,2pe7_1,Eu;,EU_601(A)_EU;,"PDC_602(A), PDC_603(A), PDC_604(A);"
12,1qsl_1,Eu;,EU_1(A)_EU;,"ASP_355(A), GLU_357(A), ASP_501(A), DC_1008(B)..."
13,3py9_1,Eu;,EU_305(A)_EU;,"ASP_99(A), ASP_130(A), ASN_132(A);"
14,3py9_2,Eu;,EU_303(A)_EU;,ASP_230(A);
15,3py9_3,Eu;,EU_302(A)_EU;,GLU_44(A);
16,3py9_4,Eu;,EU_301(A)_EU;,GLU_8(A);
17,2yat_1,Eu;,EU_1550(A)_EU;,EEU_1549(A);
18,1wc4_1,Eu;,EU3_2100(A)_EU;,"ASP_1017(A), ILE_1018(A), ASP_1061(A) APC_1500..."
19,3lgr_1,Eu;,EU_201(A)_EU;,"PDC_302(A), PDC_303(A), PDC_304(A);"
20,3lgr_2,Eu;,EU_203(A)_EU;,"HOH_331(A), HOH_544(A);"
21,3mvo_2,Eu;,EU3_503(A)_EU;,"GLU_402(A), ASN_406(A), ILE_440(A);"
22,2fby_1,Eu;Eu,EU3_237(A)_EU;EU3_238(A)_EU;,"ASP_82(A), GLU_84(A), ASP_216(A) HOH_346(A);AS..."
23,3tf6_1,Eu;,EU_206(C)_EU;,DBH_216(C);
24,3tor_1,Fe;Fe;Eu;,HEC_7(C)_FE;HEC_7(B)_FE;EU_479(B)_EU;EU_480(B)...,"HIS_275(C), HIS_318(C) HEC_7(C);HIS_275(B), HI..."
25,3tor_3,Eu;Fe;,EU_2(C)_EU;HEC_5(C)_FE;HEC_6(C)_FE;,"PRO_91(C) HEC_5(C), HEC_6(C), HOH_645(C), HOH_..."
26,3tor_7,Eu;,EU_479(C)_EU;,"GLU_190(C), ASP_457(A) HOH_521(C), HOH_622(C),..."
27,3ojo_1,Eu;,EU_501(A)_EU;,"PDC_502(A), PDC_503(A), PDC_504(A);"
28,4eni_1,Eu;,EU_201(A)_EU;,"ASP_101(A) HOH_331(A), HOH_363(A), HOH_420(A);"
29,4eni_3,Eu;,EU_202(A)_EU;,"ASN_46(A), ASP_52(A) HOH_362(A), HOH_374(A);"
30,4bap_1,Eu;,EU3_1144(A)_EU;,"DCJ_1130(A), DCJ_1131(A), DCJ_1132(A);"
31,4bar_1,Eu;,EU3_1211(A)_EU;,"IKX_1208(A), IKX_1209(A), IKX_1210(A);"
32,4bad_4,Eu;,EU3_1143(A)_EU;,"HM6_1142(A), HOH_2156(A);"
33,4lp1_2,Eu;,EU3_204(B)_EU;,GLN_52(B);
34,4lp1_4,Eu;,EU3_204(A)_EU;,GLU_5(A);
35,4lp1_7,Eu;,EU3_203(A)_EU;,"ASP_31(A), GLN_32(A) HOH_303(A);"
36,4lp1_8,Eu;,EU3_201(B)_EU;,"ASP_102(B), THR_104(B) HOH_305(B);"
37,4lp1_9,Eu;,EU3_201(A)_EU;,GLU_22(A) HOH_311(A);

General function

In [96]:
def make_ligand_count_dict(metal_tsv_string):
    metal_df = pd.read_csv(metal_tsv_string, sep = '\t')
    
    all_ligand_list = []
    for ligands in metal_df['Ligands']:
        temp = ligands.split(' ')
        all_ligand_list.append(temp)
    
    removed_extra_list = []
    for i in all_ligand_list:
        new_list = []
        for j in i:
            new_list.extend(re.findall(r'([A-Z]+)\_.*', j))
        removed_extra_list.append(new_list)
          
    key_list = [tuple(k) for k in removed_extra_list]
    ligand_dict = {}
    for key in key_list:
        if key not in ligand_dict:
            ligand_dict[key] = 1
        else:
            ligand_dict[key] += 1

    return {lig: count for lig, count in sorted(ligand_dict.items(), key=lambda item: -item[1])}

In [97]:
make_ligand_count_dict('metalpdb_report.tsv')

{('HIS',): 70,
 ('HIS', 'HIS'): 52,
 ('HIS', 'HOH'): 44,
 ('HIS', 'HOH', 'HOH', 'HOH'): 34,
 ('HIS', 'HOH', 'HOH'): 28,
 ('ASP',): 21,
 ('HIS', 'HOH', 'HOH', 'HOH', 'HOH'): 19,
 ('HOH',): 13,
 ('HOH', 'HOH'): 12,
 ('GLY', 'SER', 'HIS'): 11,
 ('GLU',): 11,
 ('HIS', 'HIS', 'HOH'): 11,
 ('HIS', 'ASP'): 10,
 ('HIS', 'HOH', 'HOH', 'HOH', 'HOH', 'HOH'): 10,
 ('HIS', 'HIS', 'HIS'): 10,
 ('ASP', 'HOH'): 8,
 ('HIS', 'HIS', 'HOH', 'HOH'): 7,
 ('HIS', 'HIS', 'HIS', 'HOH', 'HOH', 'HOH'): 7,
 ('HIS', 'HIS', 'HOH', 'HOH', 'HOH', 'HOH'): 7,
 ('GLU', 'HOH'): 7,
 ('HIS', 'HIS', 'HOH', 'HOH', 'HOH'): 6,
 ('ASP', 'HOH', 'HOH', 'HOH'): 6,
 ('HIS', 'GLU', 'HOH', 'HOH', 'HOH'): 5,
 ('HOH', 'HOH', 'HOH', 'HOH'): 5,
 ('HIS', 'ASP', 'HOH', 'HOH'): 5,
 ('GLU', 'HOH', 'HOH'): 5,
 ('HIS', 'HIS', 'HIS', 'HOH', 'HOH'): 5,
 ('GLU', 'HIS'): 5,
 ('HIS', 'GLU'): 5,
 ('ASP', 'ASP', 'HIS', 'HOH'): 4,
 ('HIS', 'GLU', 'HOH'): 4,
 ('GLU', 'HOH', 'HOH', 'HOH'): 4,
 ('HOH', 'HOH', 'HOH'): 4,
 ('ASP', 'HOH', 'HOH', 'HOH', 'HOH'): 4,
 ('ASP', 'HOH', 'HOH', 'HOH', 'HOH', 'HOH'): 4,
 ('CYS', 'CYS', 'CYS', 'CYS', 'CYS', 'GLY', 'CYS'): 4,
 ('ASP', 'HIS'): 4,
 ('ASP', 'GLU'): 4,
 ('HIS', 'GLU', 'HIS', 'GLU', 'HOH', 'HOH'): 3,
 ('ASP', 'HIS', 'HOH'): 3,
 ('GLU', 'GLU', 'HOH'): 3,
 ('HIS', 'GLU', 'HIS'): 3,
 (): 3,
 ('HIS', 'HIS', 'GLU', 'HOH'): 3,
 ('HIS', 'HIS', 'HIS', 'ASP'): 3,
 ('HIS', 'GLU', 'HIS', 'HOH', 'HOH'): 3,
 ('CYS',): 3,
 ('HIS', 'HIS', 'HIS', 'HOH'): 3,
 ('HOH', 'PXX'): 3,
 ('SER', 'HOH', 'HOH', 'HOH'): 3,
 ('LYS',): 3,
 ('HIS', 'ASP', 'HOH', 'HOH', 'HOH'): 3,
 ('HIS', 'BTB'): 3,
 ('ALA', 'HOH'): 2,
 ('HIS', 'HIS', 'GLU', 'HIS', 'UNL'): 2,
 ('HIS', 'ASP', 'HIS', 'HOH', 'HOH', 'HOH'): 2,
 ('HIS', 'ASP', 'GLU', 'HOH', 'HOH'): 2,
 ('HIS', 'HIS', 'HIS', 'CYS'): 2,
 ('HIS', 'CL', 'CL'): 2,
 ('GLU', 'ASP'): 2,
 ('GLU', 'GLU', 'HOH', 'HOH'): 2,
 ('HIS', 'LYS', 'HOH', 'HOH', 'HOH'): 2,
 ('ASP', 'ASP', 'HOH'): 2,
 ('ASN',): 2,
 ('HIS', 'GLU', 'HIS', 'GLU', 'HOH'): 2,
 ('HIS', 'HIS', 'GLU', 'HIS', 'HOH'): 2,
 ('CYS', 'CYS', 'CYS', 'CYS'): 2,
 ('GLY', 'HIS', 'HIS', 'HOH'): 2,
 ('HIS', 'HIS', 'GLU', 'HOH', 'HOH', 'HOH'): 2,
 ('ASP', 'HIS', 'HIS', 'HOH'): 2,
 ('HOH', 'HOH', 'HOH', 'HOH', 'HOH'): 2,
 ('GLU', 'GLU'): 2,
 ('HIS', 'HIS', 'HIS', 'HIS', 'IMD', 'HOH'): 2,
 ('GLY', 'HIS', 'HOH', 'HOH'): 2,
 ('GLU', 'GLU', 'HOH', 'HOH', 'HOH', 'HOH'): 2,
 ('HIS', 'HIS', 'ASP', 'ASP'): 2,
 ('HIS', 'ASP', 'HIS', 'OGA', 'HOH'): 2,
 ('HIS', 'LYS', 'HIS', 'HOH'): 2,
 ('GLU', 'ASP', 'HOH'): 2,
 ('HIS', 'GLU', 'HIS', 'HOH'): 2,
 ('HIS', 'HIS', 'GLU', 'HOH', 'HOH'): 2,
 ('HIS', 'ASP', 'HIS', 'HOH', 'HOH'): 2,
 ('HIS', 'CYS'): 2,
 ('GLU', 'HIS', 'HIS', 'HOH', 'HOH', 'HOH'): 2,
 ('CYS', 'HOH'): 2,
 ('HIS', 'HIS', 'HIS', 'UNL'): 2,
 ('MET', 'HOH', 'HOH', 'HOH', 'HOH'): 2,
 ('ASP',
  'HIS',
  'ASP',
  'HIS',
  'HOH',
  'HOH',
  'HIS',
  'HIS',
  'ASP',
  'HOH',
  'HOH'): 2,
 ('HIS', 'HIS', 'HIS', 'HIS', 'HIS'): 2,
 ('GLU', 'HIS', 'HOH', 'HOH', 'HOH'): 2,
 ('HIS', 'ASP', 'HOH', 'HOH', 'HOH', 'HOH'): 2,
 ('CYS', 'CYS'): 2,
 ('CYS', 'HOH', 'HOH'): 2,
 ('HIS', 'HIS', 'CL'): 2,
 ('MET', 'HIS', 'HIS'): 2,
 ('GLU', 'HIS', 'HIS', 'HOH'): 2,
 ('GLU', 'HIS', 'HIS', 'HOH', 'HOH'): 2,
 ('ASP', 'HIS', 'HIS', 'ASP', 'HOH'): 1,
 ('ASN', 'HIS', 'GLU', 'FMN', 'HOH', 'HOH'): 1,
 ('HIS', 'GDP', 'HOH', 'HOH', 'HOH', 'HOH'): 1,
 ('HIS', 'TRS', 'TRS'): 1,
 ('HIS', 'HIS', 'KCX', 'HOH', 'HOH', 'HOH'): 1,
 ('TRP', 'HOH', 'HOH', 'HOH', 'HOH'): 1,
 ('GLN', 'COM'): 1,
 ('GLY', 'HOH', 'HOH', 'HOH'): 1,
 ('ALA', 'HIS', 'ASP', 'HOH'): 1,
 ('HIS', 'HIS', 'HIS', 'TYR', 'HOH', 'HOH'): 1,
 ('ALA', 'ASP', 'HIS'): 1,
 ('HIS', 'CL', 'HOH', 'CL', 'HOH'): 1,
 ('ASP', 'ASP', 'ASP', 'HOH'): 1,
 ('CYS', 'CYS', 'HIS', 'CL'): 1,
 ('HIS', 'HNI'): 1,
 ('LYS', 'HOH', 'HOH', 'HOH'): 1,
 ('ASN', 'HOH', 'HOH', 'HOH', 'HOH'): 1,
 ('HIS', 'GLU', 'HIS', 'HIS', 'HOH'): 1,
 ('ALA', 'ARG'): 1,
 ('ARG', 'HIS', 'GLU', 'CL'): 1,
 ('LYS', 'HOH'): 1,
 ('HIS', 'HIS', 'HIS', 'ASP', 'HOH', 'HOH'): 1,
 ('CYS', 'HIS', 'HIS', 'HOH'): 1,
 ('ASP', 'ASP', 'GLU', 'ASP', 'HIS', 'GLU', 'GLU', 'HIS', 'CL', 'HOH'): 1,
 ('TCN',): 1,
 ('HIS', 'HIS', 'TRS', 'HOH'): 1,
 ('HIS', 'ASP', 'HOH'): 1,
 ('ALA', 'ASP'): 1,
 ('HIS', 'GLU', 'HOH', 'HOH', 'HOH', 'HOH'): 1,
 ('ALA', 'HOH', 'HOH', 'HOH'): 1,
 ('HIS', 'HOH', 'HOH', 'HOH', 'HOH', 'HOH', 'HOH'): 1,
 ('ASP', 'ASP', 'ASP', 'SEP', 'HOH'): 1,
 ('HIS', 'CL', 'HOH', 'HOH', 'HOH', 'HOH'): 1,
 ('HIS', 'CL', 'CL', 'CL', 'CL', 'CL'): 1,
 ('GLU', 'ASP', 'LEU', 'VAL'): 1,
 ('SER', 'SER', 'THR', 'ASN', 'HOH', 'HOH'): 1,
 ('HIS', 'HIS', 'GLU', 'ASP', 'HIS', 'HIS'): 1,
 ('HIS', 'ASP', 'HIS', 'IMD', 'IMD'): 1,
 ('HIS', 'ACO', 'ACO'): 1,
 ('ASP', 'VAL', 'ASP', 'PRO', 'GLU', 'HOH'): 1,
 ('ASP', 'GLU', 'ALA', 'ASN', 'HOH'): 1,
 ('GLU', 'HIS', 'ASP', 'GLO', 'HOH', 'GLU', 'ASP', 'ASP', 'GLO'): 1,
 ('GLU', 'HIS', 'CL'): 1,
 ('GLU', 'HIS', 'ASP', 'ASP', 'HOH', 'GLU', 'ASP', 'ASP'): 1,
 ('HIS', 'HIS', 'GLU', 'HIS', 'MET'): 1,
 ('HIS', 'GLU', 'GLU', 'HOH', 'HOH', 'HOH'): 1,
 ('EDO', 'HOH', 'HOH'): 1,
 ('ASP', 'HIS', 'GLU', 'GLU', 'ASP', 'ASP', 'GLU'): 1,
 ('ASP', 'ASP', 'HOH', 'HOH', 'HOH'): 1,
 ('HIS', 'LYS', 'HOH', 'HOH', 'HOH', 'HOH'): 1,
 ('TRP', 'TRS'): 1,
 ('TRP', 'PHE', 'TRS'): 1,
 ('TRP', 'PHE', 'TRS', 'HOH'): 1,
 ('ASP', 'LYS', 'HIS', 'HOH', 'HOH', 'HOH'): 1,
 ('HIS', 'HIS', 'HIS', 'CYS', 'SER', 'HIS'): 1,
 ('ASP', 'HIS', 'HOH', 'HOH', 'HOH', 'HOH'): 1,
 ('GLY',): 1,
 ('HIS', 'HIS', 'HIS', 'IMD', 'IMD'): 1,
 ('HIS', 'HOH', 'HOH', 'HOH', 'HOH', 'HOH', 'HOH', 'HOH', 'HOH', 'HOH'): 1,
 ('MET', 'VAL', 'ASP', 'HOH', 'HOH'): 1,
 ('HIS', 'LYS', 'HOH', 'HOH'): 1,
 ('HIS', 'GLU', 'ASP', 'HOH'): 1,
 ('HIS', 'HQI'): 1,
 ('HIS', 'HIS', 'HIS', 'EDO', 'MLI'): 1,
 ('SER',): 1,
 ('HIS', 'HIS', 'GLU', 'HIS', 'HOH', 'HOH'): 1,
 ('HIS', 'HIS', 'HIS', 'CIT'): 1,
 ('GLU', 'GLU', 'NOS'): 1,
 ('GLU', 'HIS', 'LYS', 'HOH', 'HOH'): 1,
 ('HIS', 'HIS', 'HIS', 'FMT', 'HOH'): 1,
 ('LYS', 'HIS', 'HOH', 'CL'): 1,
 ('ASN', 'HIS', 'HIS', 'HOH', 'HIS', 'ASP', 'HIS', 'HOH'): 1,
 ('MET', 'ASP', 'GLU', 'HIS', 'HOH'): 1,
 ('THR', 'GLN', 'HIS'): 1,
 ('CYS', 'CSO', 'NFC', 'CYS', 'CSO', 'CSO', 'NFC'): 1,
 ('HIS', 'HOH', 'HOH', 'GOL'): 1,
 ('GLU', 'HIS', 'ASP', 'ASP', 'HOH'): 1,
 ('HIS', 'CYS', 'NFS', 'NFS', 'HOH', 'NFS', 'NFS'): 1,
 ('CYS', 'NFS', 'NFS', 'HOH', 'NFS', 'NFS'): 1,
 ('GLU',
  'ASP',
  'GLU',
  'ASP',
  'HOH',
  'ASN',
  'ASP',
  'HOH',
  'HOH',
  'GLU',
  'GLU',
  'HOH',
  'HOH',
  'GLU',
  'ASP',
  'HOH',
  'HOH'): 1,
 ('GLY', 'HIS', 'HOH'): 1,
 ('GLU',
  'ASP',
  'ASP',
  'HIS',
  'HOH',
  'HOH',
  'TYR',
  'ASN',
  'ASP',
  'HOH',
  'HOH'): 1,
 ('ARG', 'HIS'): 1,
 ('HIS', 'CYS', 'CYS'): 1,
 ('ASP', 'ASP', 'HIS', 'HOH', 'HOH'): 1,
 ('MET', 'HOH', 'HOH'): 1,
 ('HIS', 'GLN', 'GLU'): 1,
 ('ARG',): 1,
 ('ASP', 'GLY', 'HIS', 'HOH', 'HOH'): 1,
 ('MET', 'HIS'): 1,
 ('BTN',): 1,
 ('ASP', 'HIS', 'HIS', 'HIS', 'UNL'): 1,
 ('CGU', 'CGU', 'CL', 'HOH', 'CL', 'CL'): 1,
 ('GLY', 'HIS', 'HOH', 'HOH', 'HOH'): 1,
 ('GLU', 'ASP', 'GLU', 'HOH'): 1,
 ('CYS', 'GLY', 'CYS', 'CYS', 'HOH'): 1,
 ('HIS', 'HIS', 'HIS', 'IMD'): 1,
 ('GLU', 'ASP', 'ASP', 'HOH', 'HOH', 'ASP', 'ASP', 'CYS', 'ASP', 'HOH'): 1,
 ('HIS', 'HIS', 'ASP', 'TRS'): 1,
 ('HIS', 'TRS', 'HOH', 'HOH'): 1,
 ('HIS', 'GLU', 'HOH', 'HOH'): 1,
 ('HIS', 'GLU', 'ASP', 'ASP'): 1,
 ('HIS', 'HIS', 'ASP', 'ASP', 'HOH', 'HOH'): 1,
 ('COM',): 1,
 ('VAL', 'ASP', 'HOH', 'HOH'): 1,
 ('ASP', 'GLN', 'HIS', 'HOH'): 1,
 ('HIS', 'HIS', 'TYR', 'HOH', 'HOH'): 1,
 ('HIS', 'IMD'): 1,
 ('GLU', 'HIS', 'HOH', 'HOH', 'HOH', 'HOH'): 1,
 ('HIS', 'HIS', 'CYS'): 1,
 ('HIS', 'CTC', 'HOH', 'HOH', 'HOH'): 1,
 ('CYS', 'HIS', 'IMD', 'IMD'): 1,
 ('ASP', 'HIS', 'HIS'): 1,
 ('HIS', 'HIS', 'CYS', 'HOH'): 1,
 ('ASP', 'GLU', 'GLU', 'HOH', 'HOH', 'ASP', 'PHE', 'GLN', 'GLU'): 1,
 ('HIS', 'HIS', 'ACT', 'HOH'): 1,
 ('ASP', 'ASP'): 1,
 ('ARG', 'HIS', 'ASP', 'HOH'): 1,
 ('HIS', 'COA'): 1,
 ('ILE', 'HOH', 'HOH', 'HOH', 'HOH'): 1,
 ('ASP', 'HIS', 'HOH', 'HOH', 'HOH'): 1,
 ('CYS', 'GLU', 'HOH', 'HOH'): 1,
 ('HIS', 'ASP', 'GLU', 'HOH', 'HOH', 'HOH'): 1,
 ('HIS', 'LYS'): 1,
 ('ASN', 'GLN', 'HOH', 'HOH'): 1,
 ('ASP', 'ASP', 'ASN', 'HOH'): 1,
 ('MET', 'ASP', 'HOH', 'HOH', 'HOH'): 1,
 ('GLY', 'HIS', 'CYS', 'HIS'): 1,
 ('ASN', 'HIS', 'HIS', 'HIS', 'HOH', 'HOH'): 1,
 ('ASP', 'HIS', 'HIS', 'ASN', 'HOH', 'HOH'): 1,
 ('ASP', 'ASN', 'HIS', 'HOH', 'HOH'): 1,
 ('HIS', 'HIS', 'ASP', 'HOH'): 1,
 ('SER', 'HIS'): 1,
 ('HIS', 'ASP', 'HIS', 'HOH', 'AKG'): 1,
 ('MET', 'HOH', 'HOH', 'HOH'): 1,
 ('ASN', 'ASN'): 1,
 ('DG', 'HOH', 'HOH', 'HOH', 'HOH'): 1,
 ('HIS', 'HIS', 'HIS', 'GLU', 'HOH', 'HOH'): 1,
 ('ARG', 'HOH'): 1,
 ('ASP', 'HIS', 'TRS', 'HOH'): 1,
 ('CSD', 'CSO', 'HOH', 'HOH', 'HOH'): 1,
 ('CSD', 'CSO', 'HOH', 'HOH'): 1,
 ('ASP', 'DTP', 'ASP', 'DTP'): 1,
 ('GLU', 'LYS'): 1,
 ('ASN', 'TRP', 'HIS', 'ASP'): 1,
 ('HIS', 'ARG'): 1,
 ('CYS', 'HIS', 'HIS', 'HOH', 'HOH', 'GLU', 'HIS', 'HOH', 'HOH'): 1,
 ('HIS', 'ASP', 'HIS', 'ASP', 'HOH', 'HOH'): 1,
 ('SER', 'GLN', 'HIS'): 1,
 ('HIS', 'ASP', 'HIS', 'HOH'): 1,
 ('HIS', 'ASP', 'GLU'): 1,
 ('HIS', 'HIS', 'ASN', 'HIS', 'GLU'): 1,
 ('HIS', 'HIS', 'GLU', 'IMD', 'HOH'): 1,
 ('ASP', 'HIS', 'HIS', 'ACY', 'HOH'): 1,
 ('ILE', 'LEU', 'ILE'): 1,
 ('HIS', 'LYS', 'SIN', 'HOH', 'HOH', 'HOH'): 1,
 ('CYS', 'HIS', 'GLU', 'HOH'): 1,
 ('HIS', 'ASP', 'ASP', 'ASP', 'ABH', 'HIS', 'ASP', 'ASP', 'ABH'): 1,
 ('GLU',
  'HIS',
  'SOR',
  'DOD',
  'HIS',
  'ASP',
  'ASP',
  'DOD',
  'GLU',
  'ASP',
  'ASP',
  'SOR'): 1,
 ('HIS', 'HIS', 'KCX', 'HIS', 'HIS', 'ASP', 'KCX'): 1,
 ('HIS', 'HIS', 'IMD'): 1,
 ('GLY', 'MET', 'HIS'): 1,
 ('GLY', 'HIS', 'GLU', 'HOH', 'HOH', 'HOH'): 1,
 ('HIS', 'HIS', 'ASN', 'HIS', 'HIS', 'HIS'): 1,
 ('SER', 'HIS', 'TRS', 'HOH'): 1,
 ('SER', 'HIS', 'HOH', 'HOH'): 1,
 ('MET', 'HIS', 'HOH'): 1,
 ('HIS', 'HOH', 'HOH', 'HOH', 'HOH', 'HOH', 'HOH', 'HOH'): 1,
 ('GLU', 'GLN', 'UNL', 'HOH', 'HOH'): 1,
 ('GLN', 'HIS'): 1,
 ('GLY', 'HIS', 'HIS', 'GLN', 'HOH'): 1,
 ('GLY', 'HIS', 'HIS', 'HOH', 'HOH'): 1,
 ('SER', 'SER', 'THR', 'ASP', 'HOH', 'HOH'): 1,
 ('ASP', 'TRS', 'HOH'): 1,
 ('ASP', 'ASP', 'THR', 'ASP', 'MBY', 'HOH'): 1,
 ('GLU', 'HIS', 'ASP'): 1,
 ('HIS', 'CYS', 'HOH'): 1,
 ('ACT', 'ACT', 'HOH', 'HOH', 'HOH'): 1,
 ('GLU', 'ACT', 'HOH'): 1,
 ('ACT', 'ACT', 'HOH', 'HOH'): 1,
 ('PRO', 'ASN', 'HOH'): 1,
 ('HIS', 'HIS', 'GLU'): 1,
 ('HIS', 'GLN', 'HOH', 'HOH', 'HOH', 'HOH'): 1,
 ('HIS', 'SER'): 1,
 ('LEU', 'LCP'): 1,
 ('GLU', 'ASN', 'GLU', 'NAG'): 1,
 ('GLN', 'HIS', 'HIS', 'HOH', 'HOH'): 1,
 ('HIS', 'HIS', 'GLU', 'TRS'): 1,
 ('LEU', 'ASN', 'ASP', 'PHE', 'ASN', 'ASP', 'PHE', 'HOH'): 1,
 ('HIS', 'HIS', 'HIS', 'HIS'): 1,
 ('ASP', 'SER', 'HIS', 'CIT'): 1,
 ('HIS', 'ALA', 'HOH', 'HOH', 'HOH'): 1,
 ('GLY', 'ALA', 'MET'): 1,
 ('HIS', 'ASP', 'HIS', 'DGR', 'HOH'): 1,
 ('GLU', 'HIS', 'ACT'): 1,
 ('ALA', 'HIS', 'HOH'): 1,
 ('THR', 'SER', 'CYS', 'HIS'): 1,
 ('GLU', 'HOH', 'HOH', 'HOH', 'GLU'): 1,
 ('HIS',
  'HIS',
  'ASP',
  'HOH',
  'HOH',
  'HOH',
  'HIS',
  'HIS',
  'HIS',
  'HOH',
  'HOH'): 1,
 ('ASP', 'HIS', 'ASP'): 1,
 ('HIS', 'EY'): 1,
 ('GLU', 'HIS', 'HIS'): 1,
 ('GLY', 'HIS'): 1,
 ('GLU', 'HIS', 'GOL'): 1,
 ('HIS', 'HIS', 'ASP', 'ASP', 'HIS', 'HIS', 'HIS'): 1,
 ('HIS', 'IMD', 'IMD', 'IMD', 'IMD'): 1,
 ('LEU', 'ASP', 'HOH', 'HOH', 'HOH', 'HOH'): 1,
 ('ASP', 'HIS', 'HOH', 'HOH'): 1,
 ('HIS', 'ASP', 'THR'): 1,
 ('HIS', 'K', 'K', 'GOL', 'HOH'): 1,
 ('HIS', 'HIS', 'HIS', 'HIS', 'HOH'): 1,
 ('HIS', 'SCN', 'SCN'): 1,
 ('HIS', 'HIS', 'LMR', 'HOH', 'HOH'): 1,
 ('HIS', 'ASP', 'HIS', 'AKG'): 1,
 ('ASN', 'ASP', 'HOH'): 1,
 ('ASN', 'HIS'): 1,
 ('ASN', 'GLN', 'HIS', 'GLU'): 1,
 ('HIS', 'HIS', 'CL', 'HOH'): 1,
 ('GLY', 'HIS', 'HIS', 'GLN', 'HIS'): 1,
 ('HIS',
  'HIS',
  'HIS',
  'ASP',
  'HOH',
  'HOH',
  'HIS',
  'ASP',
  'HIS',
  'HOH',
  'HOH'): 1,
 ('GLN', 'HIS', 'GLU', 'HOH', 'HOH', 'HOH'): 1,
 ('THR',): 1,
 ('CYS',
  'CYS',
  'FES',
  'HIS',
  'FES',
  'CYS',
  'FES',
  'HIS',
  'FES',
  'HIS',
  'HOH',
  'HOH',
  'HOH',
  'HOH'): 1,
 ('HIS', 'ASP', 'HIS', 'SIN', 'HOH'): 1,
 ('CYS', 'CYS', 'HIS', 'HIS'): 1,
 ('HIS', 'LYS', 'HIS', 'HOH', 'HOH'): 1,
 ('GLU', 'GLU', 'ASN', 'ASN', 'THR', 'HOH'): 1,
 ('VAL', 'HOH'): 1,
 ('MET', 'HOH'): 1,
 ('GLU',
  'GLU',
  'ASP',
  'GLN',
  'ASP',
  'ASP',
  'HIS',
  'ASP',
  'ASP',
  'ASN',
  'ASP',
  'HOH'): 1,
 ('PRO',): 1,
 ('GLY', 'IMD'): 1,
 ('HIS', 'ACT', 'HOH'): 1,
 ('HIS', 'ASP', 'CL'): 1,
 ('GLU', 'ASP', 'HIS', 'GLU', 'HOH'): 1,
 ('GLU', 'ASP', 'GOA', 'HOH', 'HOH'): 1,
 ('ASN', 'HIS', 'HOH', 'HOH', 'HOH', 'HOH'): 1,
 ('HIS', 'HIS', 'HOH', 'HOH', 'HOH', 'HOH', 'HOH'): 1,
 ('ASP', 'ASN', 'HIS', 'HIS', 'HIS', 'ASP', 'HOH'): 1,
 ('HIS', 'ASP', 'HOH', 'HOH', 'ASP', 'HOH', 'HOH', 'HOH', 'HOH'): 1,
 ('HIS', 'HIS', 'ASP', 'HOH', 'HOH', 'HOH'): 1,
 ('HIS', 'HIS', 'AKG', 'HOH', 'HOH'): 1,
 ('GLU', 'HOH', 'HOH', 'HOH', 'HOH'): 1,
 ('GLU', 'HIS', 'HIS', 'HOH', 'ASP', 'GLU'): 1,
 ('SER', 'CYS'): 1,
 ('HIS', 'ASP', 'HIS', 'HIS'): 1,
 ('HIS', 'HIS', 'HIS', 'HIS', 'HIS', 'HIS'): 1,
 ('MET', 'HIS', 'HOH', 'HOH', 'HOH'): 1,
 ('DG', 'HIS', 'ASP'): 1,
 ('DG', 'LYS'): 1,
 ('ASP', 'ASP', 'HOH', 'HOH'): 1,
 ('GLU',
  'GLU',
  'GLU',
  'HOH',
  'HOH',
  'GLU',
  'GLU',
  'HOH',
  'HOH',
  'HOH',
  'HOH',
  'HOH',
  'HOH',
  'HOH',
  'HOH',
  'HOH',
  'HOH',
  'HOH'): 1}

In [98]:
make_ligand_count_dict('metalpdb_report_eu.tsv')

{('PDC', 'PDC', 'PDC'): 6,
 ('GLU',): 3,
 ('ASP',): 2,
 ('ASP', 'ASP', 'GLU'): 1,
 ('ASP', 'ASP', 'HOH', 'HOH', 'HOH', 'HOH'): 1,
 ('GLU', 'ASP', 'HOH', 'HOH'): 1,
 ('ASP', 'GLU', 'HOH', 'HOH'): 1,
 ('GLU', 'HOH', 'HOH', 'HOH', 'HOH', 'HOH'): 1,
 ('PDC', 'PDC'): 1,
 ('PDC',): 1,
 ('ASP', 'GLU', 'ASP', 'DC', 'HOH'): 1,
 ('ASP', 'ASP', 'ASN'): 1,
 ('EEU',): 1,
 ('ASP', 'ILE', 'ASP', 'APC'): 1,
 ('HOH', 'HOH'): 1,
 ('GLU', 'ASN', 'ILE'): 1,
 ('ASP', 'GLU', 'ASP', 'HOH', 'HOH', 'HOH'): 1,
 ('DBH',): 1,
 ('HIS', 'HIS', 'HEC', 'HIS', 'HEC', 'HOH', 'HOH', 'HEC'): 1,
 ('PRO',
  'HEC',
  'HEC',
  'HOH',
  'HOH',
  'HOH',
  'HOH',
  'HOH',
  'HIS',
  'HEC',
  'HIS',
  'HEC'): 1,
 ('GLU', 'ASP', 'HOH', 'HOH', 'HOH', 'HOH', 'HOH'): 1,
 ('ASP', 'HOH', 'HOH', 'HOH'): 1,
 ('ASN', 'ASP', 'HOH', 'HOH'): 1,
 ('DCJ', 'DCJ', 'DCJ'): 1,
 ('IKX', 'IKX', 'IKX'): 1,
 ('HOH',): 1,
 ('GLN',): 1,
 ('ASP', 'GLN', 'HOH'): 1,
 ('ASP', 'THR', 'HOH'): 1,
 ('GLU', 'HOH'): 1}

In [99]:
make_ligand_count_dict('metalpdb_report_tb.tsv')

{('ASP',): 5,
 ('ASP', 'ASN', 'ASP', 'TRP', 'GLU', 'GLU'): 4,
 ('PDC', 'PDC'): 3,
 ('PDC', 'PDC', 'PDC'): 2,
 ('GLU', 'MT'): 2,
 ('HOH',): 2,
 ('TRP',): 1,
 ('HIS', 'ASP', 'GLU', 'CL', 'HOH', 'HOH', 'HOH'): 1,
 ('HIS', 'ASP', 'GLU', 'HOH', 'HOH', 'HOH', 'HOH'): 1,
 ('ASP', 'THR', 'GLU'): 1,
 ('ASN', 'HOH'): 1,
 ('PRO', 'ASP'): 1,
 ('ASP', 'ASN', 'ASP', 'ARG', 'GLU', 'HOH'): 1,
 ('ASP', 'ASN', 'ASP', 'PHE', 'GLU', 'HOH'): 1,
 ('BTB', 'HOH', 'HOH', 'HOH'): 1,
 ('ASP', 'HOH', 'HOH', 'HOH'): 1,
 ('ASP', 'ASP'): 1,
 ('GLU', 'GLU', 'HOH', 'HOH'): 1,
 ('ASP', 'ASP', 'HOH'): 1,
 ('GLU', 'GLU'): 1,
 ('GLU',): 1}