Importing important packages and modules.

In [2]:
!conda install -y biopython

Collecting package metadata (current_repodata.json): done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.10.3
  latest version: 22.9.0

Please update conda by running

    $ conda update -n base conda



# All requested packages already installed.

In [2]:
import pandas as pd
import numpy as np
import statistics
import os

from Bio import SeqIO

Collect names of all fasta files downloaded for Eu. Put them into a list.

In [3]:
filenames = []

for filename in os.listdir(os.getcwd() + '/eu_fasta_files'):
    with open(os.path.join(os.getcwd() + '/eu_fasta_files', filename)) as f:
        filenames.append(filename)

filenames

['1jhw_1_alignment.fasta',
 '1qsl_1_alignment.fasta',
 '1wc4_1_alignment.fasta',
 '2fby_1_alignment.fasta',
 '2p1x_1_alignment.fasta',
 '2p1x_2_alignment.fasta',
 '4lp1_9_alignment.fasta',
 '4lp1_7_alignment.fasta',
 '4lp1_4_alignment.fasta',
 '4lp1_2_alignment.fasta',
 '4bar_1_alignment.fasta',
 '4bap_1_alignment.fasta',
 '4bad_4_alignment.fasta',
 '3tor_3_alignment.fasta',
 '3tor_1_alignment.fasta',
 '3tf6_1_alignment.fasta',
 '3py9_1_alignment.fasta',
 '3ojo_1_alignment.fasta',
 '3mvo_2_alignment.fasta',
 '3lgr_1_alignment.fasta',
 '2yat_1_alignment.fasta',
 '2pe7_1_alignment.fasta',
 '2pc2_1_alignment.fasta',
 '2p1x_5_alignment.fasta']

Collect names of all site IDs.

In [4]:
code_list = ['1jhw_A', '1jhw_2', '1qsl_A', '2fby_1', '1wc4_A', '1wc4_2', '2fby_A', '1qsl_1', '2p1x_A', '4lp1_1', 
            '4lp1_3', '4lp1_6', '2pc2_A', '2pe7_A', '2yat_A', '3lgr_A', '3mvo_A', '3ojo_A', '3py9_A',
            '3tf6_C', '3tor_B', '3tor_C', '3tor_11', '3tor_18', '3tor_9', '4bad_A', '4bap_A', '4bar_A', '4lp1_B',
             '4lp1_A', '4lp1_6', '4lp1_10']

In [8]:
# Collect information about each sequence responding to the sites in the code_list above.
rec_dict = {}
for filename in filenames:
    rec_dict.update(SeqIO.to_dict(SeqIO.parse("eu_fasta_files/" + filename, "fasta")))

# To prepare making the dataframe, make a list of lists (inner list contains site and the sequence)
seq_info = []
for seq_rec in rec_dict.values():
    if seq_rec.id in code_list:
        seq_info.append([seq_rec.id, seq_rec.seq])

# Remove '-' characters and convert sequences to type string
for i in seq_info:
    i[1] = str(i[1].replace('-', ''))
    
seq_info

[['1jhw_A',
  'PFPGSVQDPGLHVWRVEKLKPVPVAQENQGVFFSGDSYLVLHNGPEEVSHLHLWIGQQSSRDEQGACAVLAVQLDDYLGGRPVQHREVQGNESDLFMSYFPRGLKYQEGGVESGFKHVVPNEVVVQRLYQVKGAKNIRATERALNWDSFNTGDCFILDLGQNIFAWCGGKSNILERNKARDLALAIRDSERQGKAQVEIVTDGEEPAEMIQVLGPKPALKEGNPAQAAALYKVSDATGQMNLTKVADSSPFALELLISDDCFVLDNGLCGKIYIWKGRKANEKERQAALQVAEGFISRMQYAPNTQVEILPQGRESPIFKQFFKDW'],
 ['1jhw_2',
  'PFPGSVQDPGLHVWRVEKLKPVPVAQENQGVFFSGDSYLVLHNGPEEVSHLHLWIGQQSSRDEQGACAVLAVQLDDYLGGRPVQHREVQGNESDLFMSYFPRGLKYQEGGVESGFKHVVPNEVVVQRLYQVKGAKNIRATERALNWDSFNTGDCFILDLGQNIFAWCGGKSNILERNKARDLALAIRDSERQGKAQVEIVTDGEEPAEMIQVLGPKPALKEGNPAQAAALYKVSDATGQMNLTKVADSSPFALELLISDDCFVLDNGLCGKIYIWKGRKANEKERQAALQVAEGFISRMQYAPNTQVEILPQGRESPIFKQFFKDW'],
 ['1qsl_A',
  'MISYDNYVTILDEETLKAWIAKLEKAPVFAFDTETDSLDNISANLVGLSFAIEPGVAAYIPVAHDYLDAPDQISRERALELLKPLLEDEKALKVGQNLKYDRGILANYGIELRGIAFDTMLESYILNSVAGRHDMDSLAERWLKHKTITFEEIAGKGKNQLTFNQIALEEAGRYAAEDADVTLQLHLKMWPDLQKHKGPLNVFENIEMPLVPVLSRIERNGVKIDPKVLHNHSEELTLRLAELEKKAHEIAGEEFNLSSTKQLQTILFEKQGIKPLKKTPSTSEEVLEELALDYPLPKVILEYRGLAKLKSTYTDKLPLMINPKTGRVHTSYHQAVTATGRLSSTDPNLQNIPVRNEEGRRIRQAFIAPEDYVIVSADYSQIELRIMAHLSRDKGLLTAFAEGKDIHRATAAEVFGLPLETVTSEQRRSAKAINFGLIYGMSAFGLARQLNIPRKEAQKYMDLYFERYPGVLEYMERTRAQAKEQGYVETLDGRRLYLPDIKSSNGARRAAAERAAINAPMQGTAADIIKRAMIAVDAWLQAEQPRVRMIMQVHDELVFEVHKDDVDAVAKQIHQLMENCTRLDVPLLVEVGSGENWDQAH'],
 ['2fby_1',
  'HHSVFEDDLPFLEFTGSIVYSYDASDCSFLSEDISMSLSDGDVVGFDMEWPPLYNRGKLGKVALIQLCVSESKCYLFHVSSMSVFPQGLKMLLENKAVKKAGVGIEGDQWKLLRDFDIKLKNFVELTDVANKKLKCTETWSLNSLVKHLLGKQLLKDKSIRCSNWSKFPLTEDQKLYAATDAYAGFIIYRNLEILD'],
 ['1wc4_A',
  'SHMRPEPRLITILFSDIVGFTRMSNALQSQGVAELLNEYLGEMTRAVFENQGTVDKFVGDAIMALYGAPEEMSPSEQVRRAIATARQMLVALEKLNQGWQERGLVGRNEVPPVRFRCGIHQGMAVVGLFGSQERSDFTAIGPSVNIAARLQEATAPNSIMVSAMVAQYVPDEEIIKREFLELKGIDEPVMTCVINPNMLN'],
 ['1wc4_2',
  'MRPEPRLITILFSDIVGFTRMSNALQSQGVAELLNEYLGEMTRAVFENQGTVDKFVGDAIMALYGAPEEMSPSEQVRRAIATARQMLVALEKLNQGWQERGLVGRVPPVRFRCGIHQGMAVVGLFGSQERSDFTAIGPSVNIAARLQEATAPNSIMVSAMVAQYVPDEEIIKREFLELKGIDEPVMTCVINPNMLN'],
 ['2fby_A',
  'HHSVFEDDLPFLEFTGSIVYSYDASDCSFLSEDISMSLSDGDVVGFDMEWPPLYNRGKLGKVALIQLCVSESKCYLFHVSSMSVFPQGLKMLLENKAVKKAGVGIEGDQWKLLRDFDIKLKNFVELTDVANKKLKCTETWSLNSLVKHLLGKQLLKDKSIRCSNWSKFPLTEDQKLYAATDAYAGFIIYRNLEILD'],
 ['1qsl_1',
  'MISYDNYVTILDEETLKAWIAKLEKAPVFAFDTETDSLDNISANLVGLSFAIEPGVAAYIPVAHDYLDAPDQISRERALELLKPLLEDEKALKVGQNLKYDRGILANYGIELRGIAFDTMLESYILNSVAGRHDMDSLAERWLKHKTITFEEIAGKGKNQLTFNQIALEEAGRYAAEDADVTLQLHLKMWPDLQKHKGPLNVFENIEMPLVPVLSRIERNGVKIDPKVLHNHSEELTLRLAELEKKAHEIAGEEFNLSSTKQLQTILFEKQGIKPLKKTPSTSEEVLEELALDYPLPKVILEYRGLAKLKSTYTDKLPLMINPKTGRVHTSYHQAVTATGRLSSTDPNLQNIPVRNEEGRRIRQAFIAPEDYVIVSADYSQIELRIMAHLSRDKGLLTAFAEGKDIHRATAAEVFGLPLETVTSEQRRSAKAINFGLIYGMSAFGLARQLNIPRKEAQKYMDLYFERYPGVLEYMERTRAQAKEQGYVETLDGRRLYLPDIKSSNGARRAAAERAAINAPMQGTAADIIKRAMIAVDAWLQAEQPRVRMIMQVHDELVFEVHKDDVDAVAKQIHQLMENCTRLDVPLLVEVGSGENWDQAH'],
 ['2p1x_A',
  'MNDSEFHRLADQLWLTIEERLDDWDGDSDIDCEINGGVLTITFENGSKIIINRQEPLHQVWLATKQGGYHFDLKGDEWICDRSGETFWDLLEQAATQQAGETVSFR'],
 ['4lp1_3',
  'MNDSEFIQLADQLYQKIEEKIEESGADVDYDQNGSLLTLEFENHTKLIINRQQPLHQVWLATLENGHHYDYNNGKWIDDRSGDEFLTFLSAAIFKQSKETVDFT'],
 ['4lp1_1',
  'MNDSEFIQLADQLYQKIEEKIEESGADVDYDQNGSLLTLEFENHTKLIINRQQPLHQVWLATLENGHHYDYNNGKWIDDRSGDEFLTFLSAAIFKQSKETVDFT'],
 ['4lp1_B',
  'MNDSEFIQLADQLYQKIEEKIEESGADVDYDQNGSLLTLEFENHTKLIINRQQPLHQVWLATLENGHHYDYNNGKWIDDRSGDEFLTFLSAAIFKQSKETVDFT'],
 ['4lp1_A',
  'MNDSEFIQLADQLYQKIEEKIEESGADVDYDQNGSLLTLEFENHTKLIINRQQPLHQVWLATLENGHHYDYNNGKWIDDRSGDEFLTFLSAAIFKQSKETVDFT'],
 ['4lp1_10',
  'MNDSEFIQLADQLYQKIEEKIEESGADVDYDQNGSLLTLEFENHTKLIINRQQPLHQVWLATLENGHHYDYNNGKWIDDRSGDEFLTFLSAAIFKQSKETVDFT'],
 ['4lp1_6',
  'MNDSEFIQLADQLYQKIEEKIEESGADVDYDQNGSLLTLEFENHTKLIINRQQPLHQVWLATLENGHHYDYNNGKWIDDRSGDEFLTFLSAAIFKQSKETVDFT'],
 ['4bar_A',
  'ATFEIVNRCSYTVWAAASKGDAALDAGGRQLNSGESWTINVEPGTNGGKIWARTDCYFDDSGSGICKTGDCGGLLRCKRFGRPPTTLAEFSLNQYGKDYIDISNIKGFNVPMNFSPTTRGCRGVRCAADIVGQCPAKLKAPGGGCNDACTVFQTSEYCCTTGKCGPTEYSRFFKRLCPDAFSYVLDKPTTVTCPGSSNYRVTFCPTA'],
 ['4bap_A',
  'KVFGRCELAAAMKRHGLDNYRGYSLGNWVCAAKFESNFNTQATNRNTDGSTDYGILQINSRWWCNDGRTPGSRNLCNIPCSALLSSDITASVNCAKKIVSDGNGMNAWVAWRNRCKGTDVQAWIRGCRL'],
 ['4bad_A',
  'KVFGRCELAAAMKRHGLDNYRGYSLGNWVCAAKFESNFNTQATNRNTDGSTDYGILQINSRWWCNDGRTPGSRNLCNIPCSALLSSDITASVNCAKKIVSDGNGMNAWVAWRNRCKGTDVQAWIRGCRL'],
 ['3tor_C',
  'TVEAKNETFAPQHPDQYLSWKATSEQSERVDALAEDPRLVILWAGYPFSRDYNKPRGHAFAVTDVRETLRTGAPKNAEDGPLPMACWSCKSPDVARLIQKDGEDGYFHGKWARGGPEIVNNLGCADCHNTASPEFAKGKPELTLSRPYAARAMEAIGKPFEKAGRFDQQSMVCGQCHVEYYFDGKNKAVKFPWDDGMKVENMEQYYDKIAFSDWTNSLSKTPMLKAQHPEYETWTAGIHGKNNVTCIDCHMPKVQNAEGKLYTDHKIGNPFDNFAQTCANCHTQDKAALQKVVAERKQSINDLKIKVEDQLVHAHFEAKAALDAGATEAEMKPIQDDIRHAQWRWDLAIASHGIHMHAPEEGLRMLGTAMDKAADARTKLARLLATKGITHEIQIPDISTKEKAQQAIGLNMEQIKAEKQDFIKTVIPQWEEQARKNGLLS'],
 ['3tor_11',
  'TVEAKNETFAPQHPDQYLSWKATSEQSERVDALAEDPRLVILWAGYPFSRDYNKPRGHAFAVTDVRETLRTGAPKNAEDGPLPMACWSCKSPDVARLIQKDGEDGYFHGKWARGGPEIVNNLGCADCHNTASPEFAKGKPELTLSRPYAARAMEAIGKPFEKAGRFDQQSMVCGQCHVEYYFDGKNKAVKFPWDDGMKVENMEQYYDKIAFSDWTNSLSKTPMLKAQHPEYETWTAGIHGKNNVTCIDCHMPKVQNAEGKLYTDHKIGNPFDNFAQTCANCHTQDKAALQKVVAERKQSINDLKIKVEDQLVHAHFEAKAALDAGATEAEMKPIQDDIRHAQWRWDLAIASHGIHMHAPEEGLRMLGTAMDKAADARTKLARLLATKGITHEIQIPDISTKEKAQQAIGLNMEQIKAEKQDFIKTVIPQWEEQARKNGLLS'],
 ['3tor_18',
  'TVEAKNETFAPQHPDQYLSWKATSEQSERVDALAEDPRLVILWAGYPFSRDYNKPRGHAFAVTDVRETLRTGAPKNAEDGPLPMACWSCKSPDVARLIQKDGEDGYFHGKWARGGPEIVNNLGCADCHNTASPEFAKGKPELTLSRPYAARAMEAIGKPFEKAGRFDQQSMVCGQCHVEYYFDGKNKAVKFPWDDGMKVENMEQYYDKIAFSDWTNSLSKTPMLKAQHPEYETWTAGIHGKNNVTCIDCHMPKVQNAEGKLYTDHKIGNPFDNFAQTCANCHTQDKAALQKVVAERKQSINDLKIKVEDQLVHAHFEAKAALDAGATEAEMKPIQDDIRHAQWRWDLAIASHGIHMHAPEEGLRMLGTAMDKAADARTKLARLLATKGITHEIQIPDISTKEKAQQAIGLNMEQIKAEKQDFIKTVIPQWEEQARKNGLLS'],
 ['3tor_9',
  'TVEAKNETFAPQHPDQYLSWKATSEQSERVDALAEDPRLVILWAGYPFSRDYNKPRGHAFAVTDVRETLRTGAPKNAEDGPLPMACWSCKSPDVARLIQKDGEDGYFHGKWARGGPEIVNNLGCADCHNTASPEFAKGKPELTLSRPYAARAMEAIGKPFEKAGRFDQQSMVCGQCHVEYYFDGKNKAVKFPWDDGMKVENMEQYYDKIAFSDWTNSLSKTPMLKAQHPEYETWTAGIHGKNNVTCIDCHMPKVQNAEGKLYTDHKIGNPFDNFAQTCANCHTQDKAALQKVVAERKQSINDLKIKVEDQLVHAHFEAKAALDAGATEAEMKPIQDDIRHAQWRWDLAIASHGIHMHAPEEGLRMLGTAMDKAADARTKLARLLATKGITHEIQIPDISTKEKAQQAIGLNMEQIKAEKQDFIKTVIPQWEEQARKNGLLS'],
 ['3tor_B',
  'TVEAKNETFAPQHPDQYLSWKATSEQSERVDALAEDPRLVILWAGYPFSRDYNKPRGHAFAVTDVRETLRTGAPKNAEDGPLPMACWSCKSPDVARLIQKDGEDGYFHGKWARGGPEIVNNLGCADCHNTASPEFAKGKPELTLSRPYAARAMEAIGKPFEKAGRFDQQSMVCGQCHVEYYFDGKNKAVKFPWDDGMKVENMEQYYDKIAFSDWTNSLSKTPMLKAQHPEYETWTAGIHGKNNVTCIDCHMPKVQNAEGKLYTDHKIGNPFDNFAQTCANCHTQDKAALQKVVAERKQSINDLKIKVEDQLVHAHFEAKAALDAGATEAEMKPIQDDIRHAQWRWDLAIASHGIHMHAPEEGLRMLGTAMDKAADARTKLARLLATKGITHEIQIPDISTKEKAQQAIGLNMEQIKAEKQDFIKTVIPQWEEQARKNGLLS'],
 ['3tf6_C',
  'SDLIPAPPLSKVPLQQNFQDNQFQGKWYVVGLAGNAILREDKDPQKMYATIYELKEDKSYNVTSVLFRKKKCDYWIRTFVPGSQPGEFTLGNIKSYPGLTSYLVRVVSTNYNQHAMVFFKKVSQNREYFKITLYGRTKELTSELKENFIRFSKSLGLPENHIVFPVPIDQCID'],
 ['3py9_A',
  'ETPDVIGKSVKEAEQIFNKNNLKLGKISRSYSDKYPENEIIKTTPNTGERVERGDSVDVVISKGPEKVKMPNVIGLPKEEALQKLKSLGLKDVTIEKVYNNQAPKGYIANQSVTATEIAIHDSNIKLYESLGIKQVYVEDFEHKSFSKAKKALEEKGFKVESKEEYSDDIDEGDVISQSPKGKSVDEGSTISFVVSKGKKSVKTTTESVDVPYTGKNDKSQKVKVYIKDKDNDGSTEKGSFDITSDQRIDIPLRIEKGKTASYIVKVDGKTVAEKEVSYD'],
 ['3ojo_A',
  'SKLTVVGLGYIGLPTSIMFAKHGVDVLGVDINQQTIDKLQNGQISIEEPGLQEVYEEVLSSGKLKVSTTPEASDVFIIAVPTPNNDDQYRSCDISLVMRALDSILPFLKKGNTIIVESTIAPKTMDDFVKPVIENLGFTIGEDIYLVHCPERVLPGKILEELVHNNRIIGGVTKACIEAGKRVYRTFVQGEMIETDARTAEMSKLMENTYRDVNIALANELTKICNNLNINVLDVIEMANKHPRVNIHQPGPGVGGHCLAVDPNAKLIQTGREINNSMPAYVVDTTKQIIKALSGNKVTVFGLTYKGDVDDIRESPAFDIYELLNQEPDIEVCAYDPHVELDFVEHDMSHAVKDASLVLILSDHSEFKNLSDSHFDKMKHKVIFDTKNVVKSSFEDVLYYNYGNIFNFI'],
 ['3mvo_A',
  'ADREDDPNFFKMVEGFFDRGASIVEDKLVEDLKTRETEEQKRNRVRSILRIIKPCNHVLSLSFPIRRDDGSWEVIEGYRAQHSQHRTPCKGGIRYSTDVSVDEVKALASLMTYKCAVVDVPFGGAKAGVKINPKNYTDNELEKITRRFTMELAKKGFIGPGVDVPAPDMSTGEREMSWIADTYASTIGHYDINAHACVTGKPISQGGIHGRISATGRGVFHGIENFINEASYMSILGMTPGFGDKTFVVQGFGNVGLHSMRYLHRFGAKCITVGESDGSIWNPDGIDPKELEDFKLQHGTILGFPKAKIYEGSILEVDCDILIPAASEKQLTKSNAPRVKAKIIAEGANGPTTPEADKIFLERNIMVIPDLYLNAGGVTVSYFEWLNNLNHVSYGRLTFKYERDSNYHLLMSVQESLERKFGKHGGTIPIVPTAEFQDRISGASEKDIVHSGLAYTMERSARQIMRTAMKYNLGLDLRTAAYVNAIEKVFRVYNEE'],
 ['3lgr_A',
  'TIQPGTGYNNGYFYSYWNDGHGGVTYTNGPGGQFSVNWSNSGNFVGGKGWQPGTKNKVINFSGSYNPNGNSYLSVYGWSRNPLIEYYIVENFGTYNPSTGATKLGEVTSDGSVYDIYRTQRVNQPSIIGTATFYQYWSVRRNHRSSGSVNTANHFNAWAQQGLTLGTMDYQIVAVEGYFSSGSASITVS'],
 ['2yat_A',
  'SKKNSLALSLTADQMVSALLDAEPPILYSESMMGLLTNLADRELVHMINWAKRVPGFVDLTLHDQVHLLESAWLEILMIGLVWRSMEHPGKLLFAPNLLLDRNEIFDMLLATSSRFRMMNLQGEEFVCLKSIILLNSGVYTFSTLKSLEEKDHIHRVLDKITDTLIHLMAKAGLTLQQQHQRLAQLLLILSHIRHMSNKGMEHLYSMKSKNVVPLYDLLLEMLDAHR'],
 ['2pe7_A',
  'ATFEIVNRCSYTVWAAASKGDAALDAGGRQLNSGESWTINVEPGTNGGKIWARTDCYFDDSGSGICKTGDCGGLLRCKRFGRPPTTLAEFSLNQYGKDYIDISNIKGFNVPMDFSPTTRGCRGVRCAADIVGQCPAKLKAPGGGCNDACTVFQTSEYCCTTGKCGPTEYSRFFKRLCPDAFSYVLDKPTTVTCPGSSNYRVTFCPTA'],
 ['2pc2_A',
  'KVFGRCELAAAMKRHGLDNYRGYSLGNWVCAAKFESNFNTQATNRNTDGSTDYGILQINSRWWCNDGRTPGSRNLCNIPCSALLSSDITASVNCAKKIVSDGNGMNAWVAWRNRCKGTDVQAWIRGCRL']]

In [13]:
test_df = pd.DataFrame(seq_info, columns = ['Entity ID', 'Sequence'])
test_df

   Entity ID                                           Sequence
0     1jhw_A  PFPGSVQDPGLHVWRVEKLKPVPVAQENQGVFFSGDSYLVLHNGPE...
1     1jhw_2  PFPGSVQDPGLHVWRVEKLKPVPVAQENQGVFFSGDSYLVLHNGPE...
2     1qsl_A  MISYDNYVTILDEETLKAWIAKLEKAPVFAFDTETDSLDNISANLV...
3     2fby_1  HHSVFEDDLPFLEFTGSIVYSYDASDCSFLSEDISMSLSDGDVVGF...
4     1wc4_A  SHMRPEPRLITILFSDIVGFTRMSNALQSQGVAELLNEYLGEMTRA...
5     1wc4_2  MRPEPRLITILFSDIVGFTRMSNALQSQGVAELLNEYLGEMTRAVF...
6     2fby_A  HHSVFEDDLPFLEFTGSIVYSYDASDCSFLSEDISMSLSDGDVVGF...
7     1qsl_1  MISYDNYVTILDEETLKAWIAKLEKAPVFAFDTETDSLDNISANLV...
8     2p1x_A  MNDSEFHRLADQLWLTIEERLDDWDGDSDIDCEINGGVLTITFENG...
9     4lp1_3  MNDSEFIQLADQLYQKIEEKIEESGADVDYDQNGSLLTLEFENHTK...
10    4lp1_1  MNDSEFIQLADQLYQKIEEKIEESGADVDYDQNGSLLTLEFENHTK...
11    4lp1_B  MNDSEFIQLADQLYQKIEEKIEESGADVDYDQNGSLLTLEFENHTK...
12    4lp1_A  MNDSEFIQLADQLYQKIEEKIEESGADVDYDQNGSLLTLEFENHTK...
13   4lp1_10  MNDSEFIQLADQLYQKIEEKIEESGADVDYDQNGSLLTLEFENHTK...
14    4lp1_6  MNDSEFIQLADQLYQKIEEKIEESGADVDYDQNGSLLTLEFENHTK...
15    4bar_A  ATFEIVNRCSYTVWAAASKGDAALDAGGRQLNSGESWTINVEPGTN...
16    4bap_A  KVFGRCELAAAMKRHGLDNYRGYSLGNWVCAAKFESNFNTQATNRN...
17    4bad_A  KVFGRCELAAAMKRHGLDNYRGYSLGNWVCAAKFESNFNTQATNRN...
18    3tor_C  TVEAKNETFAPQHPDQYLSWKATSEQSERVDALAEDPRLVILWAGY...
19   3tor_11  TVEAKNETFAPQHPDQYLSWKATSEQSERVDALAEDPRLVILWAGY...
20   3tor_18  TVEAKNETFAPQHPDQYLSWKATSEQSERVDALAEDPRLVILWAGY...
21    3tor_9  TVEAKNETFAPQHPDQYLSWKATSEQSERVDALAEDPRLVILWAGY...
22    3tor_B  TVEAKNETFAPQHPDQYLSWKATSEQSERVDALAEDPRLVILWAGY...
23    3tf6_C  SDLIPAPPLSKVPLQQNFQDNQFQGKWYVVGLAGNAILREDKDPQK...
24    3py9_A  ETPDVIGKSVKEAEQIFNKNNLKLGKISRSYSDKYPENEIIKTTPN...
25    3ojo_A  SKLTVVGLGYIGLPTSIMFAKHGVDVLGVDINQQTIDKLQNGQISI...
26    3mvo_A  ADREDDPNFFKMVEGFFDRGASIVEDKLVEDLKTRETEEQKRNRVR...
27    3lgr_A  TIQPGTGYNNGYFYSYWNDGHGGVTYTNGPGGQFSVNWSNSGNFVG...
28    2yat_A  SKKNSLALSLTADQMVSALLDAEPPILYSESMMGLLTNLADRELVH...
29    2pe7_A  ATFEIVNRCSYTVWAAASKGDAALDAGGRQLNSGESWTINVEPGTN...
30    2pc2_A  KVFGRCELAAAMKRHGLDNYRGYSLGNWVCAAKFESNFNTQATNRN...

In [14]:
# test_df = pd.read_csv("../Data/Input/rcsb_pdb_sequence_hemeproteins_All_removed.csv")

In [15]:
# test_df

In [16]:
rowNum = test_df.shape[0]
colNum = test_df.shape[1]

In [17]:
out_meanvarstdlen = pd.DataFrame(columns=['Entity_ID','mean','var','std','len'], index=range(rowNum))
out_meanvarstdlen

   Entity_ID mean  var  std  len
0        NaN  NaN  NaN  NaN  NaN
1        NaN  NaN  NaN  NaN  NaN
2        NaN  NaN  NaN  NaN  NaN
3        NaN  NaN  NaN  NaN  NaN
4        NaN  NaN  NaN  NaN  NaN
5        NaN  NaN  NaN  NaN  NaN
6        NaN  NaN  NaN  NaN  NaN
7        NaN  NaN  NaN  NaN  NaN
8        NaN  NaN  NaN  NaN  NaN
9        NaN  NaN  NaN  NaN  NaN
10       NaN  NaN  NaN  NaN  NaN
11       NaN  NaN  NaN  NaN  NaN
12       NaN  NaN  NaN  NaN  NaN
13       NaN  NaN  NaN  NaN  NaN
14       NaN  NaN  NaN  NaN  NaN
15       NaN  NaN  NaN  NaN  NaN
16       NaN  NaN  NaN  NaN  NaN
17       NaN  NaN  NaN  NaN  NaN
18       NaN  NaN  NaN  NaN  NaN
19       NaN  NaN  NaN  NaN  NaN
20       NaN  NaN  NaN  NaN  NaN
21       NaN  NaN  NaN  NaN  NaN
22       NaN  NaN  NaN  NaN  NaN
23       NaN  NaN  NaN  NaN  NaN
24       NaN  NaN  NaN  NaN  NaN
25       NaN  NaN  NaN  NaN  NaN
26       NaN  NaN  NaN  NaN  NaN
27       NaN  NaN  NaN  NaN  NaN
28       NaN  NaN  NaN  NaN  NaN
29       NaN  NaN  NaN  NaN  NaN
30       NaN  NaN  NaN  NaN  NaN

In [18]:
# fill the IDs
for i in range(rowNum):
    out_meanvarstdlen.iloc[i][0] = test_df.iloc[i][0]

out_meanvarstdlen

   Entity_ID mean  var  std  len
0     1jhw_A  NaN  NaN  NaN  NaN
1     1jhw_2  NaN  NaN  NaN  NaN
2     1qsl_A  NaN  NaN  NaN  NaN
3     2fby_1  NaN  NaN  NaN  NaN
4     1wc4_A  NaN  NaN  NaN  NaN
5     1wc4_2  NaN  NaN  NaN  NaN
6     2fby_A  NaN  NaN  NaN  NaN
7     1qsl_1  NaN  NaN  NaN  NaN
8     2p1x_A  NaN  NaN  NaN  NaN
9     4lp1_3  NaN  NaN  NaN  NaN
10    4lp1_1  NaN  NaN  NaN  NaN
11    4lp1_B  NaN  NaN  NaN  NaN
12    4lp1_A  NaN  NaN  NaN  NaN
13   4lp1_10  NaN  NaN  NaN  NaN
14    4lp1_6  NaN  NaN  NaN  NaN
15    4bar_A  NaN  NaN  NaN  NaN
16    4bap_A  NaN  NaN  NaN  NaN
17    4bad_A  NaN  NaN  NaN  NaN
18    3tor_C  NaN  NaN  NaN  NaN
19   3tor_11  NaN  NaN  NaN  NaN
20   3tor_18  NaN  NaN  NaN  NaN
21    3tor_9  NaN  NaN  NaN  NaN
22    3tor_B  NaN  NaN  NaN  NaN
23    3tf6_C  NaN  NaN  NaN  NaN
24    3py9_A  NaN  NaN  NaN  NaN
25    3ojo_A  NaN  NaN  NaN  NaN
26    3mvo_A  NaN  NaN  NaN  NaN
27    3lgr_A  NaN  NaN  NaN  NaN
28    2yat_A  NaN  NaN  NaN  NaN
29    2pe7_A  NaN  NaN  NaN  NaN
30    2pc2_A  NaN  NaN  NaN  NaN

In [19]:
for i in range(0, rowNum):                     # loop through all rows
    j = 1                                      # only one seq
    if isinstance(test_df.iloc[i,j],str):      # whether the cell is a string or NaN
        l = len(test_df.iloc[i,j])             # determine the length at the cell
        lst = [None] * l                       # create an empty list with the deterined length to be filled                     
        for p in range(l):                     # assign hydrophobicity number according to the sigmaaldrich website
            if test_df.iloc[i,j][p] == 'F':    # https://www.sigmaaldrich.com/US/en/technical-documents/technical-article/protein-biology/protein-structural-analysis/amino-acid-reference-chart#hydro
                lst[p] = 100
            elif test_df.iloc[i,j][p] == 'I':
                lst[p] = 99
            elif test_df.iloc[i,j][p] == 'W':
                lst[p] = 97
            elif test_df.iloc[i,j][p] == 'L':
                lst[p] = 97
            elif test_df.iloc[i,j][p] == 'V':
                lst[p] = 76
            elif test_df.iloc[i,j][p] == 'M':
                lst[p] = 74
            elif test_df.iloc[i,j][p] == 'Y':
                lst[p] = 63
            elif test_df.iloc[i,j][p] == 'C':
                lst[p] = 49
            elif test_df.iloc[i,j][p] == 'A':
                lst[p] = 41
            elif test_df.iloc[i,j][p] == 'T':
                    lst[p] = 13
            elif test_df.iloc[i,j][p] == 'H':
                lst[p] = 8
            elif test_df.iloc[i,j][p] == 'G':
                lst[p] = 0
            elif test_df.iloc[i,j][p] == 'S':
                lst[p] = -5
            elif test_df.iloc[i,j][p] == 'Q':
                lst[p] = -10
            elif test_df.iloc[i,j][p] == 'R':
                lst[p] = -14
            elif test_df.iloc[i,j][p] == 'K':
                lst[p] = -23
            elif test_df.iloc[i,j][p] == 'N':
                lst[p] = -28
            elif test_df.iloc[i,j][p] == 'E':
                lst[p] = -31
            elif test_df.iloc[i,j][p] == 'P':
                lst[p] = -46
            elif test_df.iloc[i,j][p] == 'D':
                lst[p] = -55
            else:                                # print else just in case
                difLetter = test_df.iloc[i,j][p]
                print('There is a', difLetter, 'at row', i, 'location', p)
        mean = statistics.mean(lst)              # calculate mean, std, var
        std = statistics.pstdev(lst)
        var = statistics.pvariance(lst)
        out_meanvarstdlen.iloc[i][1] = mean
        out_meanvarstdlen.iloc[i][2] = var
        out_meanvarstdlen.iloc[i][3] = std
        out_meanvarstdlen.iloc[i][4] = l

In [20]:
out_meanvarstdlen

   Entity_ID       mean          var        std  len
0     1jhw_A  20.377301  2727.492614  52.225402  326
1     1jhw_2  20.377301  2727.492614  52.225402  326
2     1qsl_A  22.477537  2776.615552  52.693601  601
3     2fby_1  26.336735   3030.43763  55.049411  196
4     1wc4_A      24.68    2654.9776  51.526475  200
5     1wc4_2  25.469388  2672.647022   51.69765  196
6     2fby_A  26.336735   3030.43763  55.049411  196
7     1qsl_1  22.477537  2776.615552  52.693601  601
8     2p1x_A   20.45283  3029.342115   55.03946  106
9     4lp1_3  19.663462  2990.838665  54.688561  104
10    4lp1_1  19.663462  2990.838665  54.688561  104
11    4lp1_B  19.663462  2990.838665  54.688561  104
12    4lp1_A  19.663462  2990.838665  54.688561  104
13   4lp1_10  19.663462  2990.838665  54.688561  104
14    4lp1_6  19.663462  2990.838665  54.688561  104
15    4bar_A  18.768116  2300.970384  47.968431  207
16    4bap_A  21.124031  2366.635779  48.648081  129
17    4bad_A  21.124031  2366.635779  48.648081  129
18    3tor_C  16.839002  2516.434397  50.164075  441
19   3tor_11  16.839002  2516.434397  50.164075  441
20   3tor_18  16.839002  2516.434397  50.164075  441
21    3tor_9  16.839002  2516.434397  50.164075  441
22    3tor_B  16.839002  2516.434397  50.164075  441
23    3tf6_C  22.023121  2888.681546  53.746456  173
24    3py9_A  11.342857   2557.56102  50.572335  280
25    3ojo_A  23.114914  2931.422002  54.142608  409
26    3mvo_A  20.983871  2665.721514  51.630626  496
27    3lgr_A  20.550265  2177.485569  46.663536  189
28    2yat_A    32.0837  2932.640571   54.15386  227
29    2pe7_A  18.637681  2316.675488  48.131855  207
30    2pc2_A  21.124031  2366.635779  48.648081  129

In [22]:
out_meanvarstdlen.to_csv(r'out_meanvarstdlen_fullChain.csv', index = False)

<br>

In [23]:
uniqueLen = list(set(out_meanvarstdlen.iloc[:,4]))

In [24]:
l = len(uniqueLen)
l

15

record the mean and std for mean, var and std

In [25]:
stat_var = pd.DataFrame(columns=['mean', 'std', 'len'], index=range(l))

In [26]:
for i in range(l):
    stat_var.iloc[i,2] = uniqueLen[i]

In [27]:
stat_var

   mean  std  len
0   NaN  NaN  129
1   NaN  NaN  227
2   NaN  NaN  196
3   NaN  NaN  326
4   NaN  NaN  200
5   NaN  NaN  104
6   NaN  NaN  106
7   NaN  NaN  441
8   NaN  NaN  409
9   NaN  NaN  173
10  NaN  NaN  207
11  NaN  NaN  496
12  NaN  NaN  280
13  NaN  NaN  601
14  NaN  NaN  189

In [28]:
for i in range(l):
    lst_var = list([])
    for j in range(rowNum):
        if out_meanvarstdlen.iloc[j][4] == stat_var.iloc[i,2]: # group by length/density
            lst_var.append(out_meanvarstdlen.iloc[j,2])
    stat_var.iloc[i,0] = statistics.mean(lst_var)
    stat_var.iloc[i,1] = statistics.pstdev(lst_var)

In [29]:
stat_var

           mean        std  len
0   2366.635779        0.0  129
1   2932.640571        0.0  227
2   2911.174094  168.66411  196
3   2727.492614        0.0  326
4     2654.9776        0.0  200
5   2990.838665        0.0  104
6   3029.342115        0.0  106
7   2516.434397        0.0  441
8   2931.422002        0.0  409
9   2888.681546        0.0  173
10  2308.822936   7.852552  207
11  2665.721514        0.0  496
12   2557.56102        0.0  280
13  2776.615552        0.0  601
14  2177.485569        0.0  189

In [31]:
stat_var.to_csv(r'stat_var_fullProtein.csv', index = False)

_______

In [32]:
meanvar = pd.DataFrame(columns=['mean', 'std', 'len', 'num'], index=range(42))
meanvar

   mean  std  len  num
0   NaN  NaN  NaN  NaN
1   NaN  NaN  NaN  NaN
2   NaN  NaN  NaN  NaN
3   NaN  NaN  NaN  NaN
4   NaN  NaN  NaN  NaN
5   NaN  NaN  NaN  NaN
6   NaN  NaN  NaN  NaN
7   NaN  NaN  NaN  NaN
8   NaN  NaN  NaN  NaN
9   NaN  NaN  NaN  NaN
10  NaN  NaN  NaN  NaN
11  NaN  NaN  NaN  NaN
12  NaN  NaN  NaN  NaN
13  NaN  NaN  NaN  NaN
14  NaN  NaN  NaN  NaN
15  NaN  NaN  NaN  NaN
16  NaN  NaN  NaN  NaN
17  NaN  NaN  NaN  NaN
18  NaN  NaN  NaN  NaN
19  NaN  NaN  NaN  NaN
20  NaN  NaN  NaN  NaN
21  NaN  NaN  NaN  NaN
22  NaN  NaN  NaN  NaN
23  NaN  NaN  NaN  NaN
24  NaN  NaN  NaN  NaN
25  NaN  NaN  NaN  NaN
26  NaN  NaN  NaN  NaN
27  NaN  NaN  NaN  NaN
28  NaN  NaN  NaN  NaN
29  NaN  NaN  NaN  NaN
30  NaN  NaN  NaN  NaN
31  NaN  NaN  NaN  NaN
32  NaN  NaN  NaN  NaN
33  NaN  NaN  NaN  NaN
34  NaN  NaN  NaN  NaN
35  NaN  NaN  NaN  NaN
36  NaN  NaN  NaN  NaN
37  NaN  NaN  NaN  NaN
38  NaN  NaN  NaN  NaN
39  NaN  NaN  NaN  NaN
40  NaN  NaN  NaN  NaN
41  NaN  NaN  NaN  NaN

In [33]:
for i in range(42):
    meanvar.iloc[i,2] = i + 4

In [34]:
for i in range(42):
    lst= list([])
    for j in range(rowNum):
        if round(out_meanvarstdlen.iloc[j][1]) == meanvar.iloc[i,2]: # group them by the rounded mean
            lst.append(out_meanvarstdlen.iloc[j][2])
    if len(lst) != 0:
        meanvar.iloc[i,0] = statistics.mean(lst)
        meanvar.iloc[i,1] = statistics.pstdev(lst)
        meanvar.iloc[i,3] = len(lst)

In [35]:
meanvar

           mean         std len  num
0           NaN         NaN   4  NaN
1           NaN         NaN   5  NaN
2           NaN         NaN   6  NaN
3           NaN         NaN   7  NaN
4           NaN         NaN   8  NaN
5           NaN         NaN   9  NaN
6           NaN         NaN  10  NaN
7    2557.56102         0.0  11    1
8           NaN         NaN  12  NaN
9           NaN         NaN  13  NaN
10          NaN         NaN  14  NaN
11          NaN         NaN  15  NaN
12          NaN         NaN  16  NaN
13  2516.434397         0.0  17    5
14          NaN         NaN  18  NaN
15  2308.822936    7.852552  19    2
16  2936.595481  112.400027  20    9
17  2388.622884  156.724545  21    5
18  2813.970883   52.828416  22    3
19  2931.422002         0.0  23    1
20          NaN         NaN  24  NaN
21  2663.812311    8.834711  25    2
22   3030.43763         0.0  26    2
23          NaN         NaN  27  NaN
24          NaN         NaN  28  NaN
25          NaN         NaN  29  NaN
26          NaN         NaN  30  NaN
27          NaN         NaN  31  NaN
28  2932.640571         0.0  32    1
29          NaN         NaN  33  NaN
30          NaN         NaN  34  NaN
31          NaN         NaN  35  NaN
32          NaN         NaN  36  NaN
33          NaN         NaN  37  NaN
34          NaN         NaN  38  NaN
35          NaN         NaN  39  NaN
36          NaN         NaN  40  NaN
37          NaN         NaN  41  NaN
38          NaN         NaN  42  NaN
39          NaN         NaN  43  NaN
40          NaN         NaN  44  NaN
41          NaN         NaN  45  NaN

In [36]:
meanvar.to_csv(r'meanvar_fullProtein.csv', index = False)